### ISSUE TITLE
[Bug]: add_init_script throws TypeError

### ISSUE THREAD

**Issue by imaxwen** [microsoft/playwright-python#1000]
### Playwright version

1.16.0

### Operating system

MacOS

### What browsers are you seeing the problem on?

Chromium

### Other information
Python Version: 3.8.12
Playwright Version: 1.16.0
Here is my `test_login` function definition, Following the [official documentation](https://playwright.dev/python/docs/auth#session-storage) I tried to set sessionStorage via `context.add_init_script()`

### What happened? / Describe the bug

Here comes the error:

```
 context.add_init_script("""storage => {
TypeError: add_init_script() takes from 1 to 2 positional arguments but 3 were given
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x7f989001de50>
Traceback (most recent call last):
  File "/Users/maxwen/.conda/envs/csvw-spider/lib/python3.8/asyncio/base_subprocess.py", line 126, in __del__
    self.close()
  File "/Users/maxwen/.conda/envs/csvw-spider/lib/python3.8/asyncio/base_subprocess.py", line 104, in close
    proto.pipe.close()
  File "/Users/maxwen/.conda/envs/csvw-spider/lib/python3.8/asyncio/unix_events.py", line 536, in close
    self._close(None)
  File "/Users/maxwen/.conda/envs/csvw-spider/lib/python3.8/asyncio/unix_events.py", line 560, in _close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/Users/maxwen/.conda/envs/csvw-spider/lib/python3.8/asyncio/base_events.py", line 719, in call_soon
    self._check_closed()
  File "/Users/maxwen/.conda/envs/csvw-spider/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

### Code snippet to reproduce your bug

```shell
def test_login():

    global session_storage, local_storage

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
        context = browser.new_context()

        context.add_cookies(LOGIN_COOKIES)
        context.add_init_script("""storage => {
                       entries = JSON.parse(storage)
                       Object.keys(entries).forEach(key => {
                           window.sessionStorage.setItem(key, entries[key])
                       })
                   }""", session_storage)

        page = context.new_page()
        page.goto('https://my-test-site.com/')
```

**Comment by mxschmitt** [comment]
Good catch, the examples in the docs was incorrect, something like that should work:

```py
session_storage = os.environ["SESSION_STORAGE"]
context.add_init_script("""(storage => {
  if (window.location.hostname == 'example.com') {
    entries = JSON.parse(storage)
    for (const [key, value] of Object.entries(entries)) {
      window.sessionStorage.setItem(key, value)
    }
  }
})('""" + session_storage + "')")
```
