### ISSUE TITLE
[Bug]: Raising an exception inside page.on('dialog') is supressed.

### ISSUE THREAD

**Issue by leandrodesouzadev** [microsoft/playwright-python#1017]
### Playwright version

1.16.1

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### Other information

Python 3.9.1 running on Windows 10

### What happened? / Describe the bug

I'm trying to raise an exception inside the dialog handler function. But when i do it, the exception seems to be handled internally by playwright. In some cases, it's interesting to not just ignore the dialogs. But without being able to raise an exception, am i stuck with registering an error instance in a variable and further on raise it.

An example of when not works, based on the doc, added the raise statement.
https://playwright.dev/python/docs/api/class-dialog

Is this the intented behavior?

Thanks in advance for the great work.

### Code snippet to reproduce your bug

```shell
from playwright.sync_api import sync_playwright

def handle_dialog(dialog):
    print(dialog.message)
    dialog.dismiss()
    raise ValueError("This does not goes up the call stack")

def run(playwright):
    chromium = playwright.chromium
    browser = chromium.launch()
    page = browser.new_page()
    page.on("dialog", handle_dialog)
    page.evaluate("alert('1')")
    browser.close()

with sync_playwright() as playwright:
    run(playwright)
```

**Comment by mxschmitt** [comment]
What do you mean with suppressed? That it never gets shown?

I tried to reproduce but for me its working as intended: 

```py
(env) ➜  playwright-python git:(master) ✗ python test.py                                                      
1
Exception in callback SyncBase._sync.<locals>.callback(<Task finishe...> result=None>) at /Users/max/development/playwright-python/playwright/_impl/_sync_base.py:104
handle: <Handle SyncBase._sync.<locals>.callback(<Task finishe...> result=None>) at /Users/max/development/playwright-python/playwright/_impl/_sync_base.py:104>
Traceback (most recent call last):
  File "/Users/max/.pyenv/versions/3.9.7/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/max/development/playwright-python/playwright/_impl/_sync_base.py", line 105, in callback
    g_self.switch()
  File "/Users/max/development/playwright-python/playwright/_impl/_page.py", line 155, in <lambda>
    self._channel.on("dialog", lambda params: self._on_dialog(params))
  File "/Users/max/development/playwright-python/playwright/_impl/_page.py", line 249, in _on_dialog
    self.emit(Page.Events.Dialog, dialog)
  File "/Users/max/development/playwright-python/env/lib/python3.9/site-packages/pyee/_base.py", line 115, in emit
    handled = self._call_handlers(event, args, kwargs)
  File "/Users/max/development/playwright-python/env/lib/python3.9/site-packages/pyee/_base.py", line 98, in _call_handlers
    self._emit_run(f, args, kwargs)
  File "/Users/max/development/playwright-python/env/lib/python3.9/site-packages/pyee/_asyncio.py", line 43, in _emit_run
    self.emit("error", exc)
  File "/Users/max/development/playwright-python/env/lib/python3.9/site-packages/pyee/_base.py", line 118, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/Users/max/development/playwright-python/env/lib/python3.9/site-packages/pyee/_base.py", line 88, in _emit_handle_potential_error
    raise error
  File "/Users/max/development/playwright-python/env/lib/python3.9/site-packages/pyee/_asyncio.py", line 41, in _emit_run
    coro = f(*args, **kwargs)
  File "/Users/max/development/playwright-python/playwright/_impl/_impl_to_api_mapping.py", line 89, in wrapper_func
    return handler(
  File "/Users/max/development/playwright-python/test.py", line 6, in handle_dialog
    raise ValueError("This does not goes up the call stack")
ValueError: This does not goes up the call stack
```

**Comment by leandrodesouzadev** [comment]
I think i have missed some background information. The page i'm working on its an ASPX site. When i input some info and press tab, an async request is sent to the server, when this request finishes the dialog shows up. In this snippet will be more clear what am i trying to accomplish. On my case, i can see the error being raised, but the program keeps on going a few lines and then raises a TimeoutError.

My code looks something like this:

`

    from playwright.sync_api import Page, ElementHandle, Dialog, sync_playwright


    class Handler:
        def __init__(self, page: Page):
            self.page = page
        
        def fill_form(self, data: dict):
            self.page.on('dialog', self.__dialog_handler)
            document_handle: ElementHandle = self.page.wait_for_selector('#document_input_id')
            document_handle.fill(data['document'])
            # This triggers the request
            self.page.keyboard.press('Tab')
            self.page.evaluate('alert("1")')

            #After this, if no alert is present i want to keep filling the form
            # It raises an TimeoutError on this line
            address_handle: ElementHandle = self.page.wait_for_selector('#address_select_id')
            address_handle.select_option(data['address'])

        def __dialog_handler(self, dialog: Dialog):
            message = dialog.message
            dialog.dismiss()
            raise Exception(message)


    with sync_playwright() as p:
        browser = p.chromium.launch()
        page = browser.new_page()

        handler = Handler(page)
        handler.fill_form({
            'document': '123',
            'address': 'some street'
        })
`

This is my real code exception traceback. The exception im raising is: UserPromoterAlreadyExistsError
`Exception in callback SyncBase._sync.<locals>.callback(<Task finishe...> result=None>) at c:\Users\leandro.souza.JEA\Dev\Projetos Em Desenvolvimento\scrapers\venv\lib\site-packages\playwright\_impl\_sync_base.py:104
handle: <Handle SyncBase._sync.<locals>.callback(<Task finishe...> result=None>) at c:\Users\leandro.souza.JEA\Dev\Projetos Em Desenvolvimento\scrapers\venv\lib\site-packages\playwright\_impl\_sync_base.py:104>
Traceback (most recent call last):
  File "C:\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\leandro.souza.JEA\Dev\Projetos Em Desenvolvimento\scrapers\venv\lib\site-packages\playwright\_impl\_sync_base.py", line 105, in callback
    g_self.switch()
  File "c:\Users\leandro.souza.JEA\Dev\Projetos Em Desenvolvimento\scrapers\venv\lib\site-packages\playwright\_impl\_page.py", line 155, in <lambda>
    self._channel.on("dialog", lambda params: self._on_dialog(params))
  File "c:\Users\leandro.souza.JEA\Dev\Projetos Em Desenvolvimento\scrapers\venv\lib\site-packages\playwright\_impl\_page.py", line 255, in _on_dialog
    self.emit(Page.Events.Dialog, dialog)
  File "c:\Users\leandro.souza.JEA\Dev\Projetos Em Desenvolvimento\scrapers\venv\lib\site-packages\pyee\_base.py", line 115, in emit
    handled = self._call_handlers(event, args, kwargs)
  File "c:\Users\leandro.souza.JEA\Dev\Projetos Em Desenvolvimento\scrapers\venv\lib\site-packages\pyee\_base.py", line 98, in _call_handlers
    self._emit_run(f, args, kwargs)
  File "c:\Users\leandro.souza.JEA\Dev\Projetos Em Desenvolvimento\scrapers\venv\lib\site-packages\pyee\_asyncio.py", line 43, in _emit_run
    self.emit("error", exc)
  File "c:\Users\leandro.souza.JEA\Dev\Projetos Em Desenvolvimento\scrapers\venv\lib\site-packages\pyee\_base.py", line 118, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "c:\Users\leandro.souza.JEA\Dev\Projetos Em Desenvolvimento\scrapers\venv\lib\site-packages\pyee\_base.py", line 88, in _emit_handle_potential_error
    raise error
  File "c:\Users\leandro.souza.JEA\Dev\Projetos Em Desenvolvimento\scrapers\venv\lib\site-packages\pyee\_asyncio.py", line 41, in _emit_run
    coro = f(*args, **kwargs)
  File "c:\Users\leandro.souza.JEA\Dev\Projetos Em Desenvolvimento\scrapers\venv\lib\site-packages\playwright\_impl\_impl_to_api_mapping.py", line 89, in wrapper_func
    return handler(
  File "c:\Users\leandro.souza.JEA\Dev\Projetos Em Desenvolvimento\scrapers\scrapers\playwright\handlers\user_creation.py", line 90, in __raise_error_for_duplicated_user
    raise UserPromoterAlreadyExistsError(cause=message)
scrapers.exceptions.user_creation.UserPromoterAlreadyExistsError: There is already an user with this id 1111111111_000000.
Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\leandro.souza.JEA\.vscode\extensions\ms-python.python-2021.11.1422169775\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\leandro.souza.JEA\.vscode\extensions\ms-python.python-2021.11.1422169775\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\leandro.souza.JEA\.vscode\extensions\ms-python.python-2021.11.1422169775\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Python39\lib\runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Python39\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\leandro.souza.JEA\Dev\Projetos Em Desenvolvimento\scrapers\testing.py", line 39, in <module>
    created_user: PanConsigDeliveredUser = user_creation_handler.maybe_create_user()
  File "c:\Users\leandro.souza.JEA\Dev\Projetos Em Desenvolvimento\scrapers\scrapers\playwright\handlers\user_creation.py", line 56, in maybe_create_user
    self._fill_form()
  File "c:\Users\leandro.souza.JEA\Dev\Projetos Em Desenvolvimento\scrapers\scrapers\playwright\handlers\user_creation.py", line 64, in _fill_form
    self.__fill_form_with_restricted_access()
  File "c:\Users\leandro.souza.JEA\Dev\Projetos Em Desenvolvimento\scrapers\scrapers\playwright\handlers\user_creation.py", line 125, in __fill_form_with_restricted_access
    select: ElementHandle = self.page.wait_for_selector(self.RESTRICTED_USER_SELECT_CSS)
  File "c:\Users\leandro.souza.JEA\Dev\Projetos Em Desenvolvimento\scrapers\venv\lib\site-packages\playwright\sync_api\_generated.py", line 6311, in wait_for_selector
    self._sync(
  File "c:\Users\leandro.souza.JEA\Dev\Projetos Em Desenvolvimento\scrapers\venv\lib\site-packages\playwright\_impl\_sync_base.py", line 111, in _sync
    return task.result()
  File "c:\Users\leandro.souza.JEA\Dev\Projetos Em Desenvolvimento\scrapers\venv\lib\site-packages\playwright\_impl\_page.py", line 347, in wait_for_selector
    return await self._main_frame.wait_for_selector(**locals_to_params(locals()))
  File "c:\Users\leandro.souza.JEA\Dev\Projetos Em Desenvolvimento\scrapers\venv\lib\site-packages\playwright\_impl\_frame.py", line 281, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "c:\Users\leandro.souza.JEA\Dev\Projetos Em Desenvolvimento\scrapers\venv\lib\site-packages\playwright\_impl\_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "c:\Users\leandro.souza.JEA\Dev\Projetos Em Desenvolvimento\scrapers\venv\lib\site-packages\playwright\_impl\_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "#ctl00_Cph_FIJN1_jnDadosLogin_UcDUsu_cmbUsuRestrito_CAMPO" to be visible
============================================================`

**Comment by Lucas-Bruschi** [comment]
I'm having the same problem here. 
What I think the issuer was trying to say is: if an exception is thrown inside a function called by the event listener, the exception is only logged and the program keeps running. 
Is there any way that an exception raised inside that function (called by the listener) be passed to the upper caller an then handled as intended?

**Comment by mayconfrr** [comment]
@mxschmitt you completely missed the point, when an exception is raised inside page.on('dialog'), it is printed in the console but you can't catch it, the code will then raise a Timeout Error because the element that caused the dialog to appear fails to become stable

**Comment by schinckel** [comment]
Yes, I agree that this is problematic. The only way to detect if an alert was generated is to do something like:

    dialog_detected = False

    def handle(dialog):
        nonlocal dialog_detected
        dialog.dismiss()
        dialog_detected = True

    page.on('dialog', handle)
    # ... action that results in an alert
    assert not dialog_detected

This is a lot of extra boilerplate over something like this (which could be defined once):

    def handle(dialog):
        dialog.dismiss()  # required to allow playwright to run error handling like screenshots
        raise Exception('dialog detected')

    page.on('dialog', handle)
    # ... action that results in an alert
