### ISSUE TITLE
[Bug]: KeyError: 'APIRequestContext' when creating a new context on a remote browser on 1.17.0

### ISSUE THREAD

**Issue by andrew-cartmill** [microsoft/playwright-python#1054]
### Playwright version

1.17.0

### Operating system

Linux

### What browsers are you seeing the problem on?

Chromium, Firefox

### Other information

Python 3.9

### What happened? / Describe the bug

We are using a dockerized test runner and dockerized browser images to run tests locally as well as in our CI environment. In the example provided, it seems that playwright is failing to create a new browser context due to a missing key value pair in the initializer. 

Apologies for the longer than normal code snippet with multiple files, but we only experience this with dockerized browsers. Commands and docker related files below assume all files are in the same directory. 

Commands to repro: 
`docker build -f Dockerfile -t tester --target tester . --no-cache`
`docker-compose --file demo-compose.yaml up --no-log-prefix`

### Code snippet to reproduce your bug

```shell
requirements.txt:

pytest==6.2.2
playwright

----------------------
Dockerfile:

FROM python:3.9-slim-buster as tester

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY requirements.txt ./requirements.txt
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /home
ENTRYPOINT /bin/bash

----------------------
demo-compose.yaml:

version: '3'

services:
  tester:
    image: tester:latest
    volumes:
      - .:/home
    entrypoint: python3 -B -m test

  chromium:
    image: playwright/chromium:latest

  firefox:
    image: playwright/firefox:latest

----------------------
test.py:

from playwright.sync_api import Playwright, sync_playwright


def run(playwright: Playwright) -> None:
    launch_options = {'ws_endpoint': f'ws://chromium:4444'}
    browser = playwright.chromium.connect(**launch_options)
    context = browser.new_context()

with sync_playwright() as playwright:
    run(playwright)
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/test.py", line 75, in <module>
    run(playwright)
  File "/home/test.py", line 62, in run
    context = browser.new_context()
  File "/opt/venv/lib/python3.9/site-packages/playwright/sync_api/_generated.py", line 10898, in new_context
    self._sync(
  File "/opt/venv/lib/python3.9/site-packages/playwright/_impl/_sync_base.py", line 111, in _sync
    return task.result()
  File "/opt/venv/lib/python3.9/site-packages/playwright/_impl/_browser.py", line 115, in new_context
    channel = await self._channel.send("newContext", params)
  File "/opt/venv/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/opt/venv/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
  File "/opt/venv/lib/python3.9/site-packages/playwright/_impl/_transport.py", line 216, in run
    self.on_message(obj)
  File "/opt/venv/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 154, in <lambda>
    self._transport.on_message = lambda msg: self.dispatch(msg)
  File "/opt/venv/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 256, in dispatch
    self._create_remote_object(
  File "/opt/venv/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 280, in _create_remote_object
    result = self._object_factory(parent, type, guid, initializer)
  File "/opt/venv/lib/python3.9/site-packages/playwright/_impl/_object_factory.py", line 57, in create_remote_object
    return BrowserContext(parent, type, guid, initializer)
  File "/opt/venv/lib/python3.9/site-packages/playwright/_impl/_browser_context.py", line 87, in __init__
    initializer["APIRequestContext"]
```

**Comment by mxschmitt** [comment]
Most likely this is because `playwright/chromium:latest` is not providing Playwright on the same version as you are trying to connect with your Python client.

I'm not familiar with `playwright/chromium` since its not official, so maybe try to contact them / ask for versioned Docker images or create your own image based on the official one: https://playwright.dev/docs/docker
