### ISSUE TITLE
Can't load video via expect_file_chooser

### ISSUE THREAD

**Issue by SHADR1N** [microsoft/playwright-python#1060]
### Playwright version

1.12.1

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### Other information

python 3.9.1

### What happened? / Describe the bug

I connect the browser via connect_over_cdp, everything works fine, but as soon as I try to download the video I get an error.

`**playwright._impl._api_types.Error: Browser closed.**`

Noticed that the images are loading.
It also worked very badly with "launch" and chromium
It worked with webkit.

### Code snippet to reproduce your bug

```shell
from playwright.sync_api import sync_playwright     
class Main():
    def __init___(self, url):
        self.url = url
        self.start()

    def start(self):       
            with sync_playwright() as p:
                browser = p.chromium.connect_over_cdp(endpoint_url = self.url)
                self.context = browser.contexts[0]
                self.page = self.context.pages[0]


        self.page.goto('https://viljamis.com/filetest/')
        self.page.wait_for_timeout(3000)

        with page.expect_file_chooser() as fc_info:
            hand = page.query_selector("input[type='file']")
            hand.click()

        file_chooser = fc_info.value
        file_chooser.set_files('video)
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Users\root\Desktop\YouTubeAuto\Upload.py", line 54, in __init__
    self.start()
  File "C:\Users\root\Desktop\YouTubeAuto\Upload.py", line 100, in start
    return self.upload()
  File "C:\Users\root\Desktop\YouTubeAuto\Upload.py", line 305, in upload
    file_chooser.set_files('C:\\Users\\root\\Desktop\\BAZA ISHODNIKOV\\Betting SNG\\Ishodniki video\\ТОПЫ\\20.mp4')
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\sync_api\_generated.py", line 2897, in set_files
    self._sync(
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\_impl\_sync_base.py", line 111, in _sync
    return task.result()
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\_impl\_file_chooser.py", line 58, in set_files
    await self._element_handle.set_input_files(files, timeout, noWaitAfter)
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\_impl\_element_handle.py", line 193, in set_input_files
    await self._channel.send("setInputFiles", params)
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\_impl\_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\_impl\_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Browser closed.
```

**Comment by mxschmitt** [comment]
Your script was not executable and has a bunch of syntax errors so I'm not able to repro it. How big is your file? You are then probably hitting this issue: https://github.com/microsoft/playwright/issues/3768

After adjusting, I used this script which works for me:

```py
from playwright.sync_api import sync_playwright


class Main:
    def __init__(self, url):
        self.url = url

    def start(self):
        playwright = sync_playwright().start()
        browser = playwright.chromium.connect_over_cdp(endpoint_url=self.url)
        self.context = browser.contexts[0]
        self.page = self.context.pages[0]

        self.page.goto("https://viljamis.com/filetest/")
        self.page.set_input_files(
            "input[type='file']", "test.py"
        )
        playwright.stop()


Main(
    "ws://127.0.0.1:1234/devtools/browser/9b581de3-f408-4fe6-bfe2-67c34159d0a1"
).start()

```

**Comment by SHADR1N** [comment]
Yes, the code was cut, so there could be errors.

By the way, the file is really big, it's a 10 minute video.

**Comment by mxschmitt** [comment]
If the file is bigger than 50MB you will hit this issue and we can fold it into it: https://github.com/microsoft/playwright/issues/3768

**Comment by mxschmitt** [comment]
Closing and folding into https://github.com/microsoft/playwright/issues/3768
