### ISSUE TITLE
[Question]: running playwright-python in docker container 

### ISSUE THREAD

**Issue by huzaifanasir** [microsoft/playwright-python#1066]
### Your question

Hello,

I am struggling to run playwright in a Docker container. In my Dockerfile, I have the following snippet:
```
RUN pip install -r /application/requirements.txt
RUN playwright install
RUN playwright install-deps
```

The relevant output when I `docker build` is: 
```
Step 5/6 : RUN playwright install
 ---> Running in c03572e56456
Playwright build of chromium v939194 downloaded to /application/.cache/ms-playwright/chromium-939194
Playwright build of ffmpeg v1006 downloaded to /application/.cache/ms-playwright/ffmpeg-1006
Playwright build of firefox v1304 downloaded to /application/.cache/ms-playwright/firefox-1304
Playwright build of webkit v1578 downloaded to /application/.cache/ms-playwright/webkit-1578
Removing intermediate container c03572e56456
 ---> 297bd0e67358
Step 6/6 : RUN playwright install-deps
 ---> Running in 8ad21395a1f9
Installing Ubuntu dependencies...
sh: apt-get: command not found
Removing intermediate container 8ad21395a1f9
 ---> 3a52a187c5ac
Successfully built 3a52a187c5ac
```

When I then run `python playwright_example.py` from within the container, however, I get an error complaining about missing dependencies. The output of `playwright install` indicates the relevant browsers (chromium, in my case)  have been successfully installed, though the output of `playwright install-deps` indicates an error, despite which the container was successfully built. 

Relevant stacktrace from `python playwright_example.py`:
```
(app-root) bash-4.4$ python playwright_example.py
Traceback (most recent call last):
  File "playwright_example.py", line 19, in <module>
    main()
  File "playwright_example.py", line 15, in main
    loop.run_until_complete(myfn())
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "playwright_example.py", line 7, in myfn
    browser = await p.chromium.launch()
  File "/opt/app-root/lib64/python3.8/site-packages/playwright/async_api/_generated.py", line 11602, in launch
    await self._async(
  File "/opt/app-root/lib64/python3.8/site-packages/playwright/_impl/_browser_type.py", line 88, in launch
    return from_channel(await self._channel.send("launch", params))
  File "/opt/app-root/lib64/python3.8/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/opt/app-root/lib64/python3.8/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error:
```

My docker os is redhat 8.4 fwiw

**Comment by mxschmitt** [comment]
Playwright does officially only support Ubuntu 18 and 20 see [here](https://playwright.dev/docs/library#system-requirements). For other Linux distributions, we don't provide support, since the dependencies which you require to run the browsers, are highly coupled to the OS and its version.
