### ISSUE TITLE
[Question]: On using multithreading I am getting Timeout exception while launching the browser (occasionally), what can be causes for it?

### ISSUE THREAD

**Issue by sla-te** [microsoft/playwright-python#1082]
### Your question

```
Timeout 30000ms exceeded.
=========================== logs ===========================
<launching> C:\Users\Administrator\AppData\Local\ms-playwright\firefox-1304\firefox\firefox.exe -no-remote -wait-for-browser -foreground -profile C:\Users\ADMINI~1\AppData\Local\Temp\playwright_firefoxdev_profile-w3mp1i -juggler-pipe -silent
<launched> pid=71092
============================================================

Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\pwg\venv\lib\site-packages\playwright_base\base.py", line 106, in boot
    self.browser = self.tls.playwright.firefox.launch(
  File "C:\Users\Administrator\PycharmProjects\pwg\venv\lib\site-packages\playwright\sync_api\_generated.py", line 11345, in launch
    self._sync(
  File "C:\Users\Administrator\PycharmProjects\pwg\venv\lib\site-packages\playwright\_impl\_sync_base.py", line 111, in _sync
    return task.result()
  File "C:\Users\Administrator\PycharmProjects\pwg\venv\lib\site-packages\playwright\_impl\_browser_type.py", line 88, in launch
    return from_channel(await self._channel.send("launch", params))
  File "C:\Users\Administrator\PycharmProjects\pwg\venv\lib\site-packages\playwright\_impl\_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "C:\Users\Administrator\PycharmProjects\pwg\venv\lib\site-packages\playwright\_impl\_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
<launching> C:\Users\Administrator\AppData\Local\ms-playwright\firefox-1304\firefox\firefox.exe -no-remote -wait-for-browser -foreground -profile C:\Users\ADMINI~1\AppData\Local\Temp\playwright_firefoxdev_profile-w3mp1i -juggler-pipe -silent
<launched> pid=71092
============================================================
```

And I am kind of suspecting that for some reason this one is related to the problem I am facing:

```
Exception in callback SyncBase._sync.<locals>.callback(<Task finishe...ethod='GET'>>>) at C:\Users\Administrator\PycharmProjects\pwg\venv\lib\site-packages\playwright\_impl\_sync_base.py:104
handle: <Handle SyncBase._sync.<locals>.callback(<Task finishe...ethod='GET'>>>) at C:\Users\Administrator\PycharmProjects\pwg\venv\lib\site-packages\playwright\_impl\_sync_base.py:104>
Traceback (most recent call last):
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.10.0\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\PycharmProjects\pwg\venv\lib\site-packages\playwright\_impl\_sync_base.py", line 105, in callback
    g_self.switch()
  File "C:\Users\Administrator\PycharmProjects\pwg\venv\lib\site-packages\playwright\_impl\_browser_context.py", line 138, in <lambda>
    lambda params: self._on_request_finished(
  File "C:\Users\Administrator\PycharmProjects\pwg\venv\lib\site-packages\playwright\_impl\_browser_context.py", line 382, in _on_request_finished
    page.emit(Page.Events.RequestFinished, request)
  File "C:\Users\Administrator\PycharmProjects\pwg\venv\lib\site-packages\pyee\_base.py", line 115, in emit
    handled = self._call_handlers(event, args, kwargs)
  File "C:\Users\Administrator\PycharmProjects\pwg\venv\lib\site-packages\pyee\_base.py", line 98, in _call_handlers
    self._emit_run(f, args, kwargs)
  File "C:\Users\Administrator\PycharmProjects\pwg\venv\lib\site-packages\pyee\_asyncio.py", line 43, in _emit_run
    self.emit("error", exc)
  File "C:\Users\Administrator\PycharmProjects\pwg\venv\lib\site-packages\pyee\_base.py", line 118, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "C:\Users\Administrator\PycharmProjects\pwg\venv\lib\site-packages\pyee\_base.py", line 88, in _emit_handle_potential_error
    raise error
  File "C:\Users\Administrator\PycharmProjects\pwg\venv\lib\site-packages\pyee\_asyncio.py", line 41, in _emit_run
    coro = f(*args, **kwargs)
  File "C:\Users\Administrator\PycharmProjects\pwg\venv\lib\site-packages\playwright\_impl\_wait_helper.py", line 121, in listener
    self._fulfill(event_data)
  File "C:\Users\Administrator\PycharmProjects\pwg\venv\lib\site-packages\playwright\_impl\_wait_helper.py", line 99, in _fulfill
    self._cleanup()
  File "C:\Users\Administrator\PycharmProjects\pwg\venv\lib\site-packages\playwright\_impl\_wait_helper.py", line 96, in _cleanup
    listener[0].remove_listener(listener[1], listener[2])
  File "C:\Users\Administrator\PycharmProjects\pwg\venv\lib\site-packages\playwright\_impl\_page.py", line 276, in remove_listener
    super().remove_listener(event, f)
  File "C:\Users\Administrator\PycharmProjects\pwg\venv\lib\site-packages\pyee\_base.py", line 155, in remove_listener
    self._remove_listener(event, f)
  File "C:\Users\Administrator\PycharmProjects\pwg\venv\lib\site-packages\pyee\_base.py", line 150, in _remove_listener
    self._events[event].pop(f)
KeyError: <function WaitHelper.reject_on_event.<locals>.listener at 0x000001C65BD1AF80>
```

The result of all of it are (a lot of) dead threads slowing down the overall process significantly

**Comment by sla-te** [comment]
I found the problem for this one. Using `with page.with_expect_request_finished()` combined with a route on the same target or calling into a function that uses `with page.with_expect_request_finished()` from inside a `with page.with_expect_request_finished()` does not work (and does not drop any exception to identify whats going on).

**Comment by mxschmitt** [comment]
Can you provide us a full repro which we can run locally?

**Comment by mxschmitt** [comment]
Closing since we can't act on this without having a repro. Please create a new issue if you have one.
