### ISSUE TITLE
[BUG]The latest version of add_cookies sets the cookie error

### ISSUE THREAD

**Issue by korykim** [microsoft/playwright-python#1096]
**Context:**
- Playwright Version: 1.17.2
- Operating System: Windows10
- Python version:3.9
- Browser: Chromium
- Extra: 

**Code**

- export.json is my cookies file

```
[
  {
    "domain": ".abcxxx.com",
    "expirationDate": 4791400988.232584,
    "hostOnly": false,
    "httpOnly": false,
    "name": "x-zp-client-id",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "f625d6cc-2eba-4931-8442-5286c36ca786",
    "id": 1
  },
  {
    "domain": ".abcxxx.com",
    "expirationDate": 4791400988.232584,
    "hostOnly": false,
    "httpOnly": false,
    "name": "x-zp-client-id2",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "f625d6cc-2eba-4931-8442-5286c36ca786",
    "id": 2
  },
]
```

- python code
```

import json

from playwright.sync_api import Playwright, sync_playwright


def on_response(response):
    if '/search/positions' in response.url and response.status == 200:
        print(response.json())

def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False, slow_mo=50)
    context = browser.new_context(user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36')
    page = context.new_page()
    page.on('response', on_response)

    context.clear_cookies()

    cookie_file = open('./export.json')
    cookies = json.load(cookie_file)


    page.goto('https://www.abcxxx.com')


    context.add_cookies(cookies)

    page.goto('https://www.abcxxx.com/search')

    try:
        page.wait_for_load_state('networkidle')
        page.click("text=next")
        page.close()

    except Exception as e:
        print("Error in playwright script.")
        page.close()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)

```
- Error
```
Traceback (most recent call last):
  File "I:/pycode/z/script.py", line 65, in <module>
    run(playwright)
  File "I:/pycode/z/script.py", line 40, in run
    context.add_cookies(cookies)
  File "I:\anaconda3\envs\py3.9\lib\site-packages\playwright\sync_api\_generated.py", line 10062, in add_cookies
    self._sync(
  File "I:\anaconda3\envs\py3.9\lib\site-packages\playwright\_impl\_sync_base.py", line 111, in _sync
    return task.result()
  File "I:\anaconda3\envs\py3.9\lib\site-packages\playwright\_impl\_browser_context.py", line 206, in add_cookies
    await self._channel.send("addCookies", dict(cookies=cookies))
  File "I:\anaconda3\envs\py3.9\lib\site-packages\playwright\_impl\_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "I:\anaconda3\envs\py3.9\lib\site-packages\playwright\_impl\_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: cookies[0].sameSite: expected one of (Strict|Lax|None)
```

**Comment by mxschmitt** [comment]
How did you generate your `export.json` file? 

`unspecified` is not a valid value, it needs to be one of (Strict|Lax|None).

**Comment by mxschmitt** [comment]
Closing since its stale.

**Comment by korykim** [comment]
> How did you generate your `export.json` file?
> 
> `unspecified` is not a valid value, it needs to be one of (Strict|Lax|None).

Thanks, Bro.
I have solved the problem.
Here is the workaround.

1. open `export.json` file, replace `unspecified` to `None`
2. add cookies

```
page.goto('https://www.abcxxx.com')

cookie_file = open('./export.json')
cookies = json.load(cookie_file)

for cookie in cookies:
    context.add_cookies(cookie)

page.goto('https://www.abcxxx.com/home')
```
3. Done!
