### ISSUE TITLE
[BUG]Exceptions are sometimes reported when the browser is not closed

### ISSUE THREAD

**Issue by liuyazhou1991** [microsoft/playwright-python#1152]

**Comment by aca** [comment]
Same here,
```
λ python3 run.py
Loop <_UnixSelectorEventLoop running=False closed=True debug=False> that handles pid 618225 is closed
<Response [200]>
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x7feccf255750>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/base_subprocess.py", line 126, in __del__
  File "/usr/lib/python3.10/asyncio/base_subprocess.py", line 104, in close
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 546, in close
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 570, in _close
  File "/usr/lib/python3.10/asyncio/base_events.py", line 745, in call_soon
  File "/usr/lib/python3.10/asyncio/base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed

λ cat run.py
from playwright.sync_api import sync_playwright

def get_cookies(playwright):
    browser = playwright.chromium.connect_over_cdp("http://127.0.0.1:9222/")
    context = browser.contexts[0]
    cookies = context.cookies("https://google.com")
    return {cookie["name"]: cookie["value"] for cookie in cookies}

cookies =  {}
with sync_playwright() as playwright:
    cookies = get_cookies(playwright)

import requests
print(requests.get("https://google.com", cookies=cookies))
```
