### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by wanghaisheng** [microsoft/playwright-python#1196]
**Context:**
- Playwright Version: latest
- Operating System: windows
- Python version:3.8
- Browser: firefox
- Extra: [any specific details about your environment]

**Code Snippet**
i use a socks5 proxy which selenium works but 
```
            print('start web page with proxy')

            browserLaunchOptionDict = {
                "headless": False,
                "proxy": {
                    "server": PROXY_SOCKS5,
                },
                "executable_path": executable_path,
                "timeout": timeout
            }

            if not root_profile_directory:
                self.browser = self._start_browser("firefox", **browserLaunchOptionDict)
            else:
                self.browser = self._start_persistent_browser(
                    "firefox", user_data_dir=root_profile_directory, **browserLaunchOptionDict
                )



    def _start_persistent_browser(
        self, browser: str, user_data_dir: Optional[Union[str, Path]], **kwargs
    ):
        if browser == "chromium":
            return self._playwright.chromium.launch_persistent_context(
                user_data_dir, **kwargs
            )
        if browser == "firefox":
            return self._playwright.firefox.launch_persistent_context(
                user_data_dir, **kwargs
            )
        if browser == "webkit":
            return self._playwright.webkit.launch_persistent_context(
                user_data_dir, **kwargs
            )

        raise RuntimeError(
            "You have to select either 'chromium', 'firefox' or 'webkit' as browser."
        )


```

**Describe the bug**
```
start web page with proxy
Traceback (most recent call last):
  File "example.py", line 12, in <module>
    upload = Upload(
  File "D:\Download\audio-visual\make-reddit-video\ytb-up\ytb_up\upload.py", line 76, in __init__
    self.browser = self._start_persistent_browser(
  File "D:\Download\audio-visual\make-reddit-video\ytb-up\ytb_up\upload.py", line 829, in _start_persistent_browser
    return self._playwright.firefox.launch_persistent_context(
  File "D:\Program Files\anaconda3\lib\site-packages\playwright\sync_api\_generated.py", line 11634, in launch_persistent_context
    self._sync(
  File "D:\Program Files\anaconda3\lib\site-packages\playwright\_impl\_sync_base.py", line 111, in _sync
    return task.result()
  File "D:\Program Files\anaconda3\lib\site-packages\playwright\_impl\_browser_type.py", line 148, in launch_persistent_context
    from_channel(await self._channel.send("launchPersistentContext", params)),
  File "D:\Program Files\anaconda3\lib\site-packages\playwright\_impl\_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "D:\Program Files\anaconda3\lib\site-packages\playwright\_impl\_connection.py", line    return task.result()
  File "D:\Program Files\anaconda3\lib\site-packages\playwright\_impl\_browser_type.py", line 148, in launch_persistent_context
    from_channel(await self._channel.send("launchPersistentContext", params)),
  File "D:\Program Files\anaconda3\lib\site-packages\playwright\_impl\_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "D:\Program Files\anaconda3\lib\site-packages\playwright\_impl\_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 3ms exceeded.
```

Add any other details about the problem here.

**Comment by wanghaisheng** [comment]
sameSite: 'no_restriction' or sameSite: null - the default behavior, equivalent to no SameSite attribute in Set-Cookie
    sameSite: 'strict' - equivalent to SameSite=Strict in Set-Cookie, the cookie will only be sent in same-site contexts
    sameSite: 'lax' - equivalent to SameSite=Lax in Set-Cookie, the cookie will be sent in same-site contexts and in top-level navigations

should we add no_restriction it seems ==None option
