### ISSUE TITLE
[Question]:  can we connect to nodejs server throug  websocket

### ISSUE THREAD

**Issue by wanghaisheng** [microsoft/playwright-python#1218]
### Your question

```
$ npx playwright run-server 8080
Listening on ws://127.0.0.1:8080/ws
```

from playwright.sync_api import sync_playwright,Mouse

with sync_playwright() as p:
    browser = p.chromium.connect(
        "ws://127.0.0.1:8080/ws"
    )
    page = browser.newPage()
    page.goto("http://baidu.com/")
    page.screenshot(path=f"example.png")
    browser.close()

```
Traceback (most recent call last):
  File "t.py", line 4, in <module>
    browser = p.chromium.connect(
  File "D:\Program Files\anaconda3\lib\site-packages\playwright\sync_api\_generated.py", line 11763, in connect
    self._sync(
  File "D:\Program Files\anaconda3\lib\site-packages\playwright\_impl\_sync_base.py", line 111, in _sync
    return task.result()
  File "D:\Program Files\anaconda3\lib\site-packages\playwright\_impl\_browser_type.py", line 211, in connect
    assert pre_launched_browser
AssertionError
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002B66F055280>
Traceback (most recent call last):
  File "D:\Program Files\anaconda3\lib\asyncio\proactor_events.py", line 116, in __del__
  File "D:\Program Files\anaconda3\lib\asyncio\proactor_events.py", line 108, in close
  File "D:\Program Files\anaconda3\lib\asyncio\base_events.py", line 719, in call_soon
  File "D:\Program Files\anaconda3\lib\asyncio\base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed
Task was destroyed but it is pending!
task: <Task pending name='Task-8' coro=<WebSocketCommonProtocol.transfer_data() running at D:\Program Files\anaconda3\lib\site-packages\websockets\legacy\protocol.py:944> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000002B66FD9DB20>()]> cb=[<TaskWakeupMethWrapper object at 0x000002B66FD9D400>(), _wait.<locals>._on_completion() at D:\Program Files\anaconda3\lib\asyncio\tasks.py:507]>
Task was destroyed but it is pending!
task: <Task pending name='Task-9' coro=<WebSocketCommonProtocol.keepalive_ping() running at D:\Program Files\anaconda3\lib\site-packages\websockets\legacy\protocol.py:1233> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000002B66D5CC2E0>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-10' coro=<WebSocketCommonProtocol.close_connection() running at D:\Program Files\anaconda3\lib\site-packages\websockets\legacy\protocol.py:1288> wait_for=<Task pending name='Task-8' coro=<WebSocketCommonProtocol.transfer_data() running at D:\Program Files\anaconda3\lib\site-packages\websockets\legacy\protocol.py:944> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000002B66FD9DB20>()]> cb=[<TaskWakeupMethWrapper object at 0x000002B66FD9D400>(), _wait.<locals>._on_completion() at D:\Program Files\anaconda3\lib\asyncio\tasks.py:507]>>
Exception ignored in: <coroutine object WebSocketCommonProtocol.close_connection at 0x000002B66FD0BC40>
Traceback (most recent call last):
  File "D:\Program Files\anaconda3\lib\site-packages\websockets\legacy\protocol.py", line 1321, in close_connection
  File "D:\Program Files\anaconda3\lib\site-packages\websockets\legacy\protocol.py", line 1339, in close_transport
  File "D:\Program Files\anaconda3\lib\site-packages\websockets\legacy\protocol.py", line 1364, in wait_for_connection_lost
  File "D:\Program Files\anaconda3\lib\asyncio\tasks.py", line 448, in wait_for       
RuntimeError: no running event loop
Task was destroyed but it is pending!
task: <Task pending name='Task-5' coro=<Connection.run() running at D:\Program Files\anaconda3\lib\site-packages\playwright\_impl\_connection.py:183> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000002B66FD9DB50>()]>>
(base)
```

**Comment by mxschmitt** [comment]
Instead of using `run-server` you need to use `launch-server`, keep in mind that this is not an officially supported CLI command.

We instead recommending launching your own server see [here](https://playwright.dev/docs/api/class-browsertype#browser-type-launch-server).

**Comment by wanghaisheng** [comment]
what embarrassed for me is  i could not managed to make playwright in python to launch at all ,let alone launch a server,whether in heroku or azure function app. and you will find  i leave quite a lot issue across playwright repo
it seems many one use node js  can work to this,so came to me i can use python as a client to get result from nodejs playwright server result to deal with.  if i know more about nodejs  i definitely abandon python playwright to do the post-processing
@mxschmitt

**Comment by mxschmitt** [comment]
See https://github.com/microsoft/playwright-python/issues/1215#issuecomment-1073766201 for reference. Travis CI also has nothing to do with the actual deployment. 

For CI, see the official CI guide: https://playwright.dev/python/docs/ci
