### ISSUE TITLE
'Error occured in event listener' and 'asyncio.exceptions.InvalidStateError: invalid state'

### ISSUE THREAD

**Issue by AIGeneratedUsername** [microsoft/playwright-python#1242]
**Context:**
- Playwright Version: 1.20.1
- Operating System: Lubuntu 20.04
- Python version: 3.10
- Browser: Firefox

**Code Snippet**
```python
class Client:

    def __init__(self, initial_url: str, browser: Browser):
        self.browser = browser
        self.url = initial_url

    async def __aenter__(self):
        self.context = await self.browser.new_context()  # Create a new incognito browser context.
        self.page = await self.context.new_page()
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        await self.context.close()

      async def start(self) -> None:
          self.page.goto(self.url)



async def _access_website(url: str, browser: Browser) -> None:
        async with Client(url, browser) as client:
            await client.start()


async with async_playwright() as p:
        browser = await p.firefox.launch(headless=True)
        scheduler = await aiojobs.create_scheduler(limit=20)
        try:
            jobs = [await scheduler.spawn(_access_website(url, browser)) for url in urls]
        finally:
            await scheduler.close()
            await browser.close()
```

**Describe the bug**

```
/home/sam/.cache/pypoetry/virtualenvs/client-lQZKJVih-py3.10/bin/python /home/sam/Projects/client/src/browse_website.py
Error occured in event listener
Traceback (most recent call last):
  File "/home/sam/.cache/pypoetry/virtualenvs/client-lQZKJVih-py3.10/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 272, in dispatch
    object._channel.emit(method, self._replace_guids_with_channels(params))
  File "/home/sam/.cache/pypoetry/virtualenvs/client-lQZKJVih-py3.10/lib/python3.10/site-packages/pyee/_base.py", line 113, in emit
    handled = self._call_handlers(event, args, kwargs)
  File "/home/sam/.cache/pypoetry/virtualenvs/client-lQZKJVih-py3.10/lib/python3.10/site-packages/pyee/_base.py", line 96, in _call_handlers
    self._emit_run(f, args, kwargs)
  File "/home/sam/.cache/pypoetry/virtualenvs/client-lQZKJVih-py3.10/lib/python3.10/site-packages/pyee/_asyncio.py", line 42, in _emit_run
    self.emit('error', exc)
  File "/home/sam/.cache/pypoetry/virtualenvs/client-lQZKJVih-py3.10/lib/python3.10/site-packages/pyee/_base.py", line 116, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/home/sam/.cache/pypoetry/virtualenvs/client-lQZKJVih-py3.10/lib/python3.10/site-packages/pyee/_base.py", line 86, in _emit_handle_potential_error
    raise error
  File "/home/sam/.cache/pypoetry/virtualenvs/client-lQZKJVih-py3.10/lib/python3.10/site-packages/pyee/_asyncio.py", line 40, in _emit_run
    coro = f(*args, **kwargs)
  File "/home/sam/.cache/pypoetry/virtualenvs/client-lQZKJVih-py3.10/lib/python3.10/site-packages/playwright/_impl/_page.py", line 158, in <lambda>
    self._channel.on("close", lambda _: self._on_close())
  File "/home/sam/.cache/pypoetry/virtualenvs/client-lQZKJVih-py3.10/lib/python3.10/site-packages/playwright/_impl/_page.py", line 262, in _on_close
    self.emit(Page.Events.Close, self)
  File "/home/sam/.cache/pypoetry/virtualenvs/client-lQZKJVih-py3.10/lib/python3.10/site-packages/pyee/_base.py", line 113, in emit
    handled = self._call_handlers(event, args, kwargs)
  File "/home/sam/.cache/pypoetry/virtualenvs/client-lQZKJVih-py3.10/lib/python3.10/site-packages/pyee/_base.py", line 96, in _call_handlers
    self._emit_run(f, args, kwargs)
  File "/home/sam/.cache/pypoetry/virtualenvs/client-lQZKJVih-py3.10/lib/python3.10/site-packages/pyee/_asyncio.py", line 42, in _emit_run
    self.emit('error', exc)
  File "/home/sam/.cache/pypoetry/virtualenvs/client-lQZKJVih-py3.10/lib/python3.10/site-packages/pyee/_base.py", line 116, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/home/sam/.cache/pypoetry/virtualenvs/client-lQZKJVih-py3.10/lib/python3.10/site-packages/pyee/_base.py", line 86, in _emit_handle_potential_error
    raise error
  File "/home/sam/.cache/pypoetry/virtualenvs/client-lQZKJVih-py3.10/lib/python3.10/site-packages/pyee/_asyncio.py", line 40, in _emit_run
    coro = f(*args, **kwargs)
  File "/home/sam/.cache/pypoetry/virtualenvs/client-lQZKJVih-py3.10/lib/python3.10/site-packages/playwright/_impl/_page.py", line 213, in <lambda>
    Page.Events.Close, lambda _: self._closed_or_crashed_future.set_result(True)
asyncio.exceptions.InvalidStateError: invalid state
```

I do not understand how to debug this because the traceback does not point to my code.

**Comment by AIGeneratedUsername** [comment]
One more error:
```
Error occured in event listener
Traceback (most recent call last):
  File "/home/bob/.cache/pypoetry/virtualenvs/client-lQZKJVih-py3.10/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 272, in dispatch
    object._channel.emit(method, self._replace_guids_with_channels(params))
  File "/home/bob/.cache/pypoetry/virtualenvs/client-lQZKJVih-py3.10/lib/python3.10/site-packages/pyee/_base.py", line 113, in emit
    handled = self._call_handlers(event, args, kwargs)
  File "/home/bob/.cache/pypoetry/virtualenvs/client-lQZKJVih-py3.10/lib/python3.10/site-packages/pyee/_base.py", line 96, in _call_handlers
    self._emit_run(f, args, kwargs)
  File "/home/bob/.cache/pypoetry/virtualenvs/client-lQZKJVih-py3.10/lib/python3.10/site-packages/pyee/_asyncio.py", line 42, in _emit_run
    self.emit('error', exc)
  File "/home/bob/.cache/pypoetry/virtualenvs/client-lQZKJVih-py3.10/lib/python3.10/site-packages/pyee/_base.py", line 116, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/home/bob/.cache/pypoetry/virtualenvs/client-lQZKJVih-py3.10/lib/python3.10/site-packages/pyee/_base.py", line 86, in _emit_handle_potential_error
    raise error
  File "/home/bob/.cache/pypoetry/virtualenvs/client-lQZKJVih-py3.10/lib/python3.10/site-packages/pyee/_asyncio.py", line 40, in _emit_run
    coro = f(*args, **kwargs)
  File "/home/bob/.cache/pypoetry/virtualenvs/client-lQZKJVih-py3.10/lib/python3.10/site-packages/playwright/_impl/_page.py", line 186, in <lambda>
    lambda params: self._on_frame_detached(from_channel(params["frame"])),
  File "/home/bob/.cache/pypoetry/virtualenvs/client-lQZKJVih-py3.10/lib/python3.10/site-packages/playwright/_impl/_page.py", line 228, in _on_frame_detached
    self._frames.remove(frame)
ValueError: list.remove(x): x not in list
Error occured in event listener
Traceback (most recent call last):
  File "/home/bob/.cache/pypoetry/virtualenvs/client-lQZKJVih-py3.10/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 272, in dispatch
    object._channel.emit(method, self._replace_guids_with_channels(params))
  File "/home/bob/.cache/pypoetry/virtualenvs/client-lQZKJVih-py3.10/lib/python3.10/site-packages/pyee/_base.py", line 113, in emit
    handled = self._call_handlers(event, args, kwargs)
  File "/home/bob/.cache/pypoetry/virtualenvs/client-lQZKJVih-py3.10/lib/python3.10/site-packages/pyee/_base.py", line 96, in _call_handlers
    self._emit_run(f, args, kwargs)
  File "/home/bob/.cache/pypoetry/virtualenvs/client-lQZKJVih-py3.10/lib/python3.10/site-packages/pyee/_asyncio.py", line 42, in _emit_run
    self.emit('error', exc)
  File "/home/bob/.cache/pypoetry/virtualenvs/client-lQZKJVih-py3.10/lib/python3.10/site-packages/pyee/_base.py", line 116, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/home/bob/.cache/pypoetry/virtualenvs/client-lQZKJVih-py3.10/lib/python3.10/site-packages/pyee/_base.py", line 86, in _emit_handle_potential_error
    raise error
  File "/home/bob/.cache/pypoetry/virtualenvs/client-lQZKJVih-py3.10/lib/python3.10/site-packages/pyee/_asyncio.py", line 40, in _emit_run
    coro = f(*args, **kwargs)
  File "/home/bob/.cache/pypoetry/virtualenvs/client-lQZKJVih-py3.10/lib/python3.10/site-packages/playwright/_impl/_page.py", line 186, in <lambda>
    lambda params: self._on_frame_detached(from_channel(params["frame"])),
  File "/home/bob/.cache/pypoetry/virtualenvs/client-lQZKJVih-py3.10/lib/python3.10/site-packages/playwright/_impl/_page.py", line 228, in _on_frame_detached
    self._frames.remove(frame)
ValueError: list.remove(x): x not in list
```

**Comment by AIGeneratedUsername** [comment]
My current workaround to hide the problem:

```python
    async def __aenter__(self):
        self.page.on("crash", self._open_new_page)
        self.page.on("close", self._open_new_page)
        self.context.on("close", self._open_new_context)

    async def _open_new_page(self) -> None:
        while self.context is None:
            logger.warning("Waiting for browser context...")
            await asyncio.sleep(1)
            continue
        async with lock:
            self.page = await self.context.new_page()

    async def _open_new_context(self) -> None:
        self.context = None
        async with lock:
            self.context = await self.browser.new_context()
        await self._open_new_page()
```

Also, I have to catch `ValueError: list.remove(x): x not in list` everywhere and re-open a crashed page.

**Comment by AIGeneratedUsername** [comment]
@mxschmitt Thank you for the quick feedback, but on the "main" branch, a Firefox tab crashes:
```python
import asyncio
from playwright.async_api import async_playwright


async def main():
    async with async_playwright() as p:
        browser = await p.firefox.launch(headless=False)
        page = await browser.new_page()
        await page.goto("https://www.asna.ru/")
        await page.wait_for_timeout(5_000)
        print(await page.title())
        await browser.close()

asyncio.run(main())
```
Error traceback:
```
Traceback (most recent call last):
  File "/home/OnelKaliProjects/tester/_local.py", line 14, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/OnelKaliProjects/tester/_local.py", line 11, in main
    print(await page.title())
  File "/home/OnelKali.cache/pypoetry/virtualenvs/tester-NboAmZt6-py3.10/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 8191, in title
    await self._async("page.title", self._impl_obj.title())
  File "/home/OnelKali.cache/pypoetry/virtualenvs/tester-NboAmZt6-py3.10/lib/python3.10/site-packages/playwright/_impl/_page.py", line 641, in title
    return await self._main_frame.title()
  File "/home/OnelKali.cache/pypoetry/virtualenvs/tester-NboAmZt6-py3.10/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 665, in title
    return await self._channel.send("title")
  File "/home/OnelKali.cache/pypoetry/virtualenvs/tester-NboAmZt6-py3.10/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/home/OnelKali.cache/pypoetry/virtualenvs/tester-NboAmZt6-py3.10/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target crashed

Process finished with exit code 1
```
Can you confirm that this will be fixed later on the 'main' branch or I need to create a new issue?

**Comment by mxschmitt** [comment]
This is expected, since Firefox is crashing on your site. Could you file a saperate issue for that? Then we're happy to take a look at it. Thanks!
