### ISSUE TITLE
[BUG]ValueError: I/O operation on closed pipe

### ISSUE THREAD

**Issue by wanghaisheng** [microsoft/playwright-python#1254]
**Context:**
- Playwright Version: [1.20.1]
- Operating System: [both Windows, Linux tried]
- Python version: [3.8.5,3.7]
- Browser: [firefox]
- Extra: [any specific details about your environment]

**Code Snippet**
to reproduce 
https://github.com/wanghaisheng/scraper-on-github-action/blob/main/upwork.py

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally.

**Describe the bug**

```
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x00000272824F4670>
Traceback (most recent call last):
  File "D:\Program Files\anaconda3\lib\asyncio\base_subprocess.py", line 125, in __del__  
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
  File "D:\Program Files\anaconda3\lib\asyncio\base_subprocess.py", line 70, in __repr__  
    info.append(f'stdin={stdin.pipe}')
  File "D:\Program Files\anaconda3\lib\asyncio\proactor_events.py", line 79, in __repr__  
    info.append(f'fd={self._sock.fileno()}')
  File "D:\Program Files\anaconda3\lib\asyncio\windows_utils.py", line 102, in fileno     
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000272824FBD30> 
Traceback (most recent call last):
  File "D:\Program Files\anaconda3\lib\asyncio\proactor_events.py", line 115, in __del__  
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
  File "D:\Program Files\anaconda3\lib\asyncio\proactor_events.py", line 79, in __repr__  
    info.append(f'fd={self._sock.fileno()}')
  File "D:\Program Files\anaconda3\lib\asyncio\windows_utils.py", line 102, in fileno     
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000272824FBD30> 
Traceback (most recent call last):
  File "D:\Program Files\anaconda3\lib\asyncio\proactor_events.py", line 115, in __del__  
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
  File "D:\Program Files\anaconda3\lib\asyncio\proactor_events.py", line 79, in __repr__  
    info.append(f'fd={self._sock.fileno()}')
  File "D:\Program Files\anaconda3\lib\asyncio\windows_utils.py", line 102, in fileno     
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
```

**Comment by mxschmitt** [comment]
Your repro is very big and does not have any Playwright in it. Is there a chance to make your repro a bit smaller?

Unrelated to your repro but related to your logs I'm pretty sure we we'll address the fix with the following PR: https://github.com/microsoft/playwright-python/pull/1213

**Comment by wanghaisheng** [comment]
@mxschmitt  I just remove other dep in this stanlone py   you can just download this py to have a try
