### ISSUE TITLE
[Question]: when i run threads with python threading module i get this error the middle of of doing autoamtion

### ISSUE THREAD

**Issue by mmani648** [microsoft/playwright-python#1257]
### Your question

Error: EPIPE: broken pipe, write
    at Socket._write (node:internal/net:55:25)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at PipeTransport.send (C:\Users\Nc\AppData\Local\Programs\Python\Python310\Lib\site-packages\playwright\driver\package\lib\protocol\transport.js:54:21)
    at DispatcherConnection.dispatcherConnection.onmessage (C:\Users\Nc\AppData\Local\Programs\Python\Python310\Lib\site-packages\playwright\driver\package\lib\cli\driver.js:67:57)
    at DispatcherConnection.sendMessageToClient (C:\Users\Nc\AppData\Local\Programs\Python\Python310\Lib\site-packages\playwright\driver\package\lib\dispatchers\dispatcher.js:187:10)
    at BrowserContextDispatcher._dispatchEvent (C:\Users\Nc\AppData\Local\Programs\Python\Python310\Lib\site-packages\playwright\driver\package\lib\dispatchers\dispatcher.js:108:22)
    at FFBrowserContext.<anonymous> (C:\Users\Nc\AppData\Local\Programs\Python\Python310\Lib\site-packages\playwright\driver\package\lib\dispatchers\browserContextDispatcher.js:102:19)
    at FFBrowserContext.emit (node:events:390:28)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at processImmediate (node:internal/timers:437:9) {
  errno: -4047,
  syscall: 'write',
  code: 'EPIPE'
}

**Comment by mxschmitt** [comment]
Do you have a Playwright instance per thread? Do you have a repro which you can share?

**Comment by mmani648** [comment]
def start_app(account,p):
  with sync_playwright() as playwright:
            server = {'server': f'http://{ip}:{port}', 'username': user,'password': passw}


            driver = playwright.firefox.launch( headless=False,
                                            proxy = server,
                                            firefox_user_prefs = {'media.peerconnection.enabled': False, 'media.navigator.enabled': False, 'privacy.resistFingerprinting': True, 'webgl.disabled': True, 'gfx.direct2d.disabled': True, 'layers.acceleration.disabled': True, 'geo.enabled': True, 'network.dns.use_https_rr_as_altsvc': True, 'privacy.donottrackheader.enabled': True, 'network.dns.echconfig.enabled': True, 'network.security.esni.enabled': True,'network.trr.uri': "1.1.1.1",'network.trr.mode': 1})
        
            context = driver.new_context(ignore_https_errors = True, locale='en-US', timezone_id='America/New_York', no_viewport = True, user_agent = 'Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0')
            page = context.new_page()
            page.goto('https://example.com',wait_until ="commit")
for i in range(thread):
    threading.Thread(target=start_app,args=(account[i],proxies[i],)).start()

**Comment by Leezj9671** [comment]
Have you fixed it? Faced the same problem when using multithreading.

**Comment by mmani648** [comment]
switched back to selenium
