### ISSUE TITLE
[BUG] TypeError: Cannot read properties of undefined (reading 'childFrames')

### ISSUE THREAD

**Issue by AIGeneratedUsername** [microsoft/playwright-python#1267]
**Context:**
- Playwright Version: 1.21.0
- Operating System: Lubuntu 20.04
- Python version: 3.10.4
- Browser: Firefox

## Traceback
```
/home/juol/.cache/pypoetry/virtualenvs/client-NboAmZt6-py3.10/lib/python3.10/site-packages/playwright/driver/package/lib/server/frames.js:339
    for (const child of frame.childFrames()) this._removeFramesRecursively(child);
                              ^

TypeError: Cannot read properties of undefined (reading 'childFrames')
    at FrameManager.removeChildFramesRecursively (/home/juol/.cache/pypoetry/virtualenvs/client-NboAmZt6-py3.10/lib/python3.10/site-packages/playwright/driver/package/lib/server/frames.js:339:31)
    at FrameManager.frameCommittedNewDocumentNavigation (/home/juol/.cache/pypoetry/virtualenvs/client-NboAmZt6-py3.10/lib/python3.10/site-packages/playwright/driver/package/lib/server/frames.js:171:10)
    at FFPage._onNavigationCommitted (/home/juol/.cache/pypoetry/virtualenvs/client-NboAmZt6-py3.10/lib/python3.10/site-packages/playwright/driver/package/lib/server/firefox/ffPage.js:214:30)
    at FFSession.emit (node:events:390:28)
    at /home/juol/.cache/pypoetry/virtualenvs/client-NboAmZt6-py3.10/lib/python3.10/site-packages/playwright/driver/package/lib/server/firefox/ffConnection.js:247:41
```

## Steps to reproduce

Just request some URLs one by one (e.g. `page.goto(url)`). I do nothing special. I work with multiple websites and every has some URLs, so I do not know which URLs may cause the error. Anyway, the error happens regularly. 
I hope that the traceback is self-explanatory enough to handle the error in the Playwright code.

## My current workaround 

The main problem is that after this error happens, a browser stop making any further requests. I do not know, maybe the browser crashes or hangs. 
The only workaround is to close/open a whole context manager.

**Comment by mxschmitt** [comment]
Merging into https://github.com/microsoft/playwright/issues/9840

If you can reproduce this and share with us a repro, this would help us a ton to fix this bug!
