### ISSUE TITLE
[Question] MSEdge not working in PyCharm

### ISSUE THREAD

**Issue by Misha31** [microsoft/playwright-python#1270]
Context:
    Playwright Version:  1.21.0
    Operating System: Windows 10 Pro 21H1
    Python 3.9.7
    PyCharm 2021.3.2
    Browser: Microsoft Edge 99.0.1150.55 (64-bit)

Greetings.
Faced with a strange bug, in PyCharm does not open Microsoft Edge, here is a list of errors:
```
"C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\python.exe" C:/Users/Alf/PycharmProjects/pw/main.py
2022-04-22T20:10:54.018Z pw:browser <launching> C:\Program Files (x86)\Microsoft\Edge\Application\msedge. exe --enable-features=NetworkService,NetworkServiceInProcess --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame, AutoExpandDetailsElement,CertificateTransparencyComponentUpdater --allow-pre-commit-input --force-color-profile=srgb --no-first-run --password-store=basic --no-service-autorun --user-data-dir=C: \Users\Alf\PycharmProjects\pw\tmp --remote-debugging-pipe about:blank
2022-04-22T20:10:54.031Z pw:browser <launched> pid=11132
2022-04-22T20:10:54.033Z pw:protocol SEND ► {"id":1, "method": "Browser.getVersion"}
2022-04-22T20:10:54.211Z pw:browser [pid=11132] <problematic startup completion>
2022-04-22T20:10:54.212Z pw:browser [pid=11132] <kill>
2022-04-22T20:10:54.212Z pw:browser [pid=11132] <will forcibly kill>
2022-04-22T20:10:54.297Z pw:browser [pid=11132] taskkill stderr: 
����ଠ��: �����, �⢥����騥 ������� �����, ����������

2022-04-22T20:10:54.298Z pw:browser [pid=11132] <process ended: exitCode=0, signal=null>
2022-04-22T20:10:54.298Z pw:browser [pid=11132] start temporary directories cleanup
2022-04-22T20:10:54.301Z pw:browser [pid=11132] finished temporary directories cleanup
2022-04-22T20:10:54.301Z pw:browser [pid=11132] <pleasantly close end>
```

But everything works in Visual Studio 2022)
If I change channel="msedge" to channel="chrome" in PyCharm, everything works.

I installed different versions of Python, Egde, PlayWright, but nothing worked.

**Comment by Misha31** [comment]
> Does it work if you run it from terminal without pycharm?

Does not work.

```
C:\Windows\system32>python C:/Users/Alf/PycharmProjects/pw/main.py
Traceback (most recent call last):
  File "C:\Users\Alf\PycharmProjects\pw\main.py", line 206, in <module>
    start()
    browser = p.chromium.launch_persistent_context(
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\playwright\sync_api\_generated.py", line 11728, in launch_persistent_context
    self._sync(
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\playwright\_impl\_sync_base.py", line 88, in _sync
    return task.result()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\playwright\_impl\_browser_type.py", line 148, in launch_persistent_context
    from_channel(await self._channel.send("launchPersistentContext", params)),
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\playwright\_impl\_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\playwright\_impl\_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Executable doesn't exist at C:\Users\Alf\AppData\Local\ms-playwright\chromium-1000\chrome-win\chrome.exe
```

**Comment by Misha31** [comment]
Running in the terminal with administrator privileges, it does not work.
Running in the terminal as a user, everything works, how interesting))

**Comment by mxschmitt** [comment]
Looks similar to https://github.com/microsoft/playwright/issues/13631

Interesting that it works for you with a normal user.

**Comment by Misha31** [comment]
Administrator rights - https://prnt.sc/9CeERf5XeBdN
Without rights - https://prnt.sc/wOgQuxidadg-
What needs to be changed?

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/13631 for now, we currently have no reproduce it, so any community effort in digging into that would be highly appreciated. Our guess were enterprise policies, but maybe there are not the root cause.

**Comment by Misha31** [comment]
> Folding into [microsoft/playwright#13631](https://github.com/microsoft/playwright/issues/13631) for now, we currently have no reproduce it, so any community effort in digging into that would be highly appreciated. Our guess were enterprise policies, but maybe there are not the root cause.

Understood thanks.
In PyCharm without admin rights, the browser starts up.
