### ISSUE TITLE
[Question]: error ERR_PROXY_CONNECTION_FAILED

### ISSUE THREAD

**Issue by dsism** [microsoft/playwright-python#1282]
### Your question

I have the following spider:

```
# Python
from typing import Any, Dict, Iterator, List
from urllib.parse import urlparse

# 3rd Party
from scrapy.spiders import CrawlSpider, Rule
from scrapy.linkextractors import LinkExtractor
from scrapy.link import Link
from scrapy.http import Response
from scrapy.http import Request
from scrapy_playwright.page import PageMethod


class ClientSideSiteSpider(CrawlSpider):
    name = "client-side-site"
    handle_httpstatus_list = [301, 302, 401, 403, 404, 408, 429, 500, 503]
    exclude_patterns: List[str] = []

    custom_settings = {
        "TWISTED_REACTOR": "twisted.internet.asyncioreactor.AsyncioSelectorReactor",
        "DOWNLOAD_HANDLERS": {
            "https": "scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler",
        },
        "ITEM_PIPELINES": {
            "scrapy.pipelines.files.FilesPipeline": 1,
            # some pipelines..
        },
        "DOWNLOADER_MIDDLEWARES": {
            # some middlewares...
            "scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware": 810,
        },
        "PLAYWRIGHT_CONTEXTS": {
            1: {
                "ignore_https_errors": True,
                "proxy": {
                    "server": "my proxy server address ...",
                    "username": "user",
                    "password": "pwd",
                }
            }
        }
    }

    custom_meta = {
        "playwright": True,
        "playwright_context": 1,
        "playwright_include_page": True,
        "playwright_page_methods": [
            PageMethod("wait_for_load_state", "networkidle"),
        ],
    }

    def __init__(
        self,
        crawl_id: str,
        domain: str,
        start_url: str,
        site_id: str,
        user_agent: str = None,
        user_agent_id: str = None,
        **kwargs: Any
    ):
        self.crawl_id = crawl_id
        self.site_id = site_id
        self.user_agent = user_agent
        self.user_agent_id = user_agent_id
        self.allowed_domains: List[str] = [domain]
        self.start_urls: List[str] = [start_url]

        if user_agent is not None:
            self.custom_settings["USER_AGENT"] = user_agent

        url_parsed = urlparse(start_url)
        allow_path = url_parsed.path
        self.rules = (
            Rule(
                LinkExtractor(allow=allow_path),
                callback="parse_item",
                process_links="process_links",
                follow=True,
            ),
        )

        super().__init__(**kwargs)

    def start_requests(self) -> Iterator[Request]:
        for url in self.start_urls:
            yield Request(url, meta=self.custom_meta)

    def process_links(self, links: List[Link]) -> List[Link]:
        ret: List[Link] = []

        for link in links:
            temp = link
            temp.url = temp.url.split("?", 1)[0]  # remove all query strings!
            temp.url = temp.url.split("#", 1)[0]  # remove anchor links!

            if self.not_in_pattern(temp.url):
                ret.append(temp)

        return ret

    def not_in_pattern(self, compare: str) -> bool:
        for pattern in ["tel:", "mailto:"]:
            if pattern in compare:
                return False

        return True

    def parse_start_url(self, response: Response) -> Dict[str, Any]:
        return self.parse_item(response)

    def parse_item(self, response: Response) -> Dict[str, Any]:
        return {
            "status": response.status,
            "file_urls": [response.url],
            "body": response._get_body(),
            "type": response.headers.get("Content-Type", ""),
            "latency": response.meta.get("download_latency"),
        }
```

but I am always getting the error:

`2022-05-05 12:13:13 [scrapy.core.scraper] ERROR: Error downloading <GET https://xxxxx.com/>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.8/dist-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.8/dist-packages/scrapy/core/downloader/middleware.py", line 44, in process_request
    return (yield download_func(request=request, spider=spider))
  File "/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py", line 824, in adapt
    extracted = result.result()
  File "/usr/local/lib/python3.8/dist-packages/scrapy_playwright/handler.py", line 241, in _download_request
    result = await self._download_request_with_page(request, page)
  File "/usr/local/lib/python3.8/dist-packages/scrapy_playwright/handler.py", line 252, in _download_request_with_page
    response = await page.goto(request.url)
  File "/usr/local/lib/python3.8/dist-packages/playwright/async_api/_generated.py", line 7581, in goto
    await self._async(
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_page.py", line 493, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_frame.py", line 122, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: net::ERR_PROXY_CONNECTION_FAILED at https://discountcasino262.com/`

Base on [this](https://github.com/scrapy-plugins/scrapy-playwright#proxy-support), I also tried with

```
PLAYWRIGHT_LAUNCH_OPTIONS = {
    "proxy": {
        "server": "my server address ...",
        "username": "user",
        "password": "pass",
    },
}
```

But got the same error. 
The proxy provider I'm using is ok, since it's working normally with `scrapy`.

Can anyone identify where the problem is? I've been looking for days :(

**Comment by dsism** [comment]
whops... I opened the question in the wrong place ...
