### ISSUE TITLE
[Question]: asyncio.run seems lost proxy setting 

### ISSUE THREAD

**Issue by wanghaisheng** [microsoft/playwright-python#1290]
### Your question

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Program Files\anaconda3\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "autovideo.py", line 807, in upload
    ytb_up_auto.instantpublish(video)
  File "D:\Download\audio-visual\make-reddit-video\autovideopublish\src\upload.py", line 42, in instantpublish
    asyncio.run(self.upload.upload(
  File "D:\Program Files\anaconda3\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "D:\Program Files\anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete 
    return future.result()
  File "D:\Program Files\anaconda3\lib\site-packages\ytb_up-0.1.12-py3.8.egg\ytb_up\upload.py", line 157, in upload
    await page.goto(YOUTUBE_URL,timeout=0)
  File "D:\Program Files\anaconda3\lib\site-packages\playwright\async_api\_generated.py", line 7486, in goto
    await self._async(
  File "D:\Program Files\anaconda3\lib\site-packages\playwright\_impl\_page.py", line 484, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "D:\Program Files\anaconda3\lib\site-packages\playwright\_impl\_frame.py", line 122, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "D:\Program Files\anaconda3\lib\site-packages\playwright\_impl\_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "D:\Program Files\anaconda3\lib\site-packages\playwright\_impl\_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: NS_ERROR_NET_RESET
=========================== logs ===========================
navigating to "https://www.youtube.com/", waiting until "load"
============================================================
```

this is a workable way ,i can get final result

```
from ytb_up import *
from datetime import datetime,date,timedelta
import asyncio

profilepath = r'D:\Download\audio-visual\make-reddit-video\auddit\assets\profile\aww'
CHANNEL_COOKIES = r'D:\Download\audio-visual\make-reddit-video\auddit\assets\cookies\aww.json'

videopath = r'D:\Download\audio-visual\objection_engine\hello.mp4'
tags = ['ba,baaa,bababa']
publish_date = ''
# if you use some kinda of proxy to access youtube, 
proxy_option = "socks5://127.0.0.1:1080"

# for cookie issue,
title = 'bababala'
title=title[:95]
username = "antivte"
password = ""
description = '========================'
driverpath = r'D:\Download\audio-visual\make-reddit-video\autovideo\assets\driver\geckodriver-v0.30.0-win64\geckodriver.exe'
thumbnail = r'D:\Download\audio-visual\make-reddit-video\auddit\assets\ace\ace-attorney_feature.jpg'
upload = Upload(
    # use r"" for paths, this will not give formatting errors e.g. "\n"
    root_profile_directory='',
    proxy_option=proxy_option,
    watcheveryuploadstep=True,
    # if you want to silent background running, set watcheveryuploadstep false
    CHANNEL_COOKIES=CHANNEL_COOKIES,
    username=username,
    password=password,
    recordvideo=True
    # for test purpose we need to check the video step by step ,
)
today = date.today()


def instantpublish():

    asyncio.run(upload.upload(
        videopath=videopath,
        title='instant publish-test-005',
        description=description,
        thumbnail=thumbnail,
        tags=tags,
        closewhen100percentupload=True,
        publishpolicy=1
    ))

```

not working way,init seem ok,but goto(URL) always failed

```
from ytb_up import Upload
from datetime import datetime,date,timedelta
import asyncio

class YTB_UP_AUTO:
    def __init__(self, profilepath='',CHANNEL_COOKIES='',proxy_option='',username='',password='',watcheveryuploadstep=True,recordvideo=True):
        self.profilepath=profilepath
        self.CHANNEL_COOKIES=CHANNEL_COOKIES
        self.password=password
        self.watcheveryuploadstep=watcheveryuploadstep
        self.username=username
        self.proxy_option=proxy_option
        self.recordvideo=recordvideo

        self.upload = Upload(
            # use r"" for paths, this will not give formatting errors e.g. "\n"
            root_profile_directory=self.profilepath,
            proxy_option=self.proxy_option,
            watcheveryuploadstep=self.watcheveryuploadstep,
            # if you want to silent background running, set watcheveryuploadstep false
            CHANNEL_COOKIES=self.CHANNEL_COOKIES,
            username=self.username,
            password=self.password,
            recordvideo=True
            # for test purpose we need to check the video step by step ,
        )

    def instantpublish(self,video):

        asyncio.run(self.upload.upload(
            videopath=video.videopath,
            title=video.title,
            description=video.des,
            thumbnail=video.thumbpath,
            tags=video.tags,
            closewhen100percentupload=True,
            publish_date=video.publish_date,
            publishpolicy=1
        ))

```

my async playwright func

```
    async def upload(
        self,
        videopath: str="",
        title: str = "",
        description: str = "",
        thumbnail: str = "",
        publishpolicy: str = 0,
        headless=True
        if self.watcheveryuploadstep:
            headless=False
        print('whether run in view mode',headless)
        if self.proxy_option == "":
            print('start web page without proxy')

            browserLaunchOptionDict = {
                "headless": headless,
                # "executable_path": executable_path,
                "timeout": 30000
            }

```

**Comment by mxschmitt** [comment]
Thanks for the report! Would it be possible to share a smaller repro with us which we can run locally?

**Comment by wanghaisheng** [comment]
just download zip from this branch  you can try ok and failed.py.

https://github.com/wanghaisheng/autovideopublish/tree/pl-test
@mxschmitt

**Comment by mxschmitt** [comment]
It's still very very big, are you able to create a repro out of it which only contains a single file? We often spend days on digging into issues and bugs, having a smaller repro would help a lot. Thanks!

**Comment by wanghaisheng** [comment]
pls dont use git clone  .just manually download zip is fast
other files you can ignore.just ok and failed.py

**Comment by mxschmitt** [comment]
Its not working for me: `FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Download\\audio-visual\\make-reddit-video\\auddit\\assets\\cookies\\aww.json'`

**Comment by wanghaisheng** [comment]
you should find this file exact under root folder,
assets/cookies/aww.json oh  my channel you may not login in
or just export your own youtube cookie as json

**Comment by mxschmitt** [comment]
your script depends on absolute file paths and is not OS agnostic, are you able to provide us a script which we can run locally and demonstrates your bug?

**Comment by peipeiwei303-netizen** [comment]
Super relatable pain point: you clearly defined proxy args but they get lost entirely inside asyncio request flows.

Troubleshooting for missing proxy config under asyncio: 

The root cause is usually improper isolation of proxy configuration across separate async task contexts. Shared global proxy variables often get discarded during context switching triggered by asyncio.run().

Make sure you pass the complete proxy parameter set as an independent argument directly into each individual async task entry, rather than referencing a global variable that fails to persist through async lifecycle shifts.

For long-running async Playwright YouTube scraping/upload pipelines, [Novada residential proxies](https://www.novada.com/?GithubOx) solve unstable proxy session and dropped network identity issues fundamentally. Our sticky session locking maintains one consistent residential exit IP bound to every browser context through the whole async workflow, avoiding mid-task connection resets like the NS_ERROR_NET_RESET error you hit. Free test API keys are available for developers building YouTube automation stacks.
