### ISSUE TITLE
[BUG?] Timeout thrown even though `.click(no_wait_after=True)`

### ISSUE THREAD

**Issue by bwinter** [microsoft/playwright-python#1346]
**Context:**
- Playwright Version: 1.22
- Operating System: Linux (Docker)
- Python version: Whatever ships with: mcr.microsoft.com/playwright/python:v1.22.0-focal
- Browser: I assume that image uses Chromium?
- Extra: I am not sure if this is a bug or me just missunderstanding.

**Code Snippet**

This is an intermittent bug but the code would look something like this:

```python
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()
    page.locator("[data-testid=\"navLink-cluster-group-list\"] >> text=Cluster groups").click(no_wait_after=True)
    browser.close()
```

**Describe the bug**

I expect this click line to never throw a timeout error and yet I see this in some stack traces:

```shell
Traceback (most recent call last):
  File "my_script.py", line 191, in <module>
    run(playwright)
  File "my_script.py", line 172, in run
    page.locator("[data-testid=\"navLink-cluster-group-list\"] >> text=Cluster groups").click(no_wait_after=True)
  File "/usr/local/lib/python3.8/dist-packages/playwright/sync_api/_generated.py", line 12238, in click
    self._sync(
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_sync_base.py", line 88, in _sync
    return task.result()
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_locator.py", line 144, in click
    return await self._frame.click(self._selector, strict=True, **params)
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_frame.py", line 460, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "[data-testid="navLink-cluster-group-list"] >> text=Cluster groups"
============================================================
```

Is this expected? Maybe I am thinking about this option incorrectly.

**Comment by mxschmitt** [comment]
This is expected, since the element which you are trying to click is not found on the page.

**Comment by bwinter** [comment]
Oh I see, so it hasn't even found the element yet. Looking at the stack trace, I had assumed this error was being thrown inside the click function - which I assumed would only get called if the locator had already found the element.

Can you help me understand how you know the locator is failing here and not the click function?
