### ISSUE TITLE
[BUG] Calling Network.getCertificate via CDP results in traceback

### ISSUE THREAD

**Issue by byt3bl33d3r** [microsoft/playwright-python#1381]
**Context:**
- Playwright Version: 1.22.0
- Operating System: Linux
- Python version: 3.9
- Browser: Chromium
- Extra: Playwright CDP session to a [Browserless Docker Container](https://github.com/browserless/chrome)

**Code Snippet**

```python
import asyncio
from playwright.async_api import async_playwright
from playwright._impl._api_types import Error as PlaywrightError

async def do_stuff(url):
    async with async_playwright() as p:
        browser = await p.chromium.connect_over_cdp('ws://chromelb:4000/?ignoreHTTPSErrors=true&ignoreDefaultArgs=--no-sandbox')

        page = await browser.new_page()
        client = await page.context.new_cdp_session(page)

        try:
            r = await page.goto(url, wait_until='networkidle')
        except PlaywrightError as e:
            if not 'CERT' in str(e):
                raise

            r = await page.goto(url, wait_until='networkidle')

        r = await client.send('Network.getCertificate')
        print(r)
        await browser.close()

asyncio.run(do_stuff('https://89.119.86.194:10443/'))
```

**Describe the bug**

Calling `await client.send('Network.getCertificate')` to retrieve the DER encoded TLS certificate results in a traceback

```
Traceback (most recent call last):
  File "/workspace/witnessme/cert_test.py", line 24, in <module>
    asyncio.run(do_stuff('https://89.119.86.194:10443/'))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/workspace/witnessme/cert_test.py", line 20, in do_stuff
    r = await client.send('Network.getCertificate')
  File "/home/vscode/.local/lib/python3.9/site-packages/playwright/async_api/_generated.py", line 11113, in send
    await self._async(
  File "/home/vscode/.local/lib/python3.9/site-packages/playwright/_impl/_cdp_session.py", line 32, in send
    return await self._channel.send("send", locals_to_params(locals()))
  File "/home/vscode/.local/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/home/vscode/.local/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Protocol error (Network.getCertificate): Invalid parameters Failed to deserialize params - CBOR: map start expected at position 0
```

**Comment by mxschmitt** [comment]
Network.getCertificate has a required parameter `name`: https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-getCertificate
