### ISSUE TITLE
[BUG] env:python3.7 [ValueError: signal only works in main thread ] raise error in subthread

### ISSUE THREAD

**Issue by ysj1104780606** [microsoft/playwright-python#1514]
**Context:**
- Playwright Version: 1.22.0
- Operating System: mac
- Python version:python3.7
- Browser: Chromium
- Extra: For some reason, I have to use python 3.7 and run the script in subthread.

**Code Snippet**

```python
from playwright.sync_api import sync_playwright
 def task():
        sync_playwright().start()

t = Thread(target=task)
t.start()
```

**Describe the bug**
On Python 3.7, I run the script in the subthread and the signal raise an error.[ValueError: signal only works in main thread ] 
For some reason, I have to use python 3.7 and run the script in subthread.
Dear developer, can I do something to avoid this problem?🧸

Add any other details about the problem here.
```python
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/bytedance/Downloads/uiautomation-saas/test/feishu/smoke/vc_innovation/web/upload_file.py", line 66, in task
    sync_playwright().start()
  File "/Users/bytedance/Downloads/uiautomation-saas/venv/lib/python3.7/site-packages/playwright/sync_api/_context_manager.py", line 94, in start
    return self.__enter__()
  File "/Users/bytedance/Downloads/uiautomation-saas/venv/lib/python3.7/site-packages/playwright/sync_api/_context_manager.py", line 61, in __enter__
    asyncio.set_child_watcher(self._watcher)  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/events.py", line 773, in set_child_watcher
    return get_event_loop_policy().set_child_watcher(watcher)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 1152, in set_child_watcher
    self._watcher.close()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 930, in close
    super().close()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 863, in close
    self.attach_loop(None)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 881, in attach_loop
    self._loop.remove_signal_handler(signal.SIGCHLD)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 147, in remove_signal_handler
    signal.signal(sig, handler)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
```

**Comment by symonk** [comment]
I don't think playwright-python sync api is thread safe @ysj1104780606, consider multi processing

**Comment by ysj1104780606** [comment]
> I don't think playwright-python sync api is thread safe @ysj1104780606, consider multi processing

thanks, I'll try it~

**Comment by ysj1104780606** [comment]
> I don't think playwright-python sync api is thread safe @ysj1104780606, consider multi processing
It is very useful to switch to multi-process.tks!!!!!
