### ISSUE TITLE
[BUG] AttributeError: 'PlaywrightContextManager' object has no attribute '_playwright'

### ISSUE THREAD

**Issue by mborsetti** [microsoft/playwright-python#1565]
**Context:**
- Playwright Version: `1.26.0`
- Operating System: Windows 11 Pro version `10.0.22000 Build 22000`
- Python version: `3.10.7`
- Browser: Google Chrome `105.0.5195.127 (Official Build) (64-bit)`
- Extra: node `v18.9.1`

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally.

```python
>>> from playwright.sync_api import sync_playwright
>>> with sync_playwright() as p:
...     browser = p.chromium.launch(channel='chrome')
...
'""C:\Program' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python\Python310\lib\site-packages\playwright\sync_api\_context_manager.py", line 89, in __enter__
    playwright = self._playwright
AttributeError: 'PlaywrightContextManager' object has no attribute '_playwright'
>>>
```

**Describe the bug**

```AttributeError: 'PlaywrightContextManager' object has no attribute '_playwright'```

Add any other details about the problem here.

Also weird output
```
'""C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by funnydevdotvn** [comment]
You could try my solution here [https://github.com/microsoft/playwright-python/issues/1561#issuecomment-1257091619](url)

**Comment by mborsetti** [comment]
Any suggestion as to how one can install the new, fixed, code, to resuscitate Playwright?

Neither building from GitHub by running `pip install git+https://github.com/microsoft/playwright-python@main` nor reverting to a prior version with `pip install playwright<1.26` yields a working version of Playwright. It appears that the fix has been applied to on an unreleased `npm` dependency of `playwright-python`, and I don't know how to install that code, which contains the unreleased fix.  As a result, Playwright is still bricked on Windows.

**Comment by mxschmitt** [comment]
You can either continue to use 1.25 for a few days or wait for 1.26.1 which we'll publish in a few days.

**Comment by funnydevdotvn** [comment]
> Any suggestion as to how one can install the new, fixed, code, to resuscitate Playwright?
> 
> Neither building from GitHub by running `pip install git+https://github.com/microsoft/playwright-python@main` nor reverting to a prior version with `pip install playwright<1.26` yields a working version of Playwright. It appears that the fix has been applied to on an unreleased `npm` dependency of `playwright-python`, and I don't know how to install that code, which contains the unreleased fix. As a result, Playwright is still bricked on Windows.

You could try my solution here [https://github.com/microsoft/playwright-python/issues/1561#issuecomment-1257091619](https://github.com/microsoft/playwright-python/issues/url) manually while you still wait for playwright 1.26.xx release update. I prefer to used 1.26.xx and up, not previous versions because of if you use Python 3.10 with 1.25.xx will get stuck if call launch_persistant_contant and some other errors which make browser crashed.
