### ISSUE TITLE
[BUG] TypeError: attrib() got an unexpected keyword argument 'eq'

### ISSUE THREAD

**Issue by Zerka30** [microsoft/playwright-python#1591]
**Context:**
- Playwright Version: Version 1.25.2
- Operating System: Windows 10
- Python version: Python 3.10.7
- Browser: all

**Code Snippet**

```python
import asyncio
import botright


async def main():
    botright_client = await botright.Botright()
    browser = await botright_client.new_browser()
    page = await browser.new_page()

    await page.goto("http://playwright.dev")
    print(await page.title())

    await botright_client.close()


if __name__ == "__main__":
    asyncio.run(main())

```

**Describe the bug**

I recently tried to use a python script that imports the 'botright' module which in turn imports playwright. However, each time, it crashes when importing this module obviously because of playwright. I have no idea why.

Here is the exact stacktrace

```python
Traceback (most recent call last):
  File "f:\test.py", line 2, in <module>
    import botright
  File "C:\Users\Zerka\AppData\Local\Programs\Python\Python310\lib\site-packages\botright\__init__.py", line 3, in <module>       
    from .botright import *
  File "C:\Users\Zerka\AppData\Local\Programs\Python\Python310\lib\site-packages\botright\botright.py", line 3, in <module>       
    from playwright.async_api import async_playwright
  File "C:\Users\Zerka\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\async_api\__init__.py", line 25, in <module>
    import playwright.async_api._generated
  File "C:\Users\Zerka\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\async_api\_generated.py", line 25, in 
<module>
    from playwright._impl._accessibility import Accessibility as AccessibilityImpl
  File "C:\Users\Zerka\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_accessibility.py", line 17, in 
<module>
    from playwright._impl._connection import Channel
  File "C:\Users\Zerka\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 24, in <module>
    from pyee import AsyncIOEventEmitter, EventEmitter
  File "C:\Users\Zerka\AppData\Local\Programs\Python\Python310\lib\site-packages\pyee\__init__.py", line 71, in <module>
    from pyee._trio import TrioEventEmitter  # noqa
  File "C:\Users\Zerka\AppData\Local\Programs\Python\Python310\lib\site-packages\pyee\_trio.py", line 4, in <module>
    import trio
  File "C:\Users\Zerka\AppData\Local\Programs\Python\Python310\lib\site-packages\trio\__init__.py", line 18, in <module>
    from ._core import (
  File "C:\Users\Zerka\AppData\Local\Programs\Python\Python310\lib\site-packages\trio\_core\__init__.py", line 27, in <module>    
    from ._run import (
  File "C:\Users\Zerka\AppData\Local\Programs\Python\Python310\lib\site-packages\trio\_core\_run.py", line 22, in <module>        
    from outcome import Error, Outcome, Value, capture
  File "C:\Users\Zerka\AppData\Local\Programs\Python\Python310\lib\site-packages\outcome\__init__.py", line 3, in <module>        
    from ._impl import Error, Outcome, Value, acapture, capture
  File "C:\Users\Zerka\AppData\Local\Programs\Python\Python310\lib\site-packages\outcome\_impl.py", line 39, in <module>
    class Outcome(abc.ABC):
  File "C:\Users\Zerka\AppData\Local\Programs\Python\Python310\lib\site-packages\outcome\_impl.py", line 54, in Outcome
    _unwrapped = attr.ib(default=False, eq=False, init=False)
TypeError: attrib() got an unexpected keyword argument 'eq'
```

**Comment by mxschmitt** [comment]
I recommend to file an issue in their repo: https://github.com/Vinyzu/Botright

**Comment by Zerka30** [comment]
I take the liberty to reopen because an issue has already been created on the directory of the python package [here](https://github.com/Vinyzu/Botright/issues/2) however the creator notified that it was not a bug of Botright but of playwright

**Comment by mxschmitt** [comment]
If you can provide a repro without botright, we're happy to take a look!

Otherwise we have to assume it's caused by their lib.

**Comment by Vinyzu** [comment]
Update:
It was caused by an outdated `trio` package, which is required through another package from playwright.

It can be fixxed with `pip install trio --upgrade`
