### ISSUE TITLE
[BUG]Navigation failed because page was closed!

### ISSUE THREAD

**Issue by viponedream** [microsoft/playwright-python#1615]
When i open the extension,  it opened well, but  vscode stop and say
Navigation failed because page was closed!

it seems the extension is opened and nothing error on the browser.
How to make vscode continue ?

![QQ图片20221031075932](https://user-images.githubusercontent.com/16624529/198908404-bfb2aafa-8587-4992-b2c3-4f185ac3d8c2.png)

**Comment by viponedream** [comment]
navigating to "chrome-extension://dmkamcknogkgcdfhhbddcghachkejeap/popup.html", waiting until "load"
============================================================
python-BaseException
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: EPIPE: broken pipe, write
    at Socket._write (node:internal/net:55:25)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at PipeTransport.send (C:\Python39\Lib\site-packages\playwright\driver\package\lib\protocol\transport.js:54:21)
    at DispatcherConnection.dispatcherConnection.onmessage (C:\Python39\Lib\site-packages\playwright\driver\package\lib\cli\driver.js:69:57)
    at DispatcherConnection._sendMessageToClient (C:\Python39\Lib\site-packages\playwright\driver\package\lib\server\dispatchers\dispatcher.js:248:10)
    at DispatcherConnection.sendCreate (C:\Python39\Lib\site-packages\playwright\driver\package\lib\server\dispatchers\dispatcher.js:210:10)
    at new Dispatcher (C:\Python39\Lib\site-packages\playwright\driver\package\lib\server\dispatchers\dispatcher.js:94:40)
    at new JSHandleDispatcher (C:\Python39\Lib\site-packages\playwright\driver\package\lib\server\dispatchers\jsHandleDispatcher.js:35:5)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at processImmediate (node:internal/timers:437:9) {
  errno: -4047,
  syscall: 'write',
  code: 'EPIPE'
}
