### ISSUE TITLE
[BUG] playwright._impl._api_types.Error: Execution context was destroyed, most likely because of a navigation

### ISSUE THREAD

**Issue by Fly-Playgroud** [microsoft/playwright-python#1672]
**Context:**
- Playwright Version: 1.28
- Operating System:Windows
- Python version: 3.9
- Browser: All

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally.

```python
class Browser:
    def __init__(self, port=9222):
        self.remote_debug_port = port
        self.remote_debug_address = None
        self.context: BrowserContext = None
        self.started = False

    async def setup(self):
        args = [
            "--remote-debugging-port={}".format(self.remote_debug_port),
            "--disable-gpu",
            "--no-sandbox",
            "--disable-webgl",
            "--allow-running-insecure-content",
            "--disable-xss-auditor",
            "--disable-web-security"
            "--enable-automation=false"
        ]
        chrome = await async_playwright().start()
        self.context = await chrome.chromium.launch_persistent_context(
            ignore_https_errors=True,
            headless=False,
            args=args,
            user_data_dir=ChromeConfig.USER_DATA_DIR,
            executable_path=ChromeConfig.CHROME_PATH_WIN,
            user_agent=ChromeConfig.USER_AGENT
        )
        self.started = True

    async def open_page(self, url):
        page = await self.context.new_page()
        await page.add_init_script(script=coreJs)
        page.on("console", lambda msg: console_handler(msg, page))
        await page.goto(url, wait_until="networkidle")

    async def close_page(self):
        pass

    async def close(self):
        await self.context.close()
        self.started = False

    async def is_running(self):
        return self.started


async def console_handler(msg, page):
    if msg.text == 'DomUpdate':
        await page.evaluate("xxxxxxxx.removeAllTargetBlank();")
```

**Describe the bug**
I used `async def open_page(self, url)` to create the page, and when I create the page I used `await page.add_init_script(script=coreJs)` to inject JS script into the new page, and used `page.on("console", lambda msg: console_handler(msg, page))` to listen to the console event, but when I refreshed the page, the handler function throws an exception when the event is triggered, as follows:
```python

Exception in callback AsyncIOEventEmitter._emit_run.<locals>.callback(<Task finishe...gationnixxx')>) at M:\project\loginRecord\venv\lib\site-packages\pyee\asyncio.py:65
handle: <Handle AsyncIOEventEmitter._emit_run.<locals>.callback(<Task finishe...gationnixxx')>) at M:\project\loginRecord\venv\lib\site-packages\pyee\asyncio.py:65>
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "M:\project\loginRecord\venv\lib\site-packages\pyee\asyncio.py", line 71, in callback
    self.emit("error", exc)
  File "M:\project\loginRecord\venv\lib\site-packages\pyee\base.py", line 179, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "M:\project\loginRecord\venv\lib\site-packages\pyee\base.py", line 139, in _emit_handle_potential_error
    raise error
  File "M:\project\loginRecord\core\async_utils.py", line 6, in console_handler
    await page.evaluate("xxxxxxx.removeAllTargetBlank();")
  File "M:\project\loginRecord\venv\lib\site-packages\playwright\async_api\_generated.py", line 7684, in evaluate
    await self._impl_obj.evaluate(
  File "M:\project\loginRecord\venv\lib\site-packages\playwright\_impl\_page.py", line 407, in evaluate
    return await self._main_frame.evaluate(expression, arg)
  File "M:\project\loginRecord\venv\lib\site-packages\playwright\_impl\_frame.py", line 277, in evaluate
    await self._channel.send(
  File "M:\project\loginRecord\venv\lib\site-packages\playwright\_impl\_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "M:\project\loginRecord\venv\lib\site-packages\playwright\_impl\_connection.py", line 419, in wrap_api_call
    return await cb()
  File "M:\project\loginRecord\venv\lib\site-packages\playwright\_impl\_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Execution context was destroyed, most likely because of a navigation


```

**Comment by mxschmitt** [comment]
Looks stale, please re-file with a repro.
