### ISSUE TITLE
[BUG] Python3.7 ValueError: signal only works in main thread

### ISSUE THREAD

**Issue by byehack** [microsoft/playwright-python#1685]
**Context:**
- Playwright Version: 1.28
- Operating System: Linux
- Python version: 3.7
- Browser: Firefox
- Extra: ran on codespaces.

**Code Snippet**

```python
from playwright.sync_api import sync_playwright

def my_thread():
    with sync_playwright() as pw:
        pass

threading.Thread(target=my_thread).start()
```

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "-", line 958, in my_thread
  File "/home/vscode/.local/lib/python3.7/site-packages/playwright/sync_api/_context_manager.py", line 61, in __enter__
    asyncio.set_child_watcher(self._watcher)  # type: ignore
  File "/usr/local/lib/python3.7/asyncio/events.py", line 773, in set_child_watcher
    return get_event_loop_policy().set_child_watcher(watcher)
  File "/usr/local/lib/python3.7/asyncio/unix_events.py", line 1152, in set_child_watcher
    self._watcher.close()
  File "/usr/local/lib/python3.7/asyncio/unix_events.py", line 930, in close
    super().close()
  File "/usr/local/lib/python3.7/asyncio/unix_events.py", line 863, in close
    self.attach_loop(None)
  File "/usr/local/lib/python3.7/asyncio/unix_events.py", line 881, in attach_loop
    self._loop.remove_signal_handler(signal.SIGCHLD)
  File "/usr/local/lib/python3.7/asyncio/unix_events.py", line 147, in remove_signal_handler
    signal.signal(sig, handler)
  File "/usr/local/lib/python3.7/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
```

It is coming from this patch: https://github.com/microsoft/playwright-python/pull/1213
![image](https://user-images.githubusercontent.com/26390254/208105139-439f34e4-cb0c-409e-a36c-c367121a3128.png)

**Comment by byehack** [comment]
relative https://github.com/intel/dffml/commit/c1e8d85771093d8c55ee46f292f3f6e284914c37 https://github.com/intel/dffml/commit/976a614fb2a64790e05fdf4901fa0a8d28d40337

**Comment by byehack** [comment]
temporary solution is run once `sync_playwright` in main thread then use it in your threads. this is cause last asyncio loop need to remove handlers from child watcher.

```python
import threading
from playwright.sync_api import sync_playwright

with sync_playwright() as pw: pass


def my_thread():
    with sync_playwright() as pw:
        ...


threading.Thread(target=my_thread).start()
```

**Comment by mxschmitt** [comment]
I apologize for the late reply. We dropped support for Python 3.7, so this seems not relevant anymore. Feel free to re-file if you are affected with 3.8+.
