### ISSUE TITLE
Issue building with python-build/installer

### ISSUE THREAD

**Issue by jelly** [microsoft/playwright-python#1704]
For packaging playwright for Arch Linux I tried to build and install it using:

```
python -m build --wheel --no-isolation
python -m installer --destdir="$pkgdir" dist/*.whl
```

this fails currently with:

```
==> Starting package()...
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.10/site-packages/installer/__main__.py", line 98, in <module>
    _main(sys.argv[1:], "python -m installer")
  File "/usr/lib/python3.10/site-packages/installer/__main__.py", line 94, in _main
    installer.install(source, destination, {})
  File "/usr/lib/python3.10/site-packages/installer/_core.py", line 96, in install
    for record_elements, stream, is_executable in source.get_contents():
  File "/usr/lib/python3.10/site-packages/installer/sources.py", line 158, in get_contents
    assert record is not None, "In {}, {} is not mentioned in RECORD".format(
AssertionError: In dist/playwright-1.29.0-py3-none-manylinux1_x86_64.whl, playwright/driver/node is not mentioned in RECORD
==> ERROR: A failure occurred in package().
    Aborting...
```

The generated wheel seems to be wrong:

```
[jelle@natrium][~/Downloads/python-playwright/src/playwright-python-1.29.0/dist]%cat --style=plain playwright-1.29.0.dist-info/RECORD
playwright/__init__.py,sha256=BsOs2t0T4oE_y5WtkdU-44hcK19HO-zMRaV52c7q1ws,805
playwright/__main__.py,sha256=Ni-VibWcnhVpntP9VLeUHWUB2AGFh1QRyqP3TYTs4qI,964
playwright/_repo_version.py,sha256=_rctfPDph1ATziwQ_Kw-ESD20nyypxJbuBbphV5sTK8,19
playwright-1.29.0.dist-info/LICENSE,sha256=f6sUYbQZcP83bxyTA6Y3B2v6rrcc0S3TocRKr1mhork,11399
playwright-1.29.0.dist-info/METADATA,sha256=Pgv7IMtkLP_NeMgW-XVMzKmuw--5UlClKCBnJOgKqeY,3565
playwright-1.29.0.dist-info/WHEEL,sha256=2wepM1nk4DS4eFpYrW1TTqPcoGNfHhhO_i5m4cOimbo,92
playwright-1.29.0.dist-info/entry_points.txt,sha256=G-lS5tnQw21PHcXKbZFGy81lczindXIDUejIefH8VoY,130
playwright-1.29.0.dist-info/top_level.txt,sha256=oYiz5-Zb4y23ANZot2i3lMsK-BAiwXqTlQ4hytLJYuE,11
playwright-1.29.0.dist-info/RECORD,,
```

Versus:

```
playwright-1.28.0.dist-info/LICENSE,sha256=f6sUYbQZcP83bxyTA6Y3B2v6rrcc0S3TocRKr1mhork,11399
playwright-1.28.0.dist-info/top_level.txt,sha256=oYiz5-Zb4y23ANZot2i3lMsK-BAiwXqTlQ4hytLJYuE,11
playwright-1.28.0.dist-info/WHEEL,sha256=G16H4A3IeoQmnOrYV4ueZGKSjhipXx8zc8nu9FGlvMA,92
playwright-1.28.0.dist-info/entry_points.txt,sha256=G-lS5tnQw21PHcXKbZFGy81lczindXIDUejIefH8VoY,130
playwright-1.28.0.dist-info/RECORD,,
playwright-1.28.0.dist-info/METADATA,sha256=c6Rm8AR52ue-ODdcg_uzALl5aRwOsVb365cU_ElV8Lo,3565
playwright/_repo_version.py,sha256=awUd0rfOi79VMjM8HkYDAE0wB4W10wqUL1kdZAy76qM,19
playwright/py.typed,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
playwright/__main__.py,sha256=Ni-VibWcnhVpntP9VLeUHWUB2AGFh1QRyqP3TYTs4qI,964
playwright/__init__.py,sha256=BsOs2t0T4oE_y5WtkdU-44hcK19HO-zMRaV52c7q1ws,805
......
```

Seems setup.py works but does not install the `driver` folder.

**Comment by mxschmitt** [comment]
Playwright does not support arch Linux, since we don't compile the browsers for this Linux distribution. I'd recommend to file a feature request in the https://github.com/microsoft/playwright repository first or what are you trying to achieve?

**Comment by mxschmitt** [comment]
Closing as per above.
