### ISSUE TITLE
Using tor as a proxy throws net::ERR_NO_SUPPORTED_PROXIES error

### ISSUE THREAD

**Issue by timborden** [microsoft/playwright-python#1709]
**Context:**
- Playwright Version: 1.27.1
- Operating System: Linux (Ubuntu 20.04)
- Python version: 3.8
- Browser: Chromium
- Extra: [any specific details about your environment]

**Code Snippet**

I'm trying to use tor as a proxy.

This works as expected:
```bash
python3
>>> import requests
>>> session = requests.session()
>>> session.proxies = { "http": "socks5h://localhost:9050", "https": "socks5h://localhost:9050" }
>>> r = session.get("http://httpbin.org/ip")
>>> r.text
'{\n  "origin": "185.86.151.168"\n}\n'
```

Here's the error:
```bash
>>> from playwright.sync_api import sync_playwright
>>> with sync_playwright() as p:
...     browser = p.chromium.launch(proxy={ "server": "socks5h://localhost:9050" })
...     context = browser.new_context()
...     page = browser.new_page()
...     page.goto("http://httpbin.org/ip")
...
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/usr/local/lib/python3.8/dist-packages/playwright/sync_api/_generated.py", line 8114, in goto
    self._sync(
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_frame.py", line 146, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_connection.py", line 396, in wrap_api_call
    return await cb()
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: net::ERR_NO_SUPPORTED_PROXIES at http://httpbin.org/ip
```

**Describe the bug**

I've double-checked the docs `SOCKS proxies are supported` - https://playwright.dev/python/docs/api/class-browsertype#browser-type-launch-option-proxy

What am I missing?

**Comment by mxschmitt** [comment]
Looks like a duplicate of https://github.com/microsoft/playwright/issues/10567. Since socks5h is socks with authentication.

**Comment by timborden** [comment]
I think I set up `tor` in the `Dockerfile` to not need authentication:

```
RUN echo "ControlPort 9051" > /etc/tor/torrc && echo "CookieAuthentication 0" >> /etc/tor/torrc 
```

(also, the above example using Python's `request` package isn't using authentication)

**Comment by mxschmitt** [comment]
You can try not using socks5h and using socks5:// instead then it might work!

**Comment by timborden** [comment]
That did it!

```
# python3
Python 3.8.10 (default, Nov 14 2022, 12:59:47)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from playwright.sync_api import sync_playwright
>>> with sync_playwright() as p:
...     browser = p.chromium.launch(proxy={ "server": "socks5://localhost:9050" })
...     context = browser.new_context()
...     page = browser.new_page()
...     page.goto("http://httpbin.org/ip")
...
<Response url='http://httpbin.org/ip' request=<Request url='http://httpbin.org/ip' method='GET'>>
```

Learned something about socks5h and socks5h today ...thanks for your help!
