### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by G-shaft** [microsoft/playwright-python#1730]
**Context:**
- Playwright Version: 1.29.1
- Operating System: Windows
- Python version: 3.10.5
- Browser: All
- Extra: [any specific details about your environment]

**Code Snippet**

```python
from playwright.sync_api import sync_playwright
import traceback

def run(playwright):
    browser = playwright.chromium.launch(headless=False, channel="msedge")
    page = browser.new_page()
    page.goto("https://github.com/")
    browser.close()

with sync_playwright() as playwright:
    try:
        run(playwright)
    except:
        traceback.print_exc()
```

Traceback (most recent call last):
  File "<frozen main>", line 16, in <module>
  File "<frozen main>", line -1, in run
  File "playwright\sync_api\_generated.py", line 13792, in new_page
  File "playwright\_impl\_sync_base.py", line 97, in _sync
  File "inspect.py", line 1678, in stack
  File "inspect.py", line 1655, in getouterframes
  File "inspect.py", line 1627, in getframeinfo
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

When I obfuscate the code using pyarmor with the creation of an .exe file (pyarmor pack -e " --onefile" main.py), I get this error. The browser opens, but everything crashes when I try to execute page.goto.

**Comment by mxschmitt** [comment]
Obfuscating Playwright code is not supported.
