### ISSUE TITLE
[Question]: asyncio.exceptions.CancelledError

### ISSUE THREAD

**Issue by re1oaded** [microsoft/playwright-python#1761]
### Your question

I have ignored all exceptions and errors in my code, but I still get the following exception:

```
Task was destroyed but it is pending!
task: <Task pending name='Task-308' coro=<BrowserContext._on_route() done, defined at /usr/local/lib/python3.9/dist-packages/playwright/_impl/_browser_context.py:184> wait_for=<_GatheringFuture finished exception=CancelledError()>>
_GatheringFuture exception was never retrieved
future: <_GatheringFuture finished exception=CancelledError()>
Traceback (most recent call last):
  File "/root/test/test.py", line 70, in ad
    page.goto(url, wait_until='networkidle')
  File "/usr/local/lib/python3.9/dist-packages/playwright/sync_api/_generated.py", line 9183, in goto
    self._sync(
  File "/usr/local/lib/python3.9/dist-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/usr/local/lib/python3.9/dist-packages/playwright/_impl/_page.py", line 491, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "/usr/local/lib/python3.9/dist-packages/playwright/_impl/_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/usr/local/lib/python3.9/dist-packages/playwright/_impl/_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "/usr/local/lib/python3.9/dist-packages/playwright/_impl/_connection.py", line 419, in wrap_api_call
    return await cb()
  File "/usr/local/lib/python3.9/dist-packages/playwright/_impl/_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Navigation failed because page crashed!
=========================== logs ===========================
navigating to "https://www.bing.com/", waiting until "networkidle"
============================================================

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/tasks.py", line 529, in _wait
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

asyncio.exceptions.CancelledError
```

How to ignore these exceptions, I need to display and print the log of the program running, it blocks me.

Is it related to multithreading? [https://github.com/microsoft/playwright-python/issues/939](https://github.com/microsoft/playwright-python/issues/939)

**Comment by aslushnikov** [comment]
@re1oaded it's hard to say without being able to reproduce this locally. Can you share a repro that we can run locally to reproduce this?

**Comment by mxschmitt** [comment]
I wasn't able to reproduce. Can you maybe create a more minimal example without the use of the external schedule package?
