### ISSUE TITLE
[BUG] Playwright with Streamlit not working

### ISSUE THREAD

**Issue by baniasbaabe** [microsoft/playwright-python#1769]
When running Playwright with Streamlit, the following `NotImplementedError` occurs:

**Context:**
- Playwright Version: 1.30.0
- Operating System: Windows
- Python version: 3.8.10
- Browser: Chromium
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally.

```python
 with sync_playwright() as p:
                browser = p.chromium.launch(headless=True)
                page = browser.new_page()
                page.route("**/*", lambda route: route.abort()
                if route.request.resource_type == "image"
                else route.continue_()
                )
                page.goto(f"{self.url}{page_num}")


```

**Describe the bug**

Traceback (most recent call last):
  File "c:\code\amazon-scraper\venv\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "C:\Code\amazon-scraper\pages\1_Scraping.py", line 19, in <module>
    all_reviews = amz.parse()
  File "C:\Code\amazon-scraper\amazon_scrape.py", line 29, in parse
    with sync_playwright() as p:
  File "c:\code\amazon-scraper\venv\lib\site-packages\playwright\sync_api\_context_manager.py", line 88, in __enter__
    dispatcher_fiber.switch()
  File "c:\code\amazon-scraper\venv\lib\site-packages\playwright\sync_api\_context_manager.py", line 67, in greenlet_main
    self._loop.run_until_complete(self._connection.run_as_sync())
  File "C:\Users\.pyenv\pyenv-win\versions\3.8.10\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\code\amazon-scraper\venv\lib\site-packages\playwright\_impl\_connection.py", line 238, in run_as_sync
    await self.run()
  File "c:\code\amazon-scraper\venv\lib\site-packages\playwright\_impl\_connection.py", line 247, in run
    await self._transport.connect()
  File "c:\code\amazon-scraper\venv\lib\site-packages\playwright\_impl\_transport.py", line 127, in connect
    raise exc
  File "c:\code\amazon-scraper\venv\lib\site-packages\playwright\_impl\_transport.py", line 116, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Users\.pyenv\pyenv-win\versions\3.8.10\lib\asyncio\subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\Banias\.pyenv\pyenv-win\versions\3.8.10\lib\asyncio\base_events.py", line 1630, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\.pyenv\pyenv-win\versions\3.8.10\lib\asyncio\base_events.py", line 491, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError

**Comment by mxschmitt** [comment]
See https://github.com/microsoft/playwright-python/issues/1710#issuecomment-1372007370

Also this is not end-to-end related, so closing for now.
