### ISSUE TITLE
[BUG] Error starting playwright with await without async with

### ISSUE THREAD

**Issue by JCHacking** [microsoft/playwright-python#1791]
**Context:**
- Playwright Version: 1.31.0 and 1.31.1
- Operating System: Windows
- Python version: 3.11.2
- Browser: Any
- Extra: An

**Bug:**

When I run the following code, although it works, it throws some ignored errors
```python
import asyncio

from playwright.async_api import async_playwright


async def main():
    playwright = async_playwright()
    await playwright.start()

asyncio.run(main())
```
Output
```python
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001C3D4A21D00>
Traceback (most recent call last):
  File "C:\Python311\Lib\asyncio\proactor_events.py", line 116, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\proactor_events.py", line 80, in __repr__
    info.append(f'fd={self._sock.fileno()}')
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x000001C3D4A205E0>
Traceback (most recent call last):
  File "C:\Python311\Lib\asyncio\base_subprocess.py", line 125, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\base_subprocess.py", line 70, in __repr__
    info.append(f'stdin={stdin.pipe}')
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\proactor_events.py", line 80, in __repr__
    info.append(f'fd={self._sock.fileno()}')
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001C3D4A21D00>
Traceback (most recent call last):
  File "C:\Python311\Lib\asyncio\proactor_events.py", line 116, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\proactor_events.py", line 80, in __repr__
    info.append(f'fd={self._sock.fileno()}')
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe

Process finished with exit code 0
```

**Comment by mxschmitt** [comment]
You need to stop Playwright after you are done with it, otherwise you'll get such errors. The context manager is a great way of doing it, since it will do it automatically:

```python
import asyncio
from playwright.async_api import async_playwright

async def main():
    async with async_playwright() as p:
        browser = await p.chromium.launch()
        page = await browser.new_page()
        await page.goto("http://playwright.dev")
        print(await page.title())
        await browser.close()

asyncio.run(main())
```

or you use the REPL variant: 

```python
import asyncio

from playwright.async_api import async_playwright


async def main():
    playwright = await async_playwright().start()
    # do stuff...
    await playwright.stop()

asyncio.run(main())
```

**Comment by mxschmitt** [comment]
Closing as per above, for further questions please re-file.
