### ISSUE TITLE
Cannot Run Playwright Script (error)

### ISSUE THREAD

**Issue by transcendr** [microsoft/playwright-python#1855]
### Your question

Mac 11.8 
Python 3.10.11 (via pyenv)

`pip3 install playwright` works and I can run playwright from the command line (eg, `playwright codegen` works) but when I try to run a script `python3 ./playtest.py` I get the following error:

```
Traceback (most recent call last):
  File "[path]/./playtest.py", line 1, in <module>
    from playwright.sync_api import Playwright, sync_playwright, expect
  File "[path]/.pyenv/versions/3.10.11/lib/python3.10/site-packages/playwright/sync_api/__init__.py", line 25, in <module>
    import playwright.sync_api._generated
  File "[path]/.pyenv/versions/3.10.11/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 25, in <module>
    from playwright._impl._accessibility import Accessibility as AccessibilityImpl
  File "[path]/.pyenv/versions/3.10.11/lib/python3.10/site-packages/playwright/_impl/_accessibility.py", line 17, in <module>
    from playwright._impl._connection import Channel
  File "[path]/.pyenv/versions/3.10.11/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 34, in <module>
    from greenlet import greenlet
  File "[path]/.pyenv/versions/3.10.11/lib/python3.10/site-packages/greenlet/__init__.py", line 29, in <module>
    from ._greenlet import _C_API # pylint:disable=no-name-in-module
ImportError: dlopen([path]pyenv/versions/3.10.11/lib/python3.10/site-packages/greenlet/_greenlet.cpython-310-darwin.so, 2): Symbol not found: __ZSt20__throw_length_errorPKc
  Referenced from: [path]/.pyenv/versions/3.10.11/lib/python3.10/site-packages/greenlet/_greenlet.cpython-310-darwin.so
  Expected in: flat namespace
 in /[path]/.pyenv/versions/3.10.11/lib/python3.10/site-packages/greenlet/_greenlet.cpython-310-darwin.so

```

After hours of troubleshooting I guess it has something to do with greenlet.  I have tried uinstalling and installing it.  I have tried also installing playwright locally.  Any ideas?

Thanks.

btw, script is here:

```
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=True)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://github.com/")
    page.get_by_placeholder("Search GitHub").click()
    page.get_by_placeholder("Search GitHub").fill("gpt-4")
    page.get_by_placeholder("Search GitHub").press("Enter")

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
```

**Comment by mxschmitt** [comment]
What output does executing the following command give you? `file "$(pyenv which python)"` 

This looks like a greenlet issue and not like a Playwright issue. My suspect is that you have Python amd installed on a arm64 machine and its emulating via rosetta.

**Comment by feliche93** [comment]
@transcendr @mxschmitt, I got it working with `greenlet==2.0.1` and `Python 3.8.16` on Mac M1: https://github.com/python-greenlet/greenlet/issues/352#issuecomment-1516147084
