### ISSUE TITLE
[BUG] Can't open an frefox personal executable

### ISSUE THREAD

**Issue by javierfh03** [microsoft/playwright-python#1875]
**Context:**
- Playwright Version: 1.31.0
- Operating System: Windows 10
- Python version: 3.11
- Browser: Firefox 112
- Extra: I use vscodium, i don't use vent and the firefox version is 112

**Code Snippet**

```python
with sync_playwright() as p:
    browser = p.firefox.launch(executable_path=r"C:\Users\user\AppData\Local\Mozilla Firefox\firefox.exe", headless=False, slow_mo=50)
    context = browser.new_context()
    page = context.new_page()

    page.goto("https://www.google.com")

    time.sleep(5)
    browser.close()
```

**Describe the bug**
When I start firefox with a personal executable (in my case firefox 112) it does not start and I get the error that the browser is closed:

```
    Traceback (most recent call last):
  File "c:\Users\user\Source\caharreos\playwriht\pruebainternaltools.py", line 18, in <module>
    browser = p.firefox.launch(executable_path=r"C:\Users\user\AppData\Local\Mozilla Firefox\firefox.exe", headless=False, slow_mo=50)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\sync_api\_generated.py", line 14445, in launch
    self._sync(
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_sync_base.py", line 104, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_browser_type.py", line 93, in launch
    Browser, from_channel(await self._channel.send("launch", params))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_connection.py", line 419, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._api_types.Error: Browser.enable): Browser closed.
==================== Browser output: ====================
<launching> C:\Users\user\AppData\Local\Mozilla Firefox\firefox.exe -no-remote -wait-for-browser -foreground -profile C:\Users\user\AppData\Local\Temp\playwright_firefoxdev_profile-ktn9X1 -juggler-pipe -silent
<launched> pid=18820
[pid=18820] <process did exit: exitCode=0, signal=null>
[pid=18820] starting temporary directories cleanup
=========================== logs ===========================
<launching> C:\Users\user\AppData\Local\Mozilla Firefox\firefox.exe -no-remote -wait-for-browser -foreground -profile C:\Users\user\AppData\Local\Temp\playwright_firefoxdev_profile-ktn9X1 -juggler-pipe -silent
<launched> pid=18820
[pid=18820] <process did exit: exitCode=0, signal=null>
[pid=18820] starting temporary directories cleanup
============================================================
```
To start chrome I use the same code but starting the browser as if it were chrome. I tried with another firefox executable but it didn't work either. I also tried on another computer but it doesn't work even with that. Maybe it's not a bug and I'm just using the wrong library...

**Comment by javierfh03** [comment]
Okey, and out of curiosity, one day playwright can use personal firefox executable?
