### ISSUE TITLE
[BUG] playwright._impl._api_types.Error: headers: expected array, got object

### ISSUE THREAD

**Issue by blv-matheuslins** [microsoft/playwright-python#1910]
**Context:**
- Playwright Version: `v1.33.0`
- Operating System: `Linux`
- Python version: `3.10`
- Browser: `Chromium`

**Code Snippet**

```python
if __name__ == "__main__":
    import asyncio
    from playwright.async_api import async_playwright


    async def main():
        async with async_playwright() as p:
                headers = {'User-Agent': "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/88.0.4324.96 Chrome/88.0.4324.96 Safari/537.36"}
                browser = await p.chromium.connect_over_cdp("http://whatsmyuseragent.org/", headers=headers)
                page = await browser.new_page()
                await page.goto('http://whatsmyuseragent.org/')
                await browser.close()


    asyncio.run(main())
```

**Describe the bug**

I'm facing this error with a simple script only trying to create a connection with cdp.

**Traceback**
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File ".config/JetBrains/PyCharmCE2023.1/scratches/playwright_connection.py", line 11, in main
    browser = await p.chromium.connect_over_cdp("http://whatsmyuseragent.org/", headers=headers)
  File "/venv/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 14829, in connect_over_cdp
    await self._impl_obj.connect_over_cdp(
  File "/venv/lib/python3.10/site-packages/playwright/_impl/_browser_type.py", line 168, in connect_over_cdp
    response = await self._channel.send_return_as_dict("connectOverCDP", params)
  File "/venv/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 66, in send_return_as_dict
    return await self._connection.wrap_api_call(
  File "/venv/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 461, in wrap_api_call
    return await cb()
  File "/venv/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: headers: expected array, got object

Process finished with exit code 1
```

**Comment by mxschmitt** [comment]
Thanks for the repro! While this is a bug in Playwright which gets fixed in the next release, this most likely does not end up doing what you want. It just sets the user-agent for the websocket connection which gets established from your local computer to the CDP endpoint. It does NOT set this header for requests made in the browser.

**Comment by blv-matheuslins** [comment]
Hey @mxschmitt thanks for the answer!

The `User-Agent` just was an example to show you the bug, but what I really want is to connect to the CDP endpoint by passing an `Authorization` header, like: `browser = playwright.chromium.connect_over_cdp(browser_url, headers={'Authorization': f'Bearer {my_token}'})`

Even though, thanks for the tip, I also will need the user agent ;)
