### ISSUE TITLE
How to install behind proxy?

### ISSUE THREAD

**Issue by LeMoussel** [microsoft/playwright-python#193]
Is it possible to install `playwright-python ` behind proxy?

With the use of a proxy , I got this error:
```
PS D:\Python\PlaywrightTest> python -m playwright install
Installing the browsers...
(node:26748) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT ......
```

Rem: HTTP_PROXY environment variable is set.

**Comment by mxschmitt** [comment]
@LeMoussel do you still face this issue? I took a look in the codebase, there it should work. But if not, then I would try to setup a proxy to reproduce it on my machine.

**Comment by LeMoussel** [comment]
Yes I am still face with this problem. 
I use Windows 10 & PowerShell
```
PS D:\Python\PlaywrightTest> $env:HTTP_PROXY='http://MyproxyWeb.fr:3128'
PS D:\Python\PlaywrightTest> $env:HTTP_PROXY
http://http://MyproxyWeb.fr:3128
PS D:\Python\PlaywrightTest>python -m playwright install
```
Got this error:
```

Installing the browsers...
(node:9348) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT 13.107.246.10:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
(node:9348) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9348) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Traceback (most recent call last):
  File "C:\Users\Test\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Test\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Test\AppData\Local\Programs\Python\Python37\lib\site-packages\playwright\__main__.py", line 17, in <module>
    main()
  File "C:\Users\Test\AppData\Local\Programs\Python\Python37\lib\site-packages\playwright\main.py", line 141, in main
    subprocess.check_call(f"{driver_executable} install", shell=True)
  File "C:\Users\Test\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\Users\Test\AppData\Local\Programs\Python\Python37\lib\site-packages\playwright\drivers\driver-win.exe install' returned non-zero exit status 1.

```

But I think this error is not playwright because I don't have an answer with `ping 13.107.246.10` either.

**Comment by Stastr87** [comment]
Hello! Heve you any solution for this question?
