### ISSUE TITLE
Handle page.on events is impossible.

### ISSUE THREAD

**Issue by KevinEdry** [microsoft/playwright-python#194]
Hey, 
I recently started using playwright, I am trying to listen to page responses and monitor them.
```
async def main():
    async with async_playwright() as p:
        browser = await p.chromium.launch()
        page = await browser.newPage()
        page.on('response', lambda response: asyncio.create_task(request_event_handler(response)))
        await page.goto('https://randomwebsite.com/', 0, 'networkidle')
        await browser.close()
```

All is good so far, the "page.on" event listener works well, but when I am trying to parse the body of the response like so
```
async def request_event_handler(response):
    if "randomstring" in response.url:
        body = asyncio.create_task(response.body())
        print(body)
```

I get an error message stating that "Task exception was never retrieved".
full error message:
```
Task exception was never retrieved
future: <Task finished name='Task-29' coro=<request_event_handler() done, defined at run.py:18> exception=Error('Protocol error (Network.getResponseBody): No resource with given identifier found')>
Traceback (most recent call last):
  File "run.py", line 20, in request_event_handler
    body = await response.body()
  File "/usr/local/lib/python3.8/site-packages/playwright/async_api.py", line 338, in body
    return mapping.from_maybe_impl(await self._impl_obj.body())
  File "/usr/local/lib/python3.8/site-packages/playwright/network.py", line 213, in body
    binary = await self._channel.send("body")
  File "/usr/local/lib/python3.8/site-packages/playwright/connection.py", line 39, in send
    result = await callback.future
playwright.helper.Error: Protocol error (Network.getResponseBody): No resource with given identifier found
```

How can I handle the response.body() awaitable?

**Comment by LeMoussel** [comment]
Hi,

Do `body = await response.body()`

**Example:**
```
import asyncio
from playwright import async_playwright

async def request_event_handler(response):
    print('HTTP Status code: {}'.format(response.status))
    body = await response.body()
    print('HTML body page: {}'.format(body))

async def main():
    async with async_playwright() as p:
        browser = await p.chromium.launch(
            headless=False,
            executablePath='C:/Program Files/Google/Chrome/Application/chrome.exe'
        )
        context = await browser.newContext()
        page = await context.newPage()
        page.on('response', lambda response: asyncio.create_task(request_event_handler(response)))
        await page.goto('http://example.com/', 0, 'networkidle')
        await browser.close()

asyncio.get_event_loop().run_until_complete(main())

```

**Comment by mxschmitt** [comment]
I tried the example myself and it works. What is the reason that you want to specify your own Chrome executable?

```
import asyncio
from playwright import async_playwright


async def request_event_handler(response):
    print("HTTP Status code: {}".format(response.status))
    body = await response.body()
    print("HTML body page: {}".format(body))


async def main():
    async with async_playwright() as p:
        browser = await p.chromium.launch()
        context = await browser.newContext()
        page = await context.newPage()
        page.on(
            "response",
            lambda response: asyncio.create_task(request_event_handler(response)),
        )
        await page.goto("http://example.com/", 0, "networkidle")
        await browser.close()


asyncio.get_event_loop().run_until_complete(main())

```

**Comment by LeMoussel** [comment]
The reason is I work behind a proxy and I got error when I do `playwright install`. See #193

I think it would be better to use 'requestfinished' event.  '[requestfinished](https://github.com/microsoft/playwright/blob/master/docs/api.md#event-requestfinished)' emitted when the response body is downloaded and the request is complete.

**Comment by mxschmitt** [comment]
Playwright accepts to pass a proxy which will get forwarded to the browsers see here: https://playwright.dev/#version=v1.4.1&path=docs%2Fapi.md&q=browsertypelaunchoptions--options-proxy

For Python its in the end a dictionary on the launch call.

That should maybe fix your issue.

**Comment by LeMoussel** [comment]
Yep! I do this. It's OK 
```
        browser = await p.chromium.launch(
            headless=False,
            executablePath='C:/Program Files/Google/Chrome/Application/chrome.exe',
            proxy={ "server": 'http://proxy-example:1234' }
        )
```
But for `playwright install`  I don't know how to specify the use of a proxy

**Comment by mxschmitt** [comment]
For playwright install it should automatically detect it from the env variables
