### ISSUE TITLE
[BUG] Issue with HTTP headers 

### ISSUE THREAD

**Issue by Rafiot** [microsoft/playwright-python#1943]
**Context:**
- Playwright Version: 1.34.0 (but it was an issue with older versions too)
- Operating System: Linux
- Python version: 3.8+
- Browser: Chromium, for sure, not certain for the other ones.

**Code Snippet**

Sorry, I cannot provide you with one because the issue seems to occur after a while, but I'm very much interested in debugging it.

**Describe the bug**

After a while and when running many thousands of captures with playwright (using [this module](https://github.com/Lookyloo/PlaywrightCapture)), I may end-up in a situation where the following exception is raised:

```
2023-05-29 00:03:58,730 playwrightcapture ERROR:Something went poorly with https://laposte.net: Protocol error (Network.setExtraHTTPHeaders): Invalid header name
Traceback (most recent call last):
  File "/home/raphael/.cache/pypoetry/virtualenvs/lacus-rX9D753U-py3.8/lib/python3.8/site-packages/playwrightcapture/capture.py", line 429, in capture_page
    page = await self.context.new_page()
  File "/home/raphael/.cache/pypoetry/virtualenvs/lacus-rX9D753U-py3.8/lib/python3.8/site-packages/playwright/async_api/_generated.py", line 12988, in new_page
    return mapping.from_impl(await self._impl_obj.new_page())
  File "/home/raphael/.cache/pypoetry/virtualenvs/lacus-rX9D753U-py3.8/lib/python3.8/site-packages/playwright/_impl/_browser_context.py", line 264, in new_page
    return from_channel(await self._channel.send("newPage"))
  File "/home/raphael/.cache/pypoetry/virtualenvs/lacus-rX9D753U-py3.8/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "/home/raphael/.cache/pypoetry/virtualenvs/lacus-rX9D753U-py3.8/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 482, in wrap_api_call
    return await cb()
  File "/home/raphael/.cache/pypoetry/virtualenvs/lacus-rX9D753U-py3.8/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Protocol error (Network.setExtraHTTPHeaders): Invalid header name
```

The capture raising this exception *doesn't* set any specific HTTP header but I suspect another one did and it somehow broke the complete environment (for a lack of better term, I'm not sure how to call it). But the "fix" in my case it to stop the long running process that manages the captures and restart it.

If you have any hints on how I can debug it efficiently to give you the proper information you need to fix it, please let me know, as I have no idea where to start from.

My very uneducated guess is that the [browser_context.set_extra_http_header](https://playwright.dev/python/docs/api/class-browsercontext#browser-context-set-extra-http-headers) doesn't properly sanitize some headers and it somehow breaks something.

**Comment by mxschmitt** [comment]
Some general ideas how to debug this:

- Print the headers which get logged, then you see in the logs which headers were sent, most likely around [here](https://github.com/Lookyloo/PlaywrightCapture/blob/v1.19.16/playwrightcapture/capture.py#L250).
- Find out why they were not the expected ones

Two possible outcomes, either that there is a bug on our side then (for that we need a minimal reproduction) or that incorrect headers are passed from your side, e.g. an unexpected data structure.

I'll keep it open for a bit while you are debugging it!

**Comment by Rafiot** [comment]
Alright, I'll dig into that. The issue is that I have thousands of captures per day, and at some point one of them makes it barf. It happens after an arbitrary amount of time, making it hard to pinpoint. 

I'll add some logging to just keep track of all the headers and hopefully it will be obvious in the next few days.

**Comment by Rafiot** [comment]
Alright, update on that: Once set, I was mistakenly keeping the HTTP headers across captures. That explains the issue with all the subsequent captures being broken.

I'll get back to you as soon as find an example of HTTP Header chrome doesn't like.
