### ISSUE TITLE
Webkit manifests different errors on Playwright 1.33 python version.

### ISSUE THREAD

**Issue by RomanLeca** [microsoft/playwright-python#1950]
**Context:**
- Playwright Version: [1.33]
- Operating System: [Mac OS Ventura 13.4]
- Python version: [3.8]
- Browser: [WebKit]
- Extra: [playwright sync api + pytest]

**Code Snippet**
```python

import json
from typing import List, Dict, Callable, Any
from playwright.sync_api import Route, Request, Page, expect


def capture_requests(page: Page, desired_substring: str) -> Callable[[], List[Dict[str, str]]]:
    """
    Captures all requests on a given page where the URL contains a desired substring.

    page: The playwright page object where the requests are taking place.
    desired_substring: The substring to look for in the URL of the requests.

    Returns:
        A function that, when called, removes the route that was set up, and returns the captured requests.
    """
    # Create a list to hold the captured requests
    captured_requests = []

    def log_and_continue(route: Route, request: Request) -> None:
        """
        Called for each request that matches the route.
        Captures the request if the desired_substring is in the request's URL.
        """
        if desired_substring in request.url:
            captured_requests.append({
                'url': request.url,
                'payload': request.post_data  # capture the payload
            })
        route.continue_()

    def remove_route_and_get_requests() -> List[Dict[str, str]]:
        """
        Removes the route that was set up on the page.
        Returns the captured requests.
        """
        page.unroute('**', log_and_continue)
        return captured_requests

    page.route('**', log_and_continue)
    return remove_route_and_get_requests


def get_events_data(data: List[Dict[str, Any]], field: str) -> List:
    """
    Extracts a specific field's values from the payload in each dictionary in the provided list.

    Args:
        data: A list of events each containing a 'payload' key.
        field: The field to be extracted from each event.

    Returns:
        A list of 'field' values from all events in all payloads.
    """
    event_data = []
    for item in data:
        payload = json.loads(item['payload'])
        for event in payload:
            if field in event:
                event_data.append(event[field])
    return event_data


def test_bug1(page):
    get_captured_requests = capture_requests(page, '/b/')
    page.goto("https://reachmd.com/")
    page.get_by_role("banner").get_by_role("link", name="Register").click()
    page.get_by_placeholder("First Name*").fill("playwright")
    page.get_by_placeholder("Last Name*").fill("playwright")
    page.get_by_placeholder("Email*", exact=True).fill("play1234@wright.pw")  # has to be unique
    page.get_by_placeholder("Confirm Email*").fill("play1234@wright.pw")  # has to match
    page.get_by_placeholder("Password*", exact=True).fill("Playwright123")
    page.get_by_placeholder("Confirm Password*").fill("Playwright123")
    page.locator('span[title="Profession"], select[name="Profession"]').click()
    page.get_by_role("treeitem", name="Physician", exact=True).click()
    page.locator('span[title="Specialty"], select[name="Specialty"]').click()
    page.get_by_role("treeitem", name="Allergy", exact=True).click()
    try:
        page.get_by_role("button", name="I Accept").click(timeout=1000)
    except:
        pass
    page.locator("#select2-id_country-container").click()
    page.get_by_role("treeitem", name="Rwanda").click()
    page.evaluate('document.querySelector("input[type=\'checkbox\'][data-required=\'required\']").click()')
    page.get_by_role("button", name="Register").click()  # this line will register a new account
    # collect events and check the necessary ones
    captured_requests = get_captured_requests()
    all_events = get_events_data(captured_requests, field='event_type')
    assert 190 in all_events
    assert 191 in all_events


def test_bug2(page):
    get_captured_requests = capture_requests(page, '/b/')
    page.goto("https://omniaeducation.com")
    page.get_by_role("link", name="Create an Account").click()
    page.get_by_placeholder("First Name*").fill("playwright")
    page.get_by_placeholder("Last Name*").fill("playwright")
    page.get_by_placeholder("Email*", exact=True).fill("play1234@wright.pw")  # has to be unique
    page.get_by_placeholder("Confirm Email*").fill("play1234@wright.pw") # has to match
    page.get_by_placeholder("Password*", exact=True).fill("Playwright123")
    page.get_by_placeholder("Confirm Password*").fill("Playwright123")
    page.locator('span[title="Profession"], select[name="Profession"]').click()
    page.get_by_role("treeitem", name="Physician", exact=True).click()
    page.locator('span[title="Specialty"], select[name="Specialty"]').click()
    page.get_by_role("treeitem", name="Allergy", exact=True).click()
    try:
        page.get_by_role("button", name="I Accept").click(timeout=1000)
    except:
        pass
    page.locator("#select2-id_country-container").click()
    page.get_by_role("treeitem", name="Rwanda").click()
    page.evaluate('document.querySelector("input[type=\'checkbox\'][data-required=\'required\']").click()')
    page.locator('button:has-text("Create an Account"), button:has-text("Register")').first.click()  # this line will register a new account
    expect(page.get_by_role("link", name="Log out").first).to_be_visible()

    # collect events and check the necessary ones
    captured_requests = get_captured_requests()
    all_events = get_events_data(captured_requests, field='event_type')
    assert 190 in all_events
    assert 191 in all_events

```

**Describe the bug**

***First test fails with wait for load:***
```
_______________________________________________________________________________________________ test_bug1[webkit] ________________________________________________________________________________________________

page = <Page url='https://reachmd.com/'>

    def test_bug1(page):
        """This test fails with wait for load state"""
    
        get_captured_requests = capture_requests(page, '/b/')
>       page.goto("https://reachmd.com/")

tests/pw/test_bug.py:67: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
venv/lib/python3.8/site-packages/playwright/sync_api/_generated.py:9256: in goto
    self._sync(
venv/lib/python3.8/site-packages/playwright/_impl/_page.py:495: in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
venv/lib/python3.8/site-packages/playwright/_impl/_frame.py:147: in goto
    await self._channel.send("goto", locals_to_params(locals()))
venv/lib/python3.8/site-packages/playwright/_impl/_connection.py:61: in send
    return await self._connection.wrap_api_call(
venv/lib/python3.8/site-packages/playwright/_impl/_connection.py:461: in wrap_api_call
    return await cb()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <playwright._impl._connection.Channel object at 0x7fb1a1391a30>, method = 'goto', params = {'url': 'https://reachmd.com/'}, return_as_dict = False

    async def inner_send(
        self, method: str, params: Optional[Dict], return_as_dict: bool
    ) -> Any:
        if params is None:
            params = {}
        callback = self._connection._send_message_to_server(self._guid, method, params)
        if self._connection._error:
            error = self._connection._error
            self._connection._error = None
            raise error
        done, _ = await asyncio.wait(
            {
                self._connection._transport.on_error_future,
                callback.future,
            },
            return_when=asyncio.FIRST_COMPLETED,
        )
        if not callback.future.done():
            callback.future.cancel()
>       result = next(iter(done)).result()
E       playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
E       =========================== logs ===========================
E       navigating to "https://reachmd.com/", waiting until "load"
E       ============================================================

venv/lib/python3.8/site-packages/playwright/_impl/_connection.py:96: TimeoutError
============================================================================================ short test summary info =============================================================================================
FAILED tests/pw/test_bug.py::test_bug1[webkit] - playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
```

***Second test fails with a coroutine issue:***
```
tests/pw/test_bug.py::test_bug2[webkit]
  /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py:641: RuntimeWarning: coroutine 'Connection.wrap_api_call' was never awaited
    self._ready.clear()
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================================================================ short test summary info =============================================================================================
FAILED tests/pw/test_bug.py::test_bug2[webkit] - assert 191 in [27, 2, 900, 190]
```

**Comment by mxschmitt** [comment]
Turns out these are two issues, one I extracted to  and the other, see here for dedicated logs: https://github.com/microsoft/playwright/issues/23574

```
(env) ➜  playwright-python git:(main) ✗ pytest --browser=webkit --headed tests/sync/test_page.py
================================================================= test session starts ==================================================================
platform darwin -- Python 3.11.2, pytest-7.2.1, pluggy-1.0.0 -- /Users/maxschmitt/Developer/playwright-python/env/bin/python
cachedir: .pytest_cache
rootdir: /Users/maxschmitt/Developer/playwright-python, configfile: pyproject.toml
plugins: asyncio-0.20.3, xdist-3.1.0, flaky-3.7.0, timeout-2.1.0, cov-4.0.0, repeat-0.9.1
asyncio: mode=Mode.AUTO
collected 1 item                                                                                                                                       

tests/sync/test_page.py::test_bug1[webkit] PASSED

=================================================================== warnings summary ===================================================================
env/lib/python3.11/site-packages/twisted/web/http.py:103
  /Users/maxschmitt/Developer/playwright-python/env/lib/python3.11/site-packages/twisted/web/http.py:103: DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
    import cgi

tests/sync/test_page.py::test_bug1[webkit]
  /Users/maxschmitt/.pyenv/versions/3.11.2/lib/python3.11/asyncio/base_events.py:678: RuntimeWarning: coroutine 'Connection.wrap_api_call' was never awaited
    self._ready.clear()
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================================ 1 passed, 2 warnings in 12.10s ============================================================
Future exception was never retrieved
future: <Future finished exception=Error('Connection closed')>
playwright._impl._api_types.Error: Connection closed
Future exception was never retrieved
future: <Future finished exception=Error('Connection closed')>
playwright._impl._api_types.Error: Connection closed
Future exception was never retrieved
future: <Future finished exception=Error('Connection closed')>
playwright._impl._api_types.Error: Connection closed
Future exception was never retrieved
future: <Future finished exception=Error('Connection closed')>
playwright._impl._api_types.Error: Connection closed
Task was destroyed but it is pending!
task: <Task cancelling name='Task-341' coro=<Page._on_route() running at /Users/maxschmitt/Developer/playwright-python/playwright/_impl/_page.py:259> wait_for=<_GatheringFuture finished exception=CancelledError()>>
Task was destroyed but it is pending!
task: <Task cancelling name='Task-343' coro=<Page._on_route() running at /Users/maxschmitt/Developer/playwright-python/playwright/_impl/_page.py:259> wait_for=<_GatheringFuture finished exception=CancelledError()>>
_GatheringFuture exception was never retrieved
future: <_GatheringFuture finished exception=CancelledError()>
Traceback (most recent call last):
  File "/Users/maxschmitt/Developer/playwright-python/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maxschmitt/Developer/playwright-python/playwright/_impl/_connection.py", line 477, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "/Users/maxschmitt/Developer/playwright-python/playwright/_impl/_connection.py", line 88, in inner_send
    done, _ = await asyncio.wait(
              ^^^^^^^^^^^^^^^^^^^
  File "/Users/maxschmitt/.pyenv/versions/3.11.2/lib/python3.11/asyncio/tasks.py", line 418, in wait
    return await _wait(fs, timeout, return_when, loop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maxschmitt/.pyenv/versions/3.11.2/lib/python3.11/asyncio/tasks.py", line 525, in _wait
    await waiter
asyncio.exceptions.CancelledError
_GatheringFuture exception was never retrieved
future: <_GatheringFuture finished exception=CancelledError()>
Traceback (most recent call last):
  File "/Users/maxschmitt/Developer/playwright-python/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maxschmitt/Developer/playwright-python/playwright/_impl/_connection.py", line 477, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "/Users/maxschmitt/Developer/playwright-python/playwright/_impl/_connection.py", line 88, in inner_send
    done, _ = await asyncio.wait(
              ^^^^^^^^^^^^^^^^^^^
  File "/Users/maxschmitt/.pyenv/versions/3.11.2/lib/python3.11/asyncio/tasks.py", line 418, in wait
    return await _wait(fs, timeout, return_when, loop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maxschmitt/.pyenv/versions/3.11.2/lib/python3.11/asyncio/tasks.py", line 525, in _wait
    await waiter
asyncio.exceptions.CancelledError
_GatheringFuture exception was never retrieved
future: <_GatheringFuture finished exception=CancelledError()>
Traceback (most recent call last):
  File "/Users/maxschmitt/Developer/playwright-python/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maxschmitt/Developer/playwright-python/playwright/_impl/_connection.py", line 477, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "/Users/maxschmitt/Developer/playwright-python/playwright/_impl/_connection.py", line 88, in inner_send
    done, _ = await asyncio.wait(
              ^^^^^^^^^^^^^^^^^^^
  File "/Users/maxschmitt/.pyenv/versions/3.11.2/lib/python3.11/asyncio/tasks.py", line 418, in wait
    return await _wait(fs, timeout, return_when, loop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maxschmitt/.pyenv/versions/3.11.2/lib/python3.11/asyncio/tasks.py", line 525, in _wait
    await waiter
asyncio.exceptions.CancelledError
Task was destroyed but it is pending!
task: <Task cancelling name='Task-339' coro=<Page._on_route() running at /Users/maxschmitt/Developer/playwright-python/playwright/_impl/_page.py:259> wait_for=<_GatheringFuture finished exception=CancelledError()>>
_GatheringFuture exception was never retrieved
future: <_GatheringFuture finished exception=CancelledError()>
Traceback (most recent call last):
  File "/Users/maxschmitt/Developer/playwright-python/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maxschmitt/Developer/playwright-python/playwright/_impl/_connection.py", line 477, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "/Users/maxschmitt/Developer/playwright-python/playwright/_impl/_connection.py", line 88, in inner_send
    done, _ = await asyncio.wait(
              ^^^^^^^^^^^^^^^^^^^
  File "/Users/maxschmitt/.pyenv/versions/3.11.2/lib/python3.11/asyncio/tasks.py", line 418, in wait
    return await _wait(fs, timeout, return_when, loop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maxschmitt/.pyenv/versions/3.11.2/lib/python3.11/asyncio/tasks.py", line 525, in _wait
    await waiter
asyncio.exceptions.CancelledError
Task was destroyed but it is pending!
task: <Task cancelling name='Task-345' coro=<Page._on_route() running at /Users/maxschmitt/Developer/playwright-python/playwright/_impl/_page.py:259> wait_for=<_GatheringFuture finished exception=CancelledError()>>
```

**Comment by mxschmitt** [comment]
Looks passing if we consider the WebKit issue in https://github.com/microsoft/playwright/issues/23574. Changing it to this works:

```
    page.goto("https://reachmd.com/", wait_until="commit")

```
