### ISSUE TITLE
[Question]: TypeError: Object of type Proxy is not JSON serializable

### ISSUE THREAD

**Issue by wanghaisheng** [microsoft/playwright-python#1958]
### Your question

```
self locale is:en-US
self.proxy.longitude:-118.235
self.proxy.latitude:34.0581
self.proxy.timezone:America/Los_Angeles
self.proxy.useragent:Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0       
self.proxy.storage_state_path:None
self.proxy.timezone:None
self.proxy.timezone:None
Traceback (most recent call last):
  File "D:\Download\audio-visual\saas\tiktoka\tiktoka-studio-uploader\examples\botcheck.py", line 337, in <module>
    asyncio.run(main())
  File "D:\Programs\anaconda\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Programs\anaconda\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "D:\Download\audio-visual\saas\tiktoka\tiktoka-studio-uploader\examples\botcheck.py", line 310, in main
    pl = await PlaywrightAsyncDriverStealth.create(
  File "D:\Programs\anaconda\lib\site-packages\tsup-0.1.16-py3.9.egg\tsup\utils\webdriver\playwright_driver_async_stealth.py", line 200, in create
    await self._setup()
  File "D:\Programs\anaconda\lib\site-packages\tsup-0.1.16-py3.9.egg\tsup\utils\webdriver\playwright_driver_async_stealth.py", line 131, in _setup
    browser = await self.browser.new_context(
  File "D:\Programs\anaconda\lib\site-packages\playwright\async_api\_generated.py", line 13974, in new_context
    await self._impl_obj.new_context(
  File "D:\Programs\anaconda\lib\site-packages\playwright\_impl\_browser.py", line 126, in new_context      
    channel = await self._channel.send("newContext", params)
  File "D:\Programs\anaconda\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "D:\Programs\anaconda\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call 
    return await cb()
  File "D:\Programs\anaconda\lib\site-packages\playwright\_impl\_connection.py", line 82, in inner_send     
    callback = self._connection._send_message_to_server(self._guid, method, params)
  File "D:\Programs\anaconda\lib\site-packages\playwright\_impl\_connection.py", line 333, in _send_message_to_server
    self._transport.send(message)
  File "D:\Programs\anaconda\lib\site-packages\playwright\_impl\_transport.py", line 169, in send
    data = self.serialize_message(message)
  File "D:\Programs\anaconda\lib\site-packages\playwright\_impl\_transport.py", line 78, in serialize_message
    msg = json.dumps(message)
  File "D:\Programs\anaconda\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "D:\Programs\anaconda\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\Programs\anaconda\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\Programs\anaconda\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Proxy is not JSON serializable
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x0000020531457430>
Traceback (most recent call last):
  File "D:\Programs\anaconda\lib\asyncio\base_subprocess.py", line 126, in __del__
  File "D:\Programs\anaconda\lib\asyncio\base_subprocess.py", line 104, in close
  File "D:\Programs\anaconda\lib\asyncio\proactor_events.py", line 108, in close
  File "D:\Programs\anaconda\lib\asyncio\base_events.py", line 751, in call_soon
  File "D:\Programs\anaconda\lib\asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000020531458C10>
Traceback (most recent call last):
  File "D:\Programs\anaconda\lib\asyncio\proactor_events.py", line 116, in __del__
  File "D:\Programs\anaconda\lib\asyncio\proactor_events.py", line 108, in close
  File "D:\Programs\anaconda\lib\asyncio\base_events.py", line 751, in call_soon
  File "D:\Programs\anaconda\lib\asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed
```

code 
```
        print(f"self locale is:{self.faker.locale}")
        # Context for more options
        print(f"self.proxy.longitude:{self.proxy.longitude}")
        print(f"self.proxy.latitude:{self.proxy.latitude}")
        print(f"self.proxy.timezone:{self.proxy.timezone}")
        print(f"self.proxy.useragent:{self.faker.useragent}")
        print(f"self.proxy.storage_state_path:{self.storage_state_path}")
        print(f"self.proxy.timezone:{self.proxy.username}")
        print(f"self.proxy.timezone:{self.proxy.password}")

        browser = await self.browser.new_context(
            locale=self.faker.locale,  # self.faker.locale
            geolocation={
                "longitude": self.proxy.longitude,
                "latitude": self.proxy.latitude,
                "accuracy": 0.7,
            },
            timezone_id=self.proxy.timezone,
            permissions=["geolocation"],
            # screen={"width": self.faker.avail_width, "height": self.faker.avail_height},
            user_agent=self.faker.useragent,
            no_viewport=True,
            # viewport={"width": self.faker.width, "height": self.faker.height},
            proxy=self.proxy,
            storage_state=self.storage_state_path if self._isRecodingVideo else None,
            record_video_dir=os.getcwd() + os.sep + "screen-recording"
            if self._isRecodingVideo
            else None,
            http_credentials={
                "username": self.proxy.username,
                "password": self.proxy.password,
            }
            if self.proxy.username
            else None,
        )
```

**Comment by mxschmitt** [comment]
`proxy=self.proxy,` this seems wrong, make sure to only pass there a dict, see here: https://playwright.dev/python/docs/api/class-browser#browser-new-context-option-proxy

**Comment by wanghaisheng** [comment]
I  print everyone ,and at last I find this proxy format is a dict instead of string 
thanks quick  response@mxschmitt
