### ISSUE TITLE
[Question]: how to avoid playwright._impl._api_types.Error: Target page, context or browser has been closed

### ISSUE THREAD

**Issue by wanghaisheng** [microsoft/playwright-python#1987]
### Your question

raw pl with async_stealth
Traceback (most recent call last):
  File "/__w/validate-your-proxy-against-ip-leak/validate-your-proxy-against-ip-leak/tiktoka-studio-uploader/examples/botcheck.py", line 585, in <module>
    asyncio.run(main())
  File "/__t/Python/3.10.12/x64/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/__t/Python/3.10.12/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/__w/validate-your-proxy-against-ip-leak/validate-your-proxy-against-ip-leak/tiktoka-studio-uploader/examples/botcheck.py", line 528, in main
    await async_stealth(pl.page, pure=True)
  File "/__t/Python/3.10.12/x64/lib/python3.10/site-packages/cf_clearance/stealth.py", line 100, in async_stealth
    await page_or_context.add_init_script(script)
  File "/__t/Python/3.10.12/x64/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 9666, in add_init_script
    await self._impl_obj.add_init_script(script=script, path=path)
  File "/__t/Python/3.10.12/x64/lib/python3.10/site-packages/playwright/_impl/_page.py", line 588, in add_init_script
    await self._channel.send("addInitScript", dict(source=script))
  File "/__t/Python/3.10.12/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "/__t/Python/3.10.12/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 461, in wrap_api_call
    return await cb()
  File "/__t/Python/3.10.12/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target page, context or browser has been closed

**Comment by wanghaisheng** [comment]
proxy_option=None
    pl = await PlaywrightAsyncDriverStealth.create(
        proxy=proxy_option,
        driver_type="firefox",
        timeout=300,
#         headless=False,
#         for github action
        headless=True,
        
    )
 call is quite simple

**Comment by mxschmitt** [comment]
This involves external third-party libraries. Are you able to provide a reproducible which does not involve any? Otherwise we'd have to refer to them for help.

**Comment by wanghaisheng** [comment]
third-party libraries. you mean which one 
that is me too

**Comment by wanghaisheng** [comment]
PlaywrightAsyncDriverStealth  is written by me 
https://github.com/wanghaisheng/tiktoka-studio-uploader/blob/playwright/tsup/utils/webdriver/playwright_driver_async_stealth.py

cf_clearance i can remove this

**Comment by mxschmitt** [comment]
We need more information to act on this report. Please file a new one with a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example). Ideally one script with expected and actual outcome. Thanks for your understanding.
