### ISSUE TITLE
[BUG]python:v1.35.0-jammy can't suport  China-made Hygon chip?

### ISSUE THREAD

**Issue by libp** [microsoft/playwright-python#1994]
**Context:**
- Playwright Version: 1.35.0
- Operating System: Linux 
- Python version: 3.10
- Browser: All
- Extra: My server's chip is using the China-made Hygon chip, which is also based on the X86 architecture。I use 
 mcr.microsoft.com/playwright/python:v1.35.0-jammy  as base docker images

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally.

```python
from playwright.sync_api import sync_playwright
with sync_playwright() as playwright:
    browser = playwright.chromium.launch(headless=True)
    context = browser.new_context()
    page = context.new_page()
    page.goto('https://baidu.com')
    page.wait_for_load_state('networkidle')
    page.screenshot(path='example.png')
    browser.close()
```

**Describe the bug**

Add any other details about the problem here.
(ansible) [user@mes01 test]$ docker exec -it f2 bash
root@f213bc89d4b9:/opt# python demo.py 
Traceback (most recent call last):
  File "/opt/demo.py", line 3, in <module>
    with sync_playwright() as playwright:
  File "/usr/local/lib/python3.10/dist-packages/playwright/sync_api/_context_manager.py", line 92, in __enter__
    dispatcher_fiber.switch()
  File "/usr/local/lib/python3.10/dist-packages/playwright/sync_api/_context_manager.py", line 71, in greenlet_main
    self._loop.run_until_complete(self._connection.run_as_sync())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/playwright/_impl/_connection.py", line 262, in run_as_sync
    await self.run()
  File "/usr/local/lib/python3.10/dist-packages/playwright/_impl/_connection.py", line 271, in run
    await self._transport.connect()
  File "/usr/local/lib/python3.10/dist-packages/playwright/_impl/_transport.py", line 127, in connect
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/playwright/_impl/_transport.py", line 116, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "/usr/lib/python3.10/asyncio/subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1667, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 212, in _make_subprocess_transport
    watcher.add_child_handler(transp.get_pid(),
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 1377, in add_child_handler
    thread.start()
  File "/usr/lib/python3.10/threading.py", line 935, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
/usr/local/lib/python3.10/dist-packages/playwright/driver/node[31]: ../src/node_platform.cc:68:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0xb7a940 node::Abort() [/usr/local/lib/python3.10/dist-packages/playwright/driver/node]
 2: 0xb7a9be  [/usr/local/lib/python3.10/dist-packages/playwright/driver/node]
 3: 0xbe98be  [/usr/local/lib/python3.10/dist-packages/playwright/driver/node]
Future exception was never retrieved
future: <Future finished exception=RuntimeError("can't start new thread")>
Traceback (most recent call last):
  File "/opt/demo.py", line 3, in <module>
    with sync_playwright() as playwright:
  File "/usr/local/lib/python3.10/dist-packages/playwright/sync_api/_context_manager.py", line 92, in __enter__
    dispatcher_fiber.switch()
  File "/usr/local/lib/python3.10/dist-packages/playwright/sync_api/_context_manager.py", line 71, in greenlet_main
    self._loop.run_until_complete(self._connection.run_as_sync())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/playwright/_impl/_connection.py", line 262, in run_as_sync
    await self.run()
  File "/usr/local/lib/python3.10/dist-packages/playwright/_impl/_connection.py", line 271, in run
    await self._transport.connect()
  File "/usr/local/lib/python3.10/dist-packages/playwright/_impl/_transport.py", line 127, in connect
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/playwright/_impl/_transport.py", line 116, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "/usr/lib/python3.10/asyncio/subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1667, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 212, in _make_subprocess_transport
    watcher.add_child_handler(transp.get_pid(),
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 1377, in add_child_handler
    thread.start()
  File "/usr/lib/python3.10/threading.py", line 935, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
 4: 0xbe99a1 node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [/usr/local/lib/python3.10/dist-packages/playwright/driver/node]
 5: 0xb38f5b node::InitializeOncePerProcess(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, node::ProcessFlags::Flags) [/usr/local/lib/python3.10/dist-packages/playwright/driver/node]
 6: 0xb395ab node::Start(int, char**) [/usr/local/lib/python3.10/dist-packages/playwright/driver/node]
 7: 0x7f7e30dc3d90  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7f7e30dc3e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0xabbdee _start [/usr/local/lib/python3.10/dist-packages/playwright/driver/node]
/usr/local/lib/python3.10/dist-packages/playwright/driver/playwright.sh: line 6:    31 Aborted                 "$PLAYWRIGHT_NODEJS_PATH" "$SCRIPT_PATH/package/lib/cli/cli.js" "$@"
root@f213bc89d4b9:/opt#

**Comment by mxschmitt** [comment]
Looks like Python is not able to spawn a new thread. Whats the output of `ulimit`? You can increase the max thread limit by `ulimit -u 4096`.

**Comment by libp** [comment]
ulimit -u
unlimited
eliminate this possibility.
I'm not install python. just use mcr.microsoft.com/playwright/python:v1.35.0-jammy as base docker images 。
The issue is that this image runs properly on my laptop（inter x86）.

**Comment by mxschmitt** [comment]
Playwright for Python internally uses Node.js which is not able to start on your system:

```
/usr/local/lib/python3.10/dist-packages/playwright/driver/node[31]: ../src/node_platform.cc:68:std::unique_ptr node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
```

since we use official Node.js, we recommend reaching out to their Node.js bug tracker: https://github.com/nodejs/node

**Comment by libp** [comment]
Thank you, I have resolved this issue by adding the "privileged" parameter.

**Comment by cyx222800** [comment]
> 谢谢，我通过添加“privileged”参数解决了这个问题。

大佬请问如何添加这个参数?

**Comment by libp** [comment]
> > 谢谢，我通过添加“privileged”参数解决了这个问题。
> 
> 大佬请问如何添加这个参数?

docker-compose.yml 文件里，有个容器启动参数，privileged：true
你运气真好，我刚好在查一个问题，看到你的提问了。
