### ISSUE TITLE
[BUG] Playwright import not working when code execution is triggered from Celery

### ISSUE THREAD

**Issue by balewgize** [microsoft/playwright-python#1995]
**Context:**
- Playwright Version: 1.35.0
- Operating System: Linux
- Python version: 3.9
- Browser: Chromium
- Extra: I'm using this Playwright with a newer version (https://github.com/pixelfactoryio/playwright-server) to connect to a remote Playwright instance.

Here is the flow of the code.

Celery task to call Django custom command every day at X hr
**tasks.py**
```
@shared_task
def task_name():
    call_command("django_custom_command_name")
```

A module that uses remote playwright to load a page and take screenshots, then save to DB.

**module.py** 
```
from playwright.sync_api import sync_playwright

PLAYWRIGHT_SERVER = "ws://IP:PORT"

def take_screenshot(URL):
    with sync_playwright() as p:
        browser = playwright.chromium.connect(PLAYWRIGHT_SERVER)
        context = browser.new_context()
        page = context.new_page()
        page.goto(URL)
        page.screenshot(path='screenshot.png')
        # save to DB

        context.close()
        browser.close()
```

Django custom command
/app/management/commands/command.py
```
from module import take_screenshot

URL = ""  # load from DB
take_screenshot(URL)
```

So when the command is triggered via crontab from Celery, the Playwright import from the above module causes the following error

**AttributeError: module 'select' has no attribute 'epoll'**

It works with no error if I run the command using `python manage.py command`. But not when it is scheduled to run via Celery.

I can provide the full traceback if needed. 

Any idea why it happened and how to resolve it would be highly appreciated. Thanks!

**Comment by mxschmitt** [comment]
Can you check the Python version on both cases? How does the full traceback look like?

Would it be possible to provide a minimal reproduction which we can run locally? Preferable inside a small Docker container.

**Comment by balewgize** [comment]
@mxschmitt thanks for your response. The full traceback looks like this.

```
celeryworker_1  | [2023-06-29 08:15:05,553: ERROR/MainProcess] Task apps.modules.advert.tasks.track_blackhat_ppc_links[cb9862ab-31c3-4e04-9e59-d68ca3e19631] raised unexpected: AttributeError("module 'select' has no attribute 'epoll'")
celeryworker_1  | Traceback (most recent call last):
celeryworker_1  |   File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
celeryworker_1  |     R = retval = fun(*args, **kwargs)
celeryworker_1  |   File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
celeryworker_1  |     return self.run(*args, **kwargs)
celeryworker_1  |   File "/app/backend/apps/modules/advert/tasks.py", line 139, in track_blackhat_ppc_links
celeryworker_1  |     call_command("extract_blackhat_ppc_links")
celeryworker_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 122, in call_command
celeryworker_1  |     command = load_command_class(app_name, command_name)
celeryworker_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 48, in load_command_class
celeryworker_1  |     module = import_module("%s.management.commands.%s" % (app_name, name))
celeryworker_1  |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
celeryworker_1  |     return _bootstrap._gcd_import(name[level:], package, level)
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
celeryworker_1  |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
celeryworker_1  |   File "/app/backend/apps/modules/advert/management/commands/extract_blackhat_ppc_links.py", line 8, in <module>
celeryworker_1  |     from apps.modules.advert.blackhat_ppc.affiliate_tracker import BlackhatAffiliateTracker
celeryworker_1  |   File "/app/backend/apps/modules/advert/blackhat_ppc/affiliate_tracker.py", line 11, in <module>
celeryworker_1  |     from playwright.sync_api import sync_playwright
celeryworker_1  |   File "/usr/local/lib/python3.9/site-packages/playwright/async_api/__init__.py", line 25, in <module>
celeryworker_1  |     import playwright.async_api._generated
celeryworker_1  |   File "/usr/local/lib/python3.9/site-packages/playwright/async_api/_generated.py", line 25, in <module>
celeryworker_1  |     from playwright._impl._accessibility import Accessibility as AccessibilityImpl
celeryworker_1  |   File "/usr/local/lib/python3.9/site-packages/playwright/_impl/_accessibility.py", line 17, in <module>
celeryworker_1  |     from playwright._impl._connection import Channel
celeryworker_1  |   File "/usr/local/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 35, in <module>
celeryworker_1  |     from pyee import EventEmitter
celeryworker_1  |   File "/usr/local/lib/python3.9/site-packages/pyee/__init__.py", line 120, in <module>
celeryworker_1  |     from pyee.trio import TrioEventEmitter as _TrioEventEmitter  # noqa
celeryworker_1  |   File "/usr/local/lib/python3.9/site-packages/pyee/trio.py", line 7, in <module>
celeryworker_1  |     import trio
celeryworker_1  |   File "/usr/local/lib/python3.9/site-packages/trio/__init__.py", line 18, in <module>
celeryworker_1  |     from ._core import (
celeryworker_1  |   File "/usr/local/lib/python3.9/site-packages/trio/_core/__init__.py", line 27, in <module>
celeryworker_1  |     from ._run import (
celeryworker_1  |   File "/usr/local/lib/python3.9/site-packages/trio/_core/_run.py", line 2452, in <module>
celeryworker_1  |     from ._io_epoll import EpollIOManager as TheIOManager
celeryworker_1  |   File "/usr/local/lib/python3.9/site-packages/trio/_core/_io_epoll.py", line 188, in <module>
celeryworker_1  |     class EpollIOManager:
celeryworker_1  |   File "/usr/local/lib/python3.9/site-packages/trio/_core/_io_epoll.py", line 189, in EpollIOManager
celeryworker_1  |     _epoll = attr.ib(factory=select.epoll)
celeryworker_1  | AttributeError: module 'select' has no attribute 'epoll'
```

Yes, I will prepare a minimal reproduction code and update here ASAP

**Comment by balewgize** [comment]
One thing I forgot to mention is when I run the command, it did execute and perform the job but it also gives this error.

asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=Error('Connection closed')>
playwright._impl._api_types.Error: Connection closed

**Comment by mxschmitt** [comment]
Not sure if we can do something here, the exception gets thrown from the `trio` package, which is required [here](https://github.com/jfhbrook/pyee/blob/8d207760be4792feb4009f10d31003cfcc530b93/pyee/__init__.py#L120-L136) from the `pyee` package.

You can try to comment out that `trio` stuff in this file `/usr/local/lib/python3.9/site-packages/pyee/__init__.py`. Maybe pyee is not compatible with a specific `trio` version.

I'd try the following things:
- try to comment it out and see if it then works
- Provide us your version of the `trio` package and the `pyee` package (should be 9.0.4)

Then we can figure out of there is an incompatibility between them and might upstream a fix somewhere.

**Comment by balewgize** [comment]
It was difficult to comment on that part inside docker, but did it, and still not working. Here is the version 
```
pyee==9.0.4
trio==0.22.0
```

**Comment by mxschmitt** [comment]
These versions are looking good. I'll close it for now as part of the triage process, since we don't have a minimal reproducible.

Don't hesitate to re-file with clear reproduction steps, thanks!
