### ISSUE TITLE
[Feature] How to ignore system proxy settings and set proxy to None

### ISSUE THREAD

**Issue by cesaryuan** [microsoft/playwright-python#2085]
As the title states, my system is Windows 10 and a global proxy is set, but I don’t want playwright to use this proxy. I don't want to use any proxy.

I tried `playwright.chromium.launch(proxy=None)` but that didn't work. System proxy is still used.

**Comment by yury-s** [comment]
As a workaround you can pass `--proxy-server="direct://"` command line [argument](https://playwright.dev/python/docs/api/class-browsertype#browser-type-launch-option-args) to the browser, according to [Chromium docs](https://www.chromium.org/developers/design-documents/network-settings/#:~:text=By%20using%20the%20special%20%22direct,to%20not%20use%20a%20proxy.&text=This%20tells%20chrome%20to%20bypass,tandem%20with%20%2D%2Dproxy%2Dserver.) it will cause all connections to not use a proxy:

```py
browser = playwright.chromium.launch( # or "firefox" or "webkit".
    args=['--proxy-server="direct://"']
)
```
will that work?

**Comment by cesaryuan** [comment]
> will that work?

Thank you for the documentation website you provided. After my try, `--proxy-server="direct://"` does not work, but `--no-proxy-server` works very well.

When using `--proxy-server="direct://"`, it will throw exception:
```
Traceback (most recent call last):
  File "E:\scoop\apps\miniconda3\current\envs\paddle\lib\site-packages\playwright\sync_api\_generated.py", line 9303, in goto
    self._sync(
  File "E:\scoop\apps\miniconda3\current\envs\paddle\lib\site-packages\playwright\_impl\_sync_base.py", line 109, in _sync
    return task.result()
  File "E:\scoop\apps\miniconda3\current\envs\paddle\lib\site-packages\playwright\_impl\_page.py", line 479, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "E:\scoop\apps\miniconda3\current\envs\paddle\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "E:\scoop\apps\miniconda3\current\envs\paddle\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "E:\scoop\apps\miniconda3\current\envs\paddle\lib\site-packages\playwright\_impl\_connection.py", line 482, in wrap_api_call
    return await cb()
  File "E:\scoop\apps\miniconda3\current\envs\paddle\lib\site-packages\playwright\_impl\_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: net::ERR_NO_SUPPORTED_PROXIES at http://example.com/
```

Anyway, the issue has been solved with `--no-proxy-server`, thanks!

```python
browser = playwright.chromium.launch(args=['--no-proxy-server'])
```
