### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'playwright' version1.37.0 and heigher in docker

### ISSUE THREAD

**Issue by pavoltravnik** [microsoft/playwright-python#2086]
### System info
- Playwright Version: v1.37.0 and heigher (meybe lower too)
- Operating System: macOS, Ubuntu
- Browser: 
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

```txt
$ docker run -it --rm --ipc=host mcr.microsoft.com/playwright/python:v1.29.0 /bin/bash
Unable to find image 'mcr.microsoft.com/playwright/python:v1.29.0' locally
v1.29.0: Pulling from playwright/python
846c0b181fff: Pull complete 
37d4ab11ad75: Pull complete 
a2f73531cb42: Pull complete 
0779c86c759b: Pull complete 
Digest: sha256:d362e9a7223bd21053dc26f49115da9c2a7d588d77c8476833a8311b5f5a5d00
Status: Downloaded newer image for mcr.microsoft.com/playwright/python:v1.29.0
root@68d289012f60:/# python
Python 3.8.10 (default, Nov 14 2022, 12:59:47) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from playwright.async_api import async_playwright
>>> exit
Use exit() or Ctrl-D (i.e. EOF) to exit
>>> exit()
root@68d289012f60:/# python3
Python 3.8.10 (default, Nov 14 2022, 12:59:47) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from playwright.async_api import async_playwright
>>> exit
Use exit() or Ctrl-D (i.e. EOF) to exit
>>> exit()
root@68d289012f60:/# exit
exit
$ docker run -it --rm --ipc=host mcr.microsoft.com/playwright/python:v1.37.0 /bin/bash
root@f93c81014fff:/# python
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from playwright.async_api import async_playwright
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'playwright'
>>> exit()
root@f93c81014fff:/# python3
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from playwright.async_api import async_playwright
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'playwright'
>>> 

```

**Link to the GitHub repository with the repro**

**Steps**
- [Run docker command]
- [open python and try to load playwright library]

**Expected**

library is loaded

**Actual**

ModuleNotFoundError: No module named 'playwright'

**Comment by yury-s** [comment]
Playwright was installed globally inadvertently and that was fixed in https://github.com/microsoft/playwright-python/pull/1921. Users are expected to install playwright in the docker image along with their app. The image [is promised](https://playwright.dev/python/docs/docker) to contain browsers and their native dependencies preinstalled nothing more.
