### ISSUE TITLE
[Question]  sync_playwright doesn't work with FastAPI. error message: location: expected object, got null

### ISSUE THREAD

**Issue by amal-meer** [microsoft/playwright-python#2097]
### System info
- Playwright Version: [v1.37.0]
- Operating System: [Debian 11]
- Browser: [Chromium]
- Other info: Python 3.8.17. Also I'm running the code in a docker container.

### Source code

```python
from playwright.sync_api import sync_playwright
from fastapi import APIRouter
router = APIRouter()

@router.get("/test")
def test_playwright():
    with sync_playwright() as p:
        return "SUCSESS"
```

**Steps**
- curl --location 'http://127.0.0.1/test'

**Expected** 
"SUCSESS" message is printed.

**Actual**
The code stuck in the line `with sync_playwright() as p`.
This is the log message after enabling `DEBUGP=1` env var.
```
SEND> {
  "id": 1,
  "guid": "",
  "method": "initialize",
  "params": {
    "sdkLanguage": "python"
  },
  "metadata": {
    "wallTime": 1696340903348,
    "apiName": "PlaywrightContextManager.greenlet_main",
    "location": null,
    "internal": false
  }
}
RECV> {
  "id": 1,
  "error": {
    "error": {
      "message": "location: expected object, got null",
      "stack": "Error: location: expected object, got null\n    at /usr/local/lib/python3.8/site-packages/playwright/driver/package/lib/protocol/validatorPrimitives.js:104:37\n    at /usr/local/lib/python3.8/site-packages/playwright/driver/package/lib/protocol/validatorPrimitives.js:91:12\n    at /usr/local/lib/python3.8/site-packages/playwright/driver/package/lib/protocol/validatorPrimitives.js:108:21\n    at /usr/local/lib/python3.8/site-packages/playwright/driver/package/lib/protocol/validatorPrimitives.js:91:12\n    at DispatcherConnection.dispatch (/usr/local/lib/python3.8/site-packages/playwright/driver/package/lib/server/dispatchers/dispatcher.js:239:23)\n    at transport.onmessage (/usr/local/lib/python3.8/site-packages/playwright/driver/package/lib/cli/driver.js:52:57)\n    at Immediate._onImmediate (/usr/local/lib/python3.8/site-packages/playwright/driver/package/lib/protocol/transport.js:77:34)\n    at process.processImmediate (node:internal/timers:476:21)",
      "name": "Error"
    }
  }
}
```

If I changed the code to use async functions as follow:
```python
@router.get("/test")
async def test_playwright():
    async with async_playwright() as p:
        return "SUCSESS"
```
it works fine without any error, and this is part of the logs I got
```
SEND> {
  "id": 1,
  "guid": "",
  "method": "initialize",
  "params": {
    "sdkLanguage": "python"
  },
  "metadata": {
    "wallTime": 1696344718678,
    "apiName": "Connection.init",
    "location": {
      "file": "/usr/local/lib/python3.8/site-packages/uvicorn/server.py",
      "line": 50,
      "column": 0
    },
    "internal": false
  }
}
```

The question is what causes the async code to work, but no the sync?

**Comment by mxschmitt** [comment]
Probably some bug around this code: https://github.com/microsoft/playwright-python/blob/0e92fbc2cceba0551305f2e36f75f9b71f5d5b6e/playwright/_impl/_connection.py#L473-L498

Is this reproducible with a fresh new FastAPI project?

**Comment by mxschmitt** [comment]
This works for my, hence closing. Please re-file with a repro.

```python
from fastapi import FastAPI, Response

app = FastAPI()
from typing import Optional

from playwright.async_api import async_playwright, Playwright

playwright: Optional[Playwright] = None


@app.get("/")
async def root():
    global playwright
    if not playwright:
        playwright = await async_playwright().start()
    browser = await playwright.chromium.launch()
    page = await browser.new_page()
    await page.goto("http://playwright.dev")
    screenshot = await page.screenshot()
    await browser.close()
    return Response(content=screenshot, media_type="image/png")
```

and sync as well:

```python
from fastapi import FastAPI, Response

app = FastAPI()
from typing import Optional

from playwright.sync_api import sync_playwright, Playwright

playwright: Optional[Playwright] = None


@app.get("/")
def root():
    global playwright
    if not playwright:
        playwright = sync_playwright().start()
    browser = playwright.chromium.launch()
    page = browser.new_page()
    page.goto("http://playwright.dev")
    screenshot = page.screenshot()
    browser.close()
    return Response(content=screenshot, media_type="image/png")

```
