### ISSUE TITLE
[BUG] Missing Host Dependencies when Bundling using Pyinstaller

### ISSUE THREAD

**Issue by SteveImmanuel** [microsoft/playwright-python#2100]
### System info
- Playwright Version: v1.38.0
- Operating System: Ubuntu 22.04 LTS
- Browser: Firefox
- Other info:

### Source code

- [X] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**
```python3
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.firefox.launch(headless=False)
    page = browser.new_page()
    page.goto("https://playwright.dev/")
    page.screenshot(path="example.png")
    browser.close()
```
**Python env (conda)**
```yaml
name: translate
channels:
  - microsoft
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.7.22=hbcca054_0
  - greenlet=2.0.2=py39h3d6467e_1
  - ld_impl_linux-64=2.40=h41732ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_2
  - libgomp=13.2.0=h807b86a_2
  - libnsl=2.0.0=hd590300_1
  - libsqlite=3.43.0=h2797004_0
  - libstdcxx-ng=13.2.0=h7e041cc_2
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.2.13=hd590300_5
  - ncurses=6.4=hcb278e6_0
  - openssl=3.1.3=hd590300_0
  - pip=23.2.1=pyhd8ed1ab_0
  - playwright=1.38.0=py39_0
  - pyee=9.0.4=pyhd8ed1ab_0
  - python=3.9.18=h0755675_0_cpython
  - python_abi=3.9=4_cp39
  - readline=8.2=h8228510_1
  - setuptools=68.2.2=pyhd8ed1ab_0
  - tk=8.6.13=h2797004_0
  - typing_extensions=4.8.0=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - wheel=0.41.2=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
      - altgraph==0.17.4
      - importlib-metadata==6.8.0
      - packaging==23.2
      - pyinstaller==6.0.0
      - pyinstaller-hooks-contrib==2023.9
      - pyperclip==1.8.2
      - zipp==3.17.0
```

**Steps**
- Run the script `python main.py` and it works as expected
- Create executable using Pyinstaller
```
PLAYWRIGHT_BROWSERS_PATH=0 playwright install --with-deps firefox
pyinstaller -F main.py
```
- Execute the generated file
```
./dist/main
```

**Expected**
Program executed, a screenshot is taken and saved.

**Actual**
Error missing system dependencies as follows:
```
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    browser = p.firefox.launch(headless=False)
  File "playwright/sync_api/_generated.py", line 14778, in launch
  File "playwright/_impl/_sync_base.py", line 109, in _sync
  File "playwright/_impl/_browser_type.py", line 96, in launch
  File "playwright/_impl/_connection.py", line 61, in send
  File "playwright/_impl/_connection.py", line 482, in wrap_api_call
  File "playwright/_impl/_connection.py", line 97, in inner_send
playwright._impl._api_types.Error: 
╔══════════════════════════════════════════════════════╗
║ Host system is missing dependencies to run browsers. ║
║ Missing libraries:                                   ║
║     libxul.so                                        ║
╚══════════════════════════════════════════════════════╝
[736532] Failed to execute script 'main' due to unhandled exception!
```

### Installation logs
```
133 INFO: PyInstaller: 6.0.0
133 INFO: Python: 3.9.18 (conda)
136 INFO: Platform: Linux-6.2.0-33-generic-x86_64-with-glibc2.35
136 INFO: wrote /home/steve/Git/test-firefox/main.spec
138 INFO: Extending PYTHONPATH with paths
['/home/steve/Git/test-firefox']
195 INFO: checking Analysis
195 INFO: Building Analysis because Analysis-00.toc is non existent
195 INFO: Initializing module dependency graph...
196 INFO: Caching module graph hooks...
201 INFO: Analyzing base_library.zip ...
648 INFO: Loading module hook 'hook-encodings.py' from '/home/steve/miniconda3/envs/translate/lib/python3.9/site-packages/PyInstaller/hooks'...
1302 INFO: Loading module hook 'hook-pickle.py' from '/home/steve/miniconda3/envs/translate/lib/python3.9/site-packages/PyInstaller/hooks'...
1713 INFO: Loading module hook 'hook-heapq.py' from '/home/steve/miniconda3/envs/translate/lib/python3.9/site-packages/PyInstaller/hooks'...
1878 INFO: Caching module dependency graph...
1935 INFO: Running Analysis Analysis-00.toc
1935 INFO: Looking for Python shared library...
1943 INFO: Using Python shared library: /home/steve/miniconda3/envs/translate/lib/libpython3.9.so.1.0
1943 INFO: Analyzing /home/steve/Git/test-firefox/main.py
1946 INFO: Loading module hook 'hook-playwright.sync_api.py' from '/home/steve/miniconda3/envs/translate/lib/python3.9/site-packages/playwright/_impl/__pyinstaller'...
2253 INFO: Loading module hook 'hook-multiprocessing.util.py' from '/home/steve/miniconda3/envs/translate/lib/python3.9/site-packages/PyInstaller/hooks'...
2349 INFO: Loading module hook 'hook-xml.py' from '/home/steve/miniconda3/envs/translate/lib/python3.9/site-packages/PyInstaller/hooks'...
2683 INFO: Loading module hook 'hook-platform.py' from '/home/steve/miniconda3/envs/translate/lib/python3.9/site-packages/PyInstaller/hooks'...
2805 INFO: Processing module hooks...
3828 INFO: Looking for ctypes DLLs
3830 INFO: Analyzing run-time hooks ...
3833 INFO: Including run-time hook '/home/steve/miniconda3/envs/translate/lib/python3.9/site-packages/PyInstaller/hooks/rthooks/pyi_rth_inspect.py'
3833 INFO: Including run-time hook '/home/steve/miniconda3/envs/translate/lib/python3.9/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pkgutil.py'
3835 INFO: Including run-time hook '/home/steve/miniconda3/envs/translate/lib/python3.9/site-packages/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py'
3846 INFO: Looking for dynamic libraries
	not a dynamic executable
4872 WARNING: Library not found: could not resolve 'libxul.so', dependency of '/home/steve/miniconda3/envs/translate/lib/python3.9/site-packages/playwright/driver/package/.local-browsers/firefox-1424/firefox/plugin-container'.
4879 INFO: Warnings written to /home/steve/Git/free-google-translate-image/build/main/warn-main.txt
4894 INFO: Graph cross-reference written to /home/steve/Git/free-google-translate-image/build/main/xref-main.html
4907 INFO: checking PYZ
4907 INFO: Building PYZ because PYZ-00.toc is non existent
4907 INFO: Building PYZ (ZlibArchive) /home/steve/Git/free-google-translate-image/build/main/PYZ-00.pyz
5103 INFO: Building PYZ (ZlibArchive) /home/steve/Git/free-google-translate-image/build/main/PYZ-00.pyz completed successfully.
5119 INFO: checking PKG
5119 INFO: Building PKG because PKG-00.toc is non existent
5120 INFO: Building PKG (CArchive) main.pkg
28250 INFO: Building PKG (CArchive) main.pkg completed successfully.
28256 INFO: Bootloader /home/steve/miniconda3/envs/translate/lib/python3.9/site-packages/PyInstaller/bootloader/Linux-64bit-intel/run
28256 INFO: checking EXE
28256 INFO: Building EXE because EXE-00.toc is non existent
28256 INFO: Building EXE from EXE-00.toc
28256 INFO: Copying bootloader EXE to /home/steve/Git/test-firefox/dist/main
28256 INFO: Appending PKG archive to custom ELF section in EXE
28828 INFO: Building EXE from EXE-00.toc completed successfully.
```

**Comment by mxschmitt** [comment]
This is expected, bundling OS dependencies is outside of the scope of Playwright. We recommend running `playwright install --with-deps` before you use Playwright: https://playwright.dev/python/docs/browsers#install-system-dependencies
