### ISSUE TITLE
[BUG] KeyError: 'deviceDescriptors' after upgrading to 1.39

### ISSUE THREAD

**Issue by naushadh** [microsoft/playwright-python#2130]
### System info

- Playwright Version: 1.39.0
- Operating System: RHEL 8
- Browser: [All, Chromium]

<details><summary>More Info</summary>

```bash
$ cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="8.8 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.8 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.8
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.8"

$ env
BROWSER_ENDPOINT=ws://browser:3000
LANG=C.utf8
HOSTNAME=89291b76e3d5
which_declare=declare -f
container=oci
PWD=/app
HOME=/root
TERM=xterm
SHLVL=1
PYTHONPATH=/app
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.local/bin
BASH_FUNC_which%%=() {  ( alias;
 eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot $@
}
_=/usr/bin/env

$ python3 --version
Python 3.11.2

$ pip3 list
Package            Version
------------------ ---------
aiohttp            3.8.6
aiosignal          1.3.1
async-timeout      4.0.3
attrs              23.1.0
charset-normalizer 3.3.0
frozenlist         1.4.0
greenlet           2.0.2
idna               3.4
ldap3              2.9.1
Markdown           3.5
multidict          6.0.4
mypy               1.6.1
mypy-extensions    1.0.0
pip                22.3.1
playwright         1.38.0
pyasn1             0.5.0
pyee               9.0.4
setuptools         65.5.1
types-ldap3        2.9.13.14
types-Markdown     3.5.0.0
types-pyasn1       0.5.0.0
typing_extensions  4.8.0
yarl               1.9.2
```

</details>

### Source code

```python
import asyncio
import os
import playwright.async_api as pw


async def app() -> None:
    endpoint = os.environ['BROWSER_ENDPOINT']
    browser = await (await pw.async_playwright().start()).chromium.connect(f"{endpoint}/playwright")
    page = await browser.new_page()

    await page.goto("https://google.com")
    print(await page.locator("body").inner_text())


asyncio.get_event_loop().run_until_complete(app())
```

**Expected**

With `playwright==1.38.0`, all is well

```bash
$ python3 lib/test.py
About
Store
GmailImages
Sign in
 
Google offered in: Français
Canada
Advertising
Business
How Search works
Privacy
Terms
Settings
```

**Actual**

Upgraded to 1.39.0

```bash
$ pip3 install playwright==1.39.0
...
  Attempting uninstall: pyee
    Found existing installation: pyee 9.0.4
    Uninstalling pyee-9.0.4:
      Successfully uninstalled pyee-9.0.4
  Attempting uninstall: greenlet
    Found existing installation: greenlet 2.0.2
    Uninstalling greenlet-2.0.2:
      Successfully uninstalled greenlet-2.0.2
  Attempting uninstall: playwright
    Found existing installation: playwright 1.38.0
    Uninstalling playwright-1.38.0:
      Successfully uninstalled playwright-1.38.0
Successfully installed greenlet-3.0.0 playwright-1.39.0 pyee-11.0.1
```

With `playwright==1.39.0`, KeyError

```bash
$ python3 lib/test.py
Error occurred in event listener
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 433, in dispatch
    object._channel.emit(method, params)
  File "/usr/local/lib/python3.11/site-packages/pyee/base.py", line 208, in emit
    handled = self._call_handlers(event, args, kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyee/base.py", line 184, in _call_handlers
    self._emit_run(f, args, kwargs)
  File "/usr/local/lib/python3.11/site-packages/pyee/asyncio.py", line 53, in _emit_run
    self.emit("error", exc)
  File "/usr/local/lib/python3.11/site-packages/pyee/base.py", line 211, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/usr/local/lib/python3.11/site-packages/pyee/base.py", line 169, in _emit_handle_potential_error
    raise error
  File "/usr/local/lib/python3.11/site-packages/pyee/asyncio.py", line 51, in _emit_run
    coro: Any = f(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/playwright/_impl/_json_pipe.py", line 62, in <lambda>
    lambda params: handle_message(params["message"]),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/playwright/_impl/_json_pipe.py", line 54, in handle_message
    self.on_message(cast(ParsedMessagePayload, message))
  File "/usr/local/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 235, in <lambda>
    self._transport.on_message = lambda msg: self.dispatch(msg)
                                             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 393, in dispatch
    self._create_remote_object(
  File "/usr/local/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 443, in _create_remote_object
    result = self._object_factory(parent, type, guid, initializer)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/playwright/_impl/_object_factory.py", line 71, in create_remote_object
    local_utils = LocalUtils(parent, type, guid, initializer)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/playwright/_impl/_local_utils.py", line 30, in __init__
    for device in initializer["deviceDescriptors"]
                  ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: 'deviceDescriptors'
About
Store
GmailImages
Sign in
 
Google offered in: Français
Canada
Advertising
Business
How Search works
Privacy
Terms
Settings
```

**Comment by mxschmitt** [comment]
You need to connect to a Playwright server running with the same version as the client (Playwright for Python). We saw multiple reports like this the past few releases and in the next version we'll throw an error (client/server version mismatch) to prevent errors like this and make it more visible.

Also I recommend running Playwright on a supported operating system. RHEL is not supported as per [here](https://playwright.dev/python/docs/intro#system-requirements).
