### ISSUE TITLE
[BUG] cannot connect into docker browser

### ISSUE THREAD

**Issue by kabaBZ** [microsoft/playwright-python#2182]
### System info
- Playwright Version: [v1.35]
- Operating System: [All, Windows 10, Ubuntu 20.]
- Browser: [Chromium]
- Other info:

### Source code

```python
# docker code
import asyncio
from playwright.async_api import async_playwright
from datetime import datetime


async def main():
    playwright = await async_playwright().start()
    browser = await playwright.chromium.launch(headless=True, args=['--remote-debugging-port=9001'])
    while True:
        if browser.is_connected():
            print(f'HertBeat:{str(datetime.now())}')
            await asyncio.sleep(5)
        else:
            print('Browser Vanished!')

asyncio.run(main())
```
```python
# connect code
import asyncio
from playwright.async_api import async_playwright

async def main():
    async with async_playwright() as p:
        browser = await p.chromium.connect_over_cdp('http://127.0.0.1:9001')
        page = await browser.new_page()
        await page.goto('http://playwright.dev')
        await browser.close()

asyncio.run(main())
```

**Steps**
- docker run --env=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin --env=PLAYWRIGHT_BROWSERS_PATH=/ms-playwright --workdir=/home/srv/playwright_server -p 9001:9001 --runtime=runc -d kaba5643/playwright_stand_alone:latest

**Expected**
i started this file to establish a playwright browser as a server in docker, but when i use playwright.chromium.connect_over_cdp code to connect it will raise error as follow:

```python
Traceback (most recent call last):
  File "c:\Users\kaba\Desktop\docker_selenium\final\connect_bro.py", line 11, in <module>
    asyncio.run(main())
  File "D:\pyenv\.pyenv\pyenv-win\versions\3.7.5\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "D:\pyenv\.pyenv\pyenv-win\versions\3.7.5\lib\asyncio\base_events.py", line 579, in run_until_complete
    return future.result()
  File "c:\Users\kaba\Desktop\docker_selenium\final\connect_bro.py", line 6, in main
    browser = await p.chromium.connect_over_cdp('http://127.0.0.1:9001')
  File "D:\pyenv\.pyenv\pyenv-win\versions\3.7.5\lib\site-packages\playwright\async_api\_generated.py", line 15022, in connect_over_cdp
    headers=mapping.to_impl(headers),
  File "D:\pyenv\.pyenv\pyenv-win\versions\3.7.5\lib\site-packages\playwright\_impl\_browser_type.py", line 172, in connect_over_cdp   
    response = await self._channel.send_return_as_dict("connectOverCDP", params)
  File "D:\pyenv\.pyenv\pyenv-win\versions\3.7.5\lib\site-packages\playwright\_impl\_connection.py", line 67, in send_return_as_dict   
    lambda: self.inner_send(method, params, True)
  File "D:\pyenv\.pyenv\pyenv-win\versions\3.7.5\lib\site-packages\playwright\_impl\_connection.py", line 482, in wrap_api_call        
    return await cb()
  File "D:\pyenv\.pyenv\pyenv-win\versions\3.7.5\lib\site-packages\playwright\_impl\_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: socket hang up
=========================== logs ===========================
<ws preparing> retrieving websocket url from http://127.0.0.1:9001
============================================================
```

**Actual**
Exception has occurred: Error

**Comment by mxschmitt** [comment]
When exposing ports from inside a Docker container to the outside host, you need to bind it to the `0.0.0.0` network interface. Chromium by default binds to 127.0.0.1 which would not be accessible. 

Can you try passing the following argument to Chromium as well? `"--remote-debugging-address=0.0.0.0"`

Let us know if it works for you!

**Comment by kabaBZ** [comment]
> When exposing ports from inside a Docker container to the outside host, you need to bind it to the `0.0.0.0` network interface. Chromium by default binds to 127.0.0.1 which would not be accessible.
> 
> Can you try passing the following argument to Chromium as well? `"--remote-debugging-address=0.0.0.0"`
> 
> Let us know if it works for you!

It work! Thanks a lot!
