### ISSUE TITLE
[BUG] AttributeError: 'dict' object has no attribute '_object'

### ISSUE THREAD

**Issue by Slender357** [microsoft/playwright-python#2183]
### System info
- Playwright Version: [v1.40.0]
- Operating System: [Ubuntu 20]
- Browser: [Chromium]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Test file (self-contained)**

```python
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()
    # ...
    browser.close()
```

**Steps**
- [Run the test]
- [...]

**Expected**

ERROR    [2023-11-30 20:13:36,310] asyncio.default_exception_handler:1758 Task exception was never retrieved
future: <Task finished name='Task-2' coro=<Connection.run() done, defined at /usr/local/lib/python3.10/site-packages/playwright/_impl/_connection.py:268> exception=AttributeError("'dict' object has no attribute '_object'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 277, in run
    await self._transport.run()
  File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_transport.py", line 163, in run
    self.on_message(obj)
  File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 236, in <lambda>
    self._transport.on_message = lambda msg: self.dispatch(msg)
  File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 395, in dispatch
    self._create_remote_object(
  File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 445, in _create_remote_object
    result = self._object_factory(parent, type, guid, initializer)
  File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_object_factory.py", line 67, in create_remote_object
    return Frame(parent, type, guid, initializer)
  File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 79, in __init__
    self._parent_frame = from_nullable_channel(initializer.get("parentFrame"))
  File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 515, in from_nullable_channel
    return channel._object if channel else None
AttributeError: 'dict' object has no attribute '_object'

**Actual**

[Describe actual behavior]

**Comment by mxschmitt** [comment]
This looks similar to https://github.com/microsoft/playwright/issues/28320, folding into it.

Since it does not contain a repro, closing for now.

**Comment by ZackPlauche** [comment]
I just got the same bug 🤷‍♂️

**Comment by keeth** [comment]
I am seeing this too fwiw

**Comment by LoadingT** [comment]
i get this bug when use .inner_text() when iframe not loaded correctly, i check the code and there no 'try and except'
