### ISSUE TITLE
[Feature] Playwright on jupiter notebook?

### ISSUE THREAD

**Issue by frbelotto** [microsoft/playwright-python#2185]
Hello guys,
I´ve seem many issues here and a stackoverflow discussions about running playwright inside a Jupiter notebook, but none of them were successful

I know its a old discussion, but years later, it still not possible? 

`from playwright.async_api import async_playwright

```
async with async_playwright() as p:
    browser = await p.chromium.launch()
    page = await browser.new_page()`

```
`Task exception was never retrieved
future: <Task finished name='Task-18' coro=<Connection.run() done, defined at [c:\Users\fabio\OneDrive\Python\Playwright_Scraping\.venv\Lib\site-packages\playwright\_impl\_connection.py:268](file:///C:/Users/fabio/OneDrive/Python/Playwright_Scraping/.venv/Lib/site-packages/playwright/_impl/_connection.py:268)> exception=NotImplementedError()>
Traceback (most recent call last):
  File "c:\Users\fabio\OneDrive\Python\Playwright_Scraping\.venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3548, in run_code
    await eval(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\fabio\AppData\Local\Temp\ipykernel_19176\2885320426.py", line 24, in <module>
    result = await get_browser_content()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabio\AppData\Local\Temp\ipykernel_19176\2885320426.py", line 10, in get_browser_content
    async with async_playwright() as p:
  File "c:\Users\fabio\OneDrive\Python\Playwright_Scraping\.venv\Lib\site-packages\playwright\async_api\_context_manager.py", line 47, in __aenter__
    playwright = AsyncPlaywright(next(iter(done)).result())
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabio\AppData\Local\Programs\Python\Python312\Lib\asyncio\futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "c:\Users\fabio\OneDrive\Python\Playwright_Scraping\.venv\Lib\site-packages\playwright\_impl\_transport.py", line 123, in connect
    self._proc = await asyncio.create_subprocess_exec(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabio\AppData\Local\Programs\Python\Python312\Lib\asyncio\subprocess.py", line 222, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabio\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1708, in subprocess_exec
    transport = await self._make_subprocess_transport(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabio\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 502, in _make_subprocess_transport
...
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabio\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 502, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError`

**Comment by nihirv** [comment]
Running into the same error as you

**Comment by mxschmitt** [comment]
Closing since this issue is not about an end-to-end testing use-case. Feel free to re-file if your repro starts with python main.py or pytest like our guides are about. Thanks!
