### ISSUE TITLE
[Docs] Add usage instructions for Django (including 3.x)

### ISSUE THREAD

**Issue by pinguin999** [microsoft/playwright-python#224]
Hi I'm trying the django example from: https://devblogs.microsoft.com/python/announcing-playwright-for-python-reliable-end-to-end-testing-for-the-web/

But I'm getting this error:

````
Creating test database for alias 'default'...
System check identified no issues (1 silenced).
.E
======================================================================
ERROR: test_login (app.tests_playwright.MyViewTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Lubitz\.virtualenvs\DjangoBasisLager-JHlOkGlw\lib\site-packages\django\test\testcases.py", line 274, in __call__
    self._post_teardown()
  File "C:\Users\Lubitz\.virtualenvs\DjangoBasisLager-JHlOkGlw\lib\site-packages\django\test\testcases.py", line 1009, in _post_teardown
    self._fixture_teardown()
  File "C:\Users\Lubitz\.virtualenvs\DjangoBasisLager-JHlOkGlw\lib\site-packages\django\test\testcases.py", line 1044, in _fixture_teardown
    inhibit_post_migrate=inhibit_post_migrate)
  File "C:\Users\Lubitz\.virtualenvs\DjangoBasisLager-JHlOkGlw\lib\site-packages\django\core\management\__init__.py", line 168, in call_command
    return command.execute(*args, **defaults)
  File "C:\Users\Lubitz\.virtualenvs\DjangoBasisLager-JHlOkGlw\lib\site-packages\django\core\management\base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "C:\Users\Lubitz\.virtualenvs\DjangoBasisLager-JHlOkGlw\lib\site-packages\django\core\management\commands\flush.py", line 49, in handle
    allow_cascade=allow_cascade)
  File "C:\Users\Lubitz\.virtualenvs\DjangoBasisLager-JHlOkGlw\lib\site-packages\django\core\management\sql.py", line 13, in sql_flush
    tables = connection.introspection.django_table_names(only_existing=True, include_views=False)
  File "C:\Users\Lubitz\.virtualenvs\DjangoBasisLager-JHlOkGlw\lib\site-packages\django\db\backends\base\introspection.py", line 85, in django_table_names
    existing_tables = set(self.table_names(include_views=include_views))
  File "C:\Users\Lubitz\.virtualenvs\DjangoBasisLager-JHlOkGlw\lib\site-packages\django\db\backends\base\introspection.py", line 46, in table_names
    with self.connection.cursor() as cursor:
  File "C:\Users\Lubitz\.virtualenvs\DjangoBasisLager-JHlOkGlw\lib\site-packages\django\utils\asyncio.py", line 24, in inner
    raise SynchronousOnlyOperation(message)
django.core.exceptions.SynchronousOnlyOperation: You cannot call this from an async context - use a thread or sync_to_async.

----------------------------------------------------------------------
Ran 1 test in 2.323s

FAILED (errors=1)
Destroying test database for alias 'default'...
```

**Comment by arjun27** [comment]
Thanks for reporting this @pinguin999. I was testing on Django 2.x while writing the blog post, and I suspect that you're using Django 3. I'll fix the post for 3.x.

@mxschmitt and I were trying this on Django 3, and he put together [this sample project](https://github.com/mxschmitt/python-django-playwright) that requires the `DJANGO_ALLOW_ASYNC_UNSAFE=1` environment variable to run the test without throwing this error.

Would it be possible for you to try with this env var? We would need to understand whether there are any other side-effects.

**Comment by pinguin999** [comment]
Hi looks good. 

I added `os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"` in def `setUpClass(cls):` and now it works

Thanks to @arjun27 and @mxschmitt

**Comment by mxschmitt** [comment]
Closed since the workaround seems to be working for now.

**Comment by tyomo4ka** [comment]
@mxschmitt

I might be wrong, but as far as I understand this is what happens:

* playwright creates an event loop
* Django 3.* has a validation that prevents running sync operations (e.g. model queries) inside an event loop
* DJANGO_ALLOW_ASYNC_UNSAFE=true disables this validation
* running long sync operation inside an event loop blocks the entire loop so that's why this validation exists in Django
* in test environment blocking the event loop is ok

Maybe it's a good idea to document this workaround?

**Comment by pavelfeldman** [comment]
Joining with #439
