### ISSUE TITLE
[Bug]: Can't capture browser error logs with page.on("pageerror") or page.on("console")

### ISSUE THREAD

**Issue by msu11y** [microsoft/playwright-python#2280]
### Version

1.41.1

### Steps to reproduce

I apologize if this is not a bug, but I've tried everything / looked everywhere so perhaps it is...?

Below is my code.

I have 2 fixtures that should be totally fine / irrelevant to this issue.

I have test 'test_can_load_pages_without_error' that loops through a bunch of URLS. Each time calling function 'can_load_page_without_errors'.

```
`os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"


@pytest.fixture()
def setup_and_teardown_browser():
    with sync_playwright() as p:
        # this code runs before the actual test!
        # setup / customize our browser options here
        browser = p.chromium.launch(headless=False)
        context = browser.new_context()
        page = context.new_page()
        # in order to create trace.zip file for playwrights trace viewer
        context.tracing.start(screenshots=True, snapshots=True, sources=True)
        # the yield statement is similar to the return statement, but after
        # the test is done it comes back here and continues
        yield page
        # in order to create trace.zip file
        context.tracing.stop(path="tests/trace.zip")

        # Teardown: Close the browser after the test session
        context.close()
        browser.close()


# below decorator lets us interact with db during the test
# the transaction=True parm commits the record to the db
# otherwise it would rollback changes after test runs!
@pytest.mark.django_db(transaction=True)
@pytest.fixture()
def login_to_myscore(setup_and_teardown_browser):
    try:
        # go to myscore admin page. This way we bypass the 2FA
        page = setup_and_teardown_browser
        page.goto(f'http://localhost:{local_port}/myscore_admin')
        page.get_by_label("Username:").click()

        # create a test superuser account to login with
        superuser = set_up_superuser2()

        # fill in credentials w/ newly created superuser account
        print('--------------------------')
        print('logging in user...')
        page.get_by_label("Username:").fill(superuser.username)
        page.get_by_label("Username:").press("Tab")
        page.get_by_label("Password:").fill(env('DEFAULT_DATABASE_PASSWORD'))
        page.get_by_label("Password:").press("Enter")

        # check for any login errors
        login_errors = page.query_selector_all('.errornote')
        assert len(login_errors) == 0, f"\n {[x.text_content() for x in login_errors]}"

    except Exception as e:
        print(f'Error: setUp failed. Reason: {e}')

    return page


def can_load_page_without_errors(url, page):

    print(" THE URL: ", url)

    page.on("pageerror", lambda exc: print(" 1", exc))

    # check for any uncaught error logs in browser console
    uncaught_errors = []
    page.on("pageerror", lambda exc: uncaught_errors.append(exc))
    assert len(uncaught_errors) == 0, f"The following uncaught JavaScript errors were reported for {url}:\n{uncaught_errors}"
    print(" 2", uncaught_errors)

    page.on("console", lambda exc: print(" 3", exc))

    # check for any error logs in browser console
    error_logs = []
    page.on("console", lambda msg: error_logs.append(msg.text) if msg.type == "error" else None)
    assert len(error_logs) == 0, f"The following JavaScript errors were reported for {url}:\n{error_logs}"
    print(" 4", error_logs)

    # check if 'Page Not Found' in title tag of DOM
    title = page.title()
    assert 'Page Not Foundddd' not in title, '\n\n 404 error!'


# go to the production page
@pytest.mark.django_db(transaction=True)
def test_can_load_pages_without_error(login_to_myscore):
    # login to Myscore
    page = login_to_myscore
    # Retrieve testing objects
    testing_objects = get_testing_objects('all')
    # testing_objects = ['1538', '2576', '1822']
    # load up the page for each object
    for object in tqdm(testing_objects):
        url = f'http://localhost:{local_port}/production/{str(object.slug)}'
        # page.goto(url)
        page.goto(url, wait_until="networkidle")
        page.wait_for_timeout(2000)
        page.wait_for_load_state("load")
        # Wait for jQuery to become inactive
        page.wait_for_function('!window.jQuery.active')
        # Wait for the document to be in a complete state
        page.wait_for_function('document.readyState === "complete"')
        # check for errors
        can_load_page_without_errors(url, page)`
```

### Expected behavior

In the 'can_load_page_without_errors' function I am trying to assert that there are no errors in the console for the page. If there is an error it should get appended to the list, which would fail during the assert statement as it's checking to see if the list is empty.

### Actual behavior

I am using the page.on("pageerror") and page.on("console") methods to do this.

But when I try to append the error (from these methods) to a list, it doesn't work. I believe it may have something to do with the timing of things...I noticed that even though there ARE errors in the browser, when the test runs, it prints out my lists first (2) (4), even though they are not first in the code. Those lists are blank. It then prints out the values of the errors (1) (3). I am not sure if there is some async functionality going on that is causing this? I added a bunch of different wait methods in the test after going to the URL, but that does not help.

Below is the results when I run the program with the print statements:

```
THE URL:  http://localhost:8080/production/California
 2 []
 4 []
  3%|███▉                                                                                                                                       | 1/35 [00:04<02:43,  4.80s/it] 
3 jQuery.Deferred exception: overflowz is not defined ReferenceError: overflowz is not defined
    at time_period_filter_ajax (http://localhost:8080/staticfiles/js/dashboards/production.js:160:25)
    at HTMLDocument.<anonymous> (http://localhost:8080/staticfiles/js/dashboards/production.js:312:5)
    at e (http://localhost:8080/staticfiles/js/vendor.min.js:1:29815)
    at t (http://localhost:8080/staticfiles/js/vendor.min.js:1:30139) undefined
 1 overflowz is not defined
 THE URL:  http://localhost:8080/production/cherry-creek-division
 2 []
 4 []
  6%|███████▉                                                                                                                                   | 2/35 [00:08<02:23,  4.34s/it] 
3 jQuery.Deferred exception: overflowz is not defined ReferenceError: overflowz is not defined
    at time_period_filter_ajax (http://localhost:8080/staticfiles/js/dashboards/production.js:160:25)
    at HTMLDocument.<anonymous> (http://localhost:8080/staticfiles/js/dashboards/production.js:312:5)
    at e (http://localhost:8080/staticfiles/js/vendor.min.js:1:29815)
    at t (http://localhost:8080/staticfiles/js/vendor.min.js:1:30139) undefined
 3 jQuery.Deferred exception: overflowz is not defined ReferenceError: overflowz is not defined
    at time_period_filter_ajax (http://localhost:8080/staticfiles/js/dashboards/production.js:160:25)
    at HTMLDocument.<anonymous> (http://localhost:8080/staticfiles/js/dashboards/production.js:312:5)
    at e (http://localhost:8080/staticfiles/js/vendor.min.js:1:29815)
    at t (http://localhost:8080/staticfiles/js/vendor.min.js:1:30139) undefined
 1 overflowz is not defined
 1 overflowz is not defined
 THE URL:  http://localhost:8080/production/ne-management
 2 []
 4 []
  9%|███████████▉                                                                                                                               | 3/35 [00:11<02:06,  3.96s/it] 
3 jQuery.Deferred exception: overflowz is not defined ReferenceError: overflowz is not defined
    at time_period_filter_ajax (http://localhost:8080/staticfiles/js/dashboards/production.js:160:25)
    at HTMLDocument.<anonymous> (http://localhost:8080/staticfiles/js/dashboards/production.js:312:5)
    at e (http://localhost:8080/staticfiles/js/vendor.min.js:1:29815)
    at t (http://localhost:8080/staticfiles/js/vendor.min.js:1:30139) undefined
 3 jQuery.Deferred exception: overflowz is not defined ReferenceError: overflowz is not defined
    at time_period_filter_ajax (http://localhost:8080/staticfiles/js/dashboards/production.js:160:25)
    at HTMLDocument.<anonymous> (http://localhost:8080/staticfiles/js/dashboards/production.js:312:5)
    at e (http://localhost:8080/staticfiles/js/vendor.min.js:1:29815)
    at t (http://localhost:8080/staticfiles/js/vendor.min.js:1:30139) undefined
 3 jQuery.Deferred exception: overflowz is not defined ReferenceError: overflowz is not defined
    at time_period_filter_ajax (http://localhost:8080/staticfiles/js/dashboards/production.js:160:25)
    at HTMLDocument.<anonymous> (http://localhost:8080/staticfiles/js/dashboards/production.js:312:5)
    at e (http://localhost:8080/staticfiles/js/vendor.min.js:1:29815)
    at t (http://localhost:8080/staticfiles/js/vendor.min.js:1:30139) undefined
 1 overflowz is not defined
 1 overflowz is not defined
 1 overflowz is not defined
 THE URL:  http://localhost:8080/production/new-mexico-district-district
 2 []
 4 []
 11%|███████████████▉                                                                                                                           | 4/35 [00:14<01:55,  3.72s/it] 
3 jQuery.Deferred exception: overflowz is not defined ReferenceError: overflowz is not defined
    at time_period_filter_ajax (http://localhost:8080/staticfiles/js/dashboards/production.js:160:25)
    at HTMLDocument.<anonymous> (http://localhost:8080/staticfiles/js/dashboards/production.js:312:5)
    at e (http://localhost:8080/staticfiles/js/vendor.min.js:1:29815)
    at t (http://localhost:8080/staticfiles/js/vendor.min.js:1:30139) undefined
 3 jQuery.Deferred exception: overflowz is not defined ReferenceError: overflowz is not defined
    at time_period_filter_ajax (http://localhost:8080/staticfiles/js/dashboards/production.js:160:25)
    at HTMLDocument.<anonymous> (http://localhost:8080/staticfiles/js/dashboards/production.js:312:5)
    at e (http://localhost:8080/staticfiles/js/vendor.min.js:1:29815)
    at t (http://localhost:8080/staticfiles/js/vendor.min.js:1:30139) undefined
 3 jQuery.Deferred exception: overflowz is not defined ReferenceError: overflowz is not defined
    at time_period_filter_ajax (http://localhost:8080/staticfiles/js/dashboards/production.js:160:25)
    at HTMLDocument.<anonymous> (http://localhost:8080/staticfiles/js/dashboards/production.js:312:5)
    at e (http://localhost:8080/staticfiles/js/vendor.min.js:1:29815)
    at t (http://localhost:8080/staticfiles/js/vendor.min.js:1:30139) undefined
 3 jQuery.Deferred exception: overflowz is not defined ReferenceError: overflowz is not defined
    at time_period_filter_ajax (http://localhost:8080/staticfiles/js/dashboards/production.js:160:25)
    at HTMLDocument.<anonymous> (http://localhost:8080/staticfiles/js/dashboards/production.js:312:5)
    at e (http://localhost:8080/staticfiles/js/vendor.min.js:1:29815)
    at t (http://localhost:8080/staticfiles/js/vendor.min.js:1:30139) undefined
 1 overflowz is not defined
 1 overflowz is not defined
 1 overflowz is not defined
 1 overflowz is not defined
 THE URL:  http://localhost:8080/production/midwest-region-district
 2 []
 4 []
 14%|███████████████████▊                                                                                                                       | 5/35 [00:17<01:46,  3.55s/it] 
3 jQuery.Deferred exception: overflowz is not defined ReferenceError: overflowz is not defined
    at time_period_filter_ajax (http://localhost:8080/staticfiles/js/dashboards/production.js:160:25)
    at HTMLDocument.<anonymous> (http://localhost:8080/staticfiles/js/dashboards/production.js:312:5)
    at e (http://localhost:8080/staticfiles/js/vendor.min.js:1:29815)
    at t (http://localhost:8080/staticfiles/js/vendor.min.js:1:30139) undefined
 3 jQuery.Deferred exception: overflowz is not defined ReferenceError: overflowz is not defined
    at time_period_filter_ajax (http://localhost:8080/staticfiles/js/dashboards/production.js:160:25)
    at HTMLDocument.<anonymous> (http://localhost:8080/staticfiles/js/dashboards/production.js:312:5)
    at e (http://localhost:8080/staticfiles/js/vendor.min.js:1:29815)
    at t (http://localhost:8080/staticfiles/js/vendor.min.js:1:30139) undefined
 3 jQuery.Deferred exception: overflowz is not defined ReferenceError: overflowz is not defined
    at time_period_filter_ajax (http://localhost:8080/staticfiles/js/dashboards/production.js:160:25)
    at HTMLDocument.<anonymous> (http://localhost:8080/staticfiles/js/dashboards/production.js:312:5)
    at e (http://localhost:8080/staticfiles/js/vendor.min.js:1:29815)
    at t (http://localhost:8080/staticfiles/js/vendor.min.js:1:30139) undefined
 3 jQuery.Deferred exception: overflowz is not defined ReferenceError: overflowz is not defined
    at time_period_filter_ajax (http://localhost:8080/staticfiles/js/dashboards/production.js:160:25)
    at HTMLDocument.<anonymous> (http://localhost:8080/staticfiles/js/dashboards/production.js:312:5)
    at e (http://localhost:8080/staticfiles/js/vendor.min.js:1:29815)
    at t (http://localhost:8080/staticfiles/js/vendor.min.js:1:30139) undefined
 3 jQuery.Deferred exception: overflowz is not defined ReferenceError: overflowz is not defined
    at time_period_filter_ajax (http://localhost:8080/staticfiles/js/dashboards/production.js:160:25)
    at HTMLDocument.<anonymous> (http://localhost:8080/staticfiles/js/dashboards/production.js:312:5)
    at e (http://localhost:8080/staticfiles/js/vendor.min.js:1:29815)
    at t (http://localhost:8080/staticfiles/js/vendor.min.js:1:30139) undefined
 1 overflowz is not defined
 1 overflowz is not defined
 1 overflowz is not defined
 1 overflowz is not defined
 1 overflowz is not defined
 THE URL:  http://localhost:8080/production/northern-ca-district-district
 2 []
 4 []
 17%|███████████████████████▊                                          
```

### Environment

```Text
- Operating System: [Windows 10]
- CPU: []
- Browser: [Chromium]
- Python Version: [3.9]
- Other info:
```

**Comment by msu11y** [comment]
I figured out the solution, it was not a bug. I had to put the event handler before going to the page.

`      # build the URL of our page
        url = f'http://localhost:{local_port}/{app}/{str(object.slug)}'
        print(" PAGE URL: ", url)

        # append any uncaught javascript errors in browser error logs to list
        uncaught_errors = []
        page.on("pageerror", lambda exc: uncaught_errors.append(exc))

        # append any javascript errors in browser error logs to list
        error_logs = []
        page.on("console", lambda msg: error_logs.append(msg.text) if msg.type == "error" else None)

        # go to page once there are no more than 2 network connections for at least 500 milliseconds
        page.goto(url, wait_until="networkidle")

        # assert that 'Page Not Found' is not in title tag of DOM
        title = page.title()
        assert 'Page Not Found' not in title, '\n\n 404 error!'

        # assert that no uncaught javascript errors are in browser error logs
        assert len(uncaught_errors) == 0, f"The following uncaught JavaScript errors were reported for {url}:\n{uncaught_errors}"

        # assert that no javascript errors are in browser error logs
        assert len(error_logs) == 0, f"The following JavaScript errors were reported for {url}:\n{error_logs}"
`
