### ISSUE TITLE
[Bug]: context_browse.route is broken for requests initiated by service worker

### ISSUE THREAD

**Issue by LironHaroni** [microsoft/playwright-python#2346]
### Version

v1.42.0

### Steps to reproduce

`browser.route("https://example.com/g.json", lamda route: route.fulfill(json={"1": "6"}))
`
in serviceworker.js:
`const response = fetch("https://example.com/g.json").then(res => res.json())`

### Expected behavior

response in service worker should be `{ "1": "6" }`

### Actual behavior

```
ERROR    asyncio:base_events.py:1707 Task exception was never retrieved
future: <Task finished name='Task-43' coro=<BrowserContext._on_route() done, defined at /home/pwuser/.local/lib/python3.8/site-packages/playwright/_impl/_browser_context.py:221> exception=KeyError('frame')>
Traceback (most recent call last):
  File "/home/pwuser/.local/lib/python3.8/site-packages/playwright/_impl/_browser_context.py", line 223, in _on_route
    page = route.request._safe_page()
  File "/home/pwuser/.local/lib/python3.8/site-packages/playwright/_impl/_network.py", line 271, in _safe_page
    return cast("Frame", from_channel(self._initializer["frame"]))._page
KeyError: 'frame'
```

### Additional context

Created a fix for this issue: https://github.com/microsoft/playwright-python/pull/2345

### Environment

```Text
- Operating System: Ubuntu 22.04
- Browser: All
- Python Version: 3.12
- Other info:
```

**Comment by mxschmitt** [comment]
Thanks for the PR!
