### ISSUE TITLE
NotImplemented Error using asycn_playwright with click

### ISSUE THREAD

**Issue by auphofBSF** [microsoft/playwright-python#239]
I have some automation scripts written with pyppeteer that I would like to use with playwright, these scripts are windows CLI scripts using the asyncio wrapped click module, asyncclick, when I port the working example below to playwright I get a NotImplemented Error
Thank you for what looks like a very promising browser automation and test module.

## NotImplemented Error
```
(Tools20W39Py376) PS C:\Users\<USER>\SANDBOXplaywright> python .\async_click_playwright.py
Traceback (most recent call last):
  File ".\async_click_playwright.py", line 24, in <module>
    main(_anyio_backend="asyncio")
  File "c:\users\<USER>\axternal\asyncclick\asyncclick\core.py", line 865, in __call__
    return anyio.run(self._main, main, args, kwargs, backend=_anyio_backend)
  File "C:\Users\<USER>\Anaconda3\envs\Tools20W39Py376\lib\site-packages\anyio\_core\_eventloop.py", line 52, in run
    return asynclib.run(func, *args, **backend_options)  # type: ignore
  File "C:\Users\<USER>\Anaconda3\envs\Tools20W39Py376\lib\site-packages\anyio\_backends\_asyncio.py", line 160, in run
    return native_run(wrapper(), debug=debug)
  File "C:\Users\<USER>\Anaconda3\envs\Tools20W39Py376\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\<USER>\Anaconda3\envs\Tools20W39Py376\lib\asyncio\base_events.py", line 583, in run_until_complete
    return future.result()
  File "C:\Users\<USER>\Anaconda3\envs\Tools20W39Py376\lib\site-packages\anyio\_backends\_asyncio.py", line 155, in wrapper
    return await func(*args)
  File "c:\users\<USER>\axternal\asyncclick\asyncclick\core.py", line 868, in _main
    return await main(*args, **kwargs)
  File "c:\users\<USER>\axternal\asyncclick\asyncclick\core.py", line 814, in main
    rv = await self.invoke(ctx)
  File "c:\users\<USER>\axternal\asyncclick\asyncclick\core.py", line 1105, in invoke
    return await ctx.invoke(self.callback, **ctx.params)
  File "c:\users\<USER>\axternal\asyncclick\asyncclick\core.py", line 644, in invoke
    rv = await rv
  File ".\async_click_playwright.py", line 9, in main
    playwright = await async_playwright().start()
  File "C:\Users\<USER>\Anaconda3\envs\Tools20W39Py376\lib\site-packages\playwright\main.py", line 119, in start
    return await self.__aenter__()
  File "C:\Users\<USER>\Anaconda3\envs\Tools20W39Py376\lib\site-packages\playwright\main.py", line 110, in __aenter__
    self._connection = await run_driver_async()
  File "C:\Users\<USER>\Anaconda3\envs\Tools20W39Py376\lib\site-packages\playwright\main.py", line 62, in run_driver_async
    limit=32768,
  File "C:\Users\<USER>\Anaconda3\envs\Tools20W39Py376\lib\asyncio\subprocess.py", line 217, in create_subprocess_exec
    stderr=stderr, **kwds)
  File "C:\Users\<USER>\Anaconda3\envs\Tools20W39Py376\lib\asyncio\base_events.py", line 1540, in subprocess_exec
    bufsize, **kwargs)
  File "C:\Users\<USER>\Anaconda3\envs\Tools20W39Py376\lib\asyncio\base_events.py", line 462, in _make_subprocess_transport
    raise NotImplementedError
```
## Failing Code
The playwright code `async_click_playwright.py` running in Python 3.7.6  on Windows 10 x64  with latest asyncclick fails with the NotImplementedError
```python
import asyncio
import anyio
import asyncclick as click
from  playwright import async_playwright

@click.command()
@click.argument('url',default="http://whatsmyuseragent.org/")
async def main(url):
    playwright = await async_playwright().start()
    browser=await playwright.launch(headless=False)
    print("Browser Launched-----------------")
    page = await browser.newPage()
    print("Browser new Page created ")
    await asyncio.sleep(2)
    print(f"Goto {url} ")
    await page.goto(url)
    await asyncio.sleep(10)
    await browser.close()
    print("------------------------")

if __name__ == "__main__":
    main(_anyio_backend="asyncio")

    

```

## Working pyppetteer example
The following pyppeteer code works well

```python
import asyncio
import anyio
import asyncclick as click
import pyppeteer

@click.command()
@click.argument('url',default="http://whatsmyuseragent.org/")
async def main(url):
    browser=await pyppeteer.launch(headless=False)
    print("Browser Launched-----------------")
    page = await browser.newPage()
    print("Browser new Page created ")
    await asyncio.sleep(2)
    print(f"Goto {url} ")
    await page.goto(url)
    await asyncio.sleep(10)
    await browser.close()
    print("------------------------")

if __name__ == "__main__":
    main(_anyio_backend="asyncio")

```

**Comment by auphofBSF** [comment]
Further debugging, it appears to be an issue in `asyncclick` where by  the event loop policy does not default to asyncio.WindowsProactorEventLoopPolicy()
temporary modifying `asyncclick` and setting the `backend_options={'policy':asyncio.WindowsProactorEventLoopPolicy() }` has worked.  I will raise an issue/PR on the asyncclick module
