### ISSUE TITLE
[Bug]: Run in Fastapi async request  Error

### ISSUE THREAD

**Issue by chenjinjun** [microsoft/playwright-python#2480]
### Version

1.44.0

### Steps to reproduce

Running the code in the demo is normal, but running it on the asynchronous interface of the FastAPI will result in an error

### Expected behavior

Task exception was never retrieved
future: <Task finished name='Task-11' coro=<Connection.run() done, defined at d:\SourceCode\AiFaProject\apiserver_aifa\.venv\lib\site-packages\playwright\_impl\_connection.py:265> exception=NotImplementedError()>
Traceback (most recent call last):
  File "d:\SourceCode\AiFaProject\apiserver_aifa\.venv\lib\site-packages\playwright\_impl\_connection.py", line 272, in run
    await self._transport.connect()
  File "d:\SourceCode\AiFaProject\apiserver_aifa\.venv\lib\site-packages\playwright\_impl\_transport.py", line 133, in connect
    raise exc
  File "d:\SourceCode\AiFaProject\apiserver_aifa\.venv\lib\site-packages\playwright\_impl\_transport.py", line 120, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "c:\Users\pc\AppData\Local\Programs\Python\Python310\lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "c:\Users\pc\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1681, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "c:\Users\pc\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 498, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError

### Actual behavior

Task exception was never retrieved

### Environment

```Text
- Operating System: [Ubuntu 22.04]
- CPU: [arm64]
- Browser: [All, Chromium, Firefox, WebKit]
- Python Version: [3.12]
- Other info:
```

**Comment by chenjinjun** [comment]
Closing the reload interface of Uviorn can solve this problem
