### ISSUE TITLE
[Bug]: .chromium.connect_over_cdp ，Timeout 2000ms exceeded

### ISSUE THREAD

**Issue by tdRPA** [microsoft/playwright-python#2485]
### Version

1.45.0

### Steps to reproduce

1. connect to Chrome
2. after several hours connect again
3. timeout error

### Expected behavior

be able to connect to Chrome

### Actual behavior

Timeout 2000ms exceeded

### Additional context

>>> from playwright.sync_api import sync_playwright
>>> play=sync_playwright()
>>> 
>>> playAPI=play.start()

>>> currentBrowser=playAPI.chromium.connect_over_cdp('http://127.0.0.1:%s' % '9222',timeout=2000)
Traceback (most recent call last):
  File "<pyshell#8>", line 1, in <module>
    currentBrowser=playAPI.chromium.connect_over_cdp('http://127.0.0.1:%s' % '9222',timeout=2000)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\sync_api\_generated.py", line 14516, in connect_over_cdp
    self._sync(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\_impl\_sync_base.py", line 115, in _sync
    return task.result()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\_impl\_browser_type.py", line 172, in connect_over_cdp
    response = await self._channel.send_return_as_dict("connectOverCDP", params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\_impl\_connection.py", line 64, in send_return_as_dict
    return await self._connection.wrap_api_call(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\_impl\_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: BrowserType.connect_over_cdp: Timeout 2000ms exceeded.
Call log:
<ws preparing> retrieving websocket url from http://127.0.0.1:9222
  - <ws connecting> ws://127.0.0.1:9222/devtools/browser/8f24caea-3a04-4b66-860d-a8d8e2d10927
  - <ws connected> ws://127.0.0.1:9222/devtools/browser/8f24caea-3a04-4b66-860d-a8d8e2d10927

### Environment

```Text
- Operating System: [win 2016 server]
- CPU: [amd64]
- Browser: [Chrome 126.0.6478.127]
- Python Version: [3.8.10]
- Other info:
```

**Comment by mxschmitt** [comment]
Looks like the Chromium you are connecting to takes more than 2 seconds to accept the connection, have you tried to increase it to e.g. `30_000`? Maybe the Chromium is not responsive anymore. Looks more like a Chromium bug, which is probably also reproducible via Puppeteer so I'd try to file it against crbug.com

**Comment by tdRPA** [comment]
> Looks like the Chromium you are connecting to takes more than 2 seconds to accept the connection, have you tried to increase it to e.g. `30_000`? Maybe the Chromium is not responsive anymore. Looks more like a Chromium bug, which is probably also reproducible via Puppeteer so I'd try to file it against https://crbug.com

I am sure it's not related to the timeout seconds. Normally to make a connection to local port, 2 seconds is enough.

Everytime when I first lanched chrome manully, it works well. But sometimes after I maunully using chrome and open some tabs for pages, it can not be connected. It's very hard to know when and how it happend.
