### ISSUE TITLE
handleSIGTERM=False causes UnhandledPromiseRejectionWarning and closes a browser

### ISSUE THREAD

**Issue by tkratky** [microsoft/playwright-python#291]
I'm getting UnhandledPromiseRejectionWarning Error and the browser is closed when trying to simulate test failure which shouldn't close the browser.

The [documentation](https://microsoft.github.io/playwright-python/async_api.html) says that I should set the **handleSIGTERM** to `False` and it shouldn't close the browser by the end of the run, right? So I did it (see code example).

> handleSIGTERM : Optional[bool] Close the browser process on SIGTERM. Defaults to true.

Environment:
node v15.0.1
Python 3.8.0
MacOS Catalina 10.15.7 
playwright 0.152.0
Code example:
```
import asyncio

from playwright import async_playwright


async def main():
    playwright = await async_playwright().start()
    browser = await playwright.chromium.launch(headless=False, handleSIGTERM=False, handleSIGHUP=False)
    page = await browser.newPage()
    page.setDefaultTimeout(timeout=5000)

    await page.goto('https://google.com/')

    # the following row simulates test failure
    await page.waitForSelector('input[name="q"]', state='hidden')

    await browser.close()
    await playwright.stop()


if __name__ == "__main__":
    asyncio.run(main())
```
The unexpected behavior is that the browser gets closed and node displays the following output:
```
(node:28715) UnhandledPromiseRejectionWarning: Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:154:25)
    at writeGeneric (internal/stream_base_commons.js:145:3)
    at Socket._writeGeneric (net.js:786:11)
    at Socket._write (net.js:798:8)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at Transport.send (/snapshot/playwright-cli/node_modules/playwright/lib/protocol/transport.js:38:25)
    at DispatcherConnection.onmessage (/snapshot/playwright-cli/lib/driver.js:49:61)
    at DispatcherConnection.sendMessageToClient (/snapshot/playwright-cli/node_modules/playwright/lib/dispatchers/dispatcher.js:130:14)
(node:28715) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:28715) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:28715) UnhandledPromiseRejectionWarning: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:399:19)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at Transport.send (/snapshot/playwright-cli/node_modules/playwright/lib/protocol/transport.js:38:25)
    at DispatcherConnection.onmessage (/snapshot/playwright-cli/lib/driver.js:49:61)
    at DispatcherConnection.sendMessageToClient (/snapshot/playwright-cli/node_modules/playwright/lib/dispatchers/dispatcher.js:130:14)
    at BrowserContextDispatcher._dispatchEvent (/snapshot/playwright-cli/node_modules/playwright/lib/dispatchers/dispatcher.js:70:26)
    at CRBrowserContext.<anonymous> (/snapshot/playwright-cli/node_modules/playwright/lib/dispatchers/browserContextDispatcher.js:33:18)
    at CRBrowserContext.emit (events.js:315:20)
    at CRBrowserContext._didCloseInternal (/snapshot/playwright-cli/node_modules/playwright/lib/server/browserContext.js:102:14)
(node:28715) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```
The same issue occurs with `sync_playwright`: the browser gets closed.

**Comment by pavelfeldman** [comment]
> The documentation says that I should set the handleSIGTERM to False and it shouldn't close the browser by the end of the run, right? So I did it (see code example).

`handle*` flags define how program processes external signals, which you don't seem to have. Nothing is force-closing the process, it simply raises an exception. You can try/catch that exception and the control flow will go further.

Your test times out while waiting for the selector and here is what I get in my console:

```
playwright.helper.TimeoutError: Timeout 5000ms exceeded.
=========================== logs ===========================
waiting for selector "input[name="q"]" to be hidden
  selector resolved to visible <input name="q" value="" type="text" autofocus="" title…/>
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
(node:28541) UnhandledPromiseRejectionWarning: Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:154:25)
    at writeGeneric (internal/stream_base_commons.js:145:3)
    at Socket._writeGeneric (net.js:786:11)
    at Socket._write (net.js:798:8)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at Transport.send (/snapshot/playwright-cli/node_modules/playwright/lib/protocol/transport.js:38:25)
    at DispatcherConnection.onmessage (/snapshot/playwright-cli/lib/driver.js:49:61)
    at DispatcherConnection.sendMessageToClient (/snapshot/playwright-cli/node_modules/playwright/lib/dispatchers/dispatcher.js:129:14)
```

Which is expected. Using timeout for this might flake, so I wonder what your end goal is, there might be a more elegant solution to your problem.

**Comment by tkratky** [comment]
Thank you for the answer,
the force-close of the program closes the browser as well. 

In general, we would like to define the boolean flag `keep_browser_on_failure=True` so the browser stays open (usually when implementing new test cases) when a program is interrupted (force-quit) or the test fails (we can catch the exception and skip `browser.close()` method). In both cases, the browser is closed even when `browser.close()` method is not called. You can reproduce it when you remove  `await browser.close()` and `await playwright.stop()` lines in the code example.

**Comment by pavelfeldman** [comment]
Right, so what the test frameworks do in that case is they try/catch the tests and perform the necessary tear down. We don't close the browsers, your program exists with an exception and hence the browsers are closed, basically no program - no browsers...

**Comment by pavelfeldman** [comment]
Check out how https://github.com/microsoft/playwright-pytest handles it for example, you can timeout as much as you'd like in a test and the browser will keep running!

**Comment by tkratky** [comment]
You are right, thank you very much for your answer. I think we can close this issue.
