### ISSUE TITLE
Interactive mode (REPL) Error

### ISSUE THREAD

**Issue by zhonghai9967** [microsoft/playwright-python#310]
from playwright import sync_playwright
playwright = sync_playwright().start()
==>
AttributeError: 'NoneType' object has no attribute 'fileno'
why?
Thank you！

**Comment by mxschmitt** [comment]
Hi, do you a full stack trace of it available? In which REPL are you executing it?

**Comment by zhonghai9967** [comment]
python ide
win10

**Comment by dld8888** [comment]
>>> from playwright import sync_playwright
>>> playwright = sync_playwright().start()
Traceback (most recent call last):
  File "C:\Python378\lib\site-packages\playwright\main.py", line 49, in _get_stderr_fileno
    return sys.stderr.fileno()
io.UnsupportedOperation: fileno

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    playwright = sync_playwright().start()
  File "C:\Python378\lib\site-packages\playwright\__init__.py", line 34, in sync_playwright
    return SyncPlaywrightContextManager()
  File "C:\Python378\lib\site-packages\playwright\main.py", line 81, in __init__
    self._connection = run_driver()
  File "C:\Python378\lib\site-packages\playwright\main.py", line 76, in run_driver
    return loop.run_until_complete(run_driver_async())
  File "C:\Python378\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Python378\lib\site-packages\playwright\main.py", line 61, in run_driver_async
    stderr=_get_stderr_fileno(),
  File "C:\Python378\lib\site-packages\playwright\main.py", line 54, in _get_stderr_fileno
    return sys.__stderr__.fileno()
**AttributeError: 'NoneType' object has no attribute 'fileno'**

**Comment by dld8888** [comment]
>>> from playwright import sync_playwright
>>> playwright = sync_playwright().start()
Traceback (most recent call last):
  File "C:\Python378\lib\site-packages\playwright\main.py", line 49, in _get_stderr_fileno
    return sys.stderr.fileno()
io.UnsupportedOperation: fileno

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    playwright = sync_playwright().start()
  File "C:\Python378\lib\site-packages\playwright\__init__.py", line 34, in sync_playwright
    return SyncPlaywrightContextManager()
  File "C:\Python378\lib\site-packages\playwright\main.py", line 81, in __init__
    self._connection = run_driver()
  File "C:\Python378\lib\site-packages\playwright\main.py", line 76, in run_driver
    return loop.run_until_complete(run_driver_async())
  File "C:\Python378\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Python378\lib\site-packages\playwright\main.py", line 61, in run_driver_async
    stderr=_get_stderr_fileno(),
  File "C:\Python378\lib\site-packages\playwright\main.py", line 54, in _get_stderr_fileno
    return sys.__stderr__.fileno()
**AttributeError: 'NoneType' object has no attribute 'fileno'**

**Comment by mxschmitt** [comment]
Probably we should add a check if the attribute exists or another try/catch block to the existing try/catch block:

https://github.com/microsoft/playwright-python/blob/master/playwright/main.py#L54

**Comment by pavelfeldman** [comment]
> Probably we should add a check if the attribute exists or another try/catch block to the existing try/catch block:

Looks like this would be going further into the hack path. I originally thought what you did there was an established solution, but it looks fishy. Shouldn't we simply pipe the stderr of a spawn process?

**Comment by mxschmitt** [comment]
> > Probably we should add a check if the attribute exists or another try/catch block to the existing try/catch block:
> 
> Looks like this would be going further into the hack path. I originally thought what you did there was an established solution, but it looks fishy. Shouldn't we simply pipe the stderr of a spawn process?


Unfortunately we need some kind of hacky solution since pytest-xdist monkey patches it and its not working if we are just using the stderr of the spawn process. (pytest-xdist is very common).

**Comment by pavelfeldman** [comment]
> Unfortunately we need some kind of hacky solution

I am not sure I get it. My understanding is that users can use sys.stderr from their tests that will be running from child processes. That means sys.stderr should function somehow. If it does not have an underlying descriptor, we could still pump child process stderr into it, what do I miss?

**Comment by zhonghai9967** [comment]
13 days have passed, when will this problem be solved? Thank you

**Comment by mxschmitt** [comment]
@zhonghai9967 there was a fix applied and a new version got released. 

```
pip install playwright==0.162.2

```

**Comment by zhonghai9967** [comment]
pip install playwright==0.162.2
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: playwright==0.162.2 in c:\python37\lib\site-packages (0.162.2)
Requirement already satisfied: typing-extensions in c:\python37\lib\site-packages (from playwright==0.162.2) (3.7.4.3)
Requirement already satisfied: pyee>=8.0.1 in c:\python37\lib\site-packages (from playwright==0.162.2) (8.1.0)
Requirement already satisfied: greenlet==1.0a1 in c:\python37\lib\site-packages (from playwright==0.162.2) (1.0a1)

>>> from playwright import sync_playwright
>>> **playwright = sync_playwright().start()**
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\playwright\main.py", line 49, in _get_stderr_fileno
    return sys.stderr.fileno()
io.UnsupportedOperation: fileno

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    playwright = sync_playwright().start()
  File "C:\Python37\lib\site-packages\playwright\__init__.py", line 34, in sync_playwright
    return SyncPlaywrightContextManager()
  File "C:\Python37\lib\site-packages\playwright\main.py", line 81, in __init__
    self._connection = run_driver()
  File "C:\Python37\lib\site-packages\playwright\main.py", line 76, in run_driver
    return loop.run_until_complete(run_driver_async())
  File "C:\Python37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Python37\lib\site-packages\playwright\main.py", line 61, in run_driver_async
    stderr=_get_stderr_fileno(),
  File "C:\Python37\lib\site-packages\playwright\main.py", line 54, in _get_stderr_fileno
    return sys.__stderr__.fileno()
**AttributeError: 'NoneType' object has no attribute 'fileno'**

**Comment by zhonghai9967** [comment]
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:01:55) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

**Comment by dld8888** [comment]
playwright==0.162.2
The problem still exists.

**Comment by dld8888** [comment]
@mxschmitt 
playwright==0.162.2
The problem still exists.
