### ISSUE TITLE
[INSTALLATION] - Playwright installation fails

### ISSUE THREAD

**Issue by robindz** [microsoft/playwright-python#323]
**Describe the error**

Running the playwright install command results in the following error

```
pi@raspberrypi:~ $ sudo python3.8 -m playwright install
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/site-packages/playwright/__main__.py", line 17, in <module>
    main()
  File "/usr/local/lib/python3.8/site-packages/playwright/main.py", line 135, in main
    subprocess.run([str(driver_executable), *sys.argv[1:]], env=my_env)
  File "/usr/local/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/site-packages/playwright/driver/playwright-cli'
```

**OS**
Linux raspberrypi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux

**Additional context**
`sudo pip3.8 install playwright` executed just fine, so I'm unsure what went wrong.

If any more information is required, I'll be happy to provide it.

**Comment by kumaraditya303** [comment]
Currently arm architecture isn't supported!

**Comment by robindz** [comment]
@kumaraditya303 I see, is ARM support something that is planned to be added or no plans for ARM support so far?

**Comment by kumaraditya303** [comment]
There isn't plan of supporting arm architecture so far.

**Comment by robindz** [comment]
Ok, well, thank you for the quick replies!

**Comment by glops** [comment]
Hi!
I made a Dockerfile to install playwright-python on Raspberry pi. 
I tested it only on raspberry pi 4 64bits. It may work on older raspberry
[playwright-rpi4](https://github.com/glops/playwright-rpi4)
