### ISSUE TITLE
Documentation for handling timeout exceptions

### ISSUE THREAD

**Issue by kbreit** [microsoft/playwright-python#326]
I am setting timeout to 10 seconds (10000ms) and when it times out it's raising an exception. This looks very similar to #291 but I'm not seeing how to catch the exception.

```
python3: src/unix/core.c:932: uv__io_stop: Assertion `loop->watchers[w->fd] == w' failed.
(node:29246) UnhandledPromiseRejectionWarning: Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:154:25)
    at writeGeneric (internal/stream_base_commons.js:145:3)
    at Socket._writeGeneric (net.js:786:11)
    at Socket._write (net.js:798:8)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at Transport.send (/snapshot/playwright-cli/node_modules/playwright/lib/protocol/transport.js:38:25)
    at DispatcherConnection.onmessage (/snapshot/playwright-cli/lib/driver.js:49:61)
    at DispatcherConnection.sendMessageToClient (/snapshot/playwright-cli/node_modules/playwright/lib/dispatchers/dispatcher.js:130:14)
```

Here's the relevant code. It's broken out into functions and classes so this is a little abbreviated.

```
    page = await browser.newPage()
    data = await download_price(url, page)
    ...
    from playwright.helper import TimeoutError
    try:
        page.setDefaultNavigationTimeout(10000)
        await page.goto(self.url)
    except TimeoutError:
        logger.info(f'HTTP timeout for {self.url}')
        return (None, None)
```

When I increase the timeout time to 20 seconds, or something longer that works, it executes just fine as it never hits the timeout. Should I be catching the TimeoutError somewhere else?

**Comment by pavelfeldman** [comment]
Your exception does not seem to be about the timeout. I can catch the timeout one:

Your code looks good. I'm trying following and it works as expected:

```python
import asyncio
from playwright import async_playwright
from playwright.helper import TimeoutError

async def main():
    async with async_playwright() as p:
        for browser_type in [p.chromium]:
            browser = await browser_type.launch()
            page = await browser.newPage()
            try:
                page.setDefaultNavigationTimeout(10)
                await page.goto("https://theverge.com")
            except TimeoutError:
                print('HTTP timeout')

asyncio.get_event_loop().run_until_complete(main())
```

But your seems to be related to an internal PIP error in the libuv (Node internals). And you are saying it triggers on Timeout error when you make timeout small? Is there a way to further reduce your repro test case and share it with us?

**Comment by kbreit** [comment]
@pavelfeldman Sorry about the delay getting back to you. It worked fine in Chrome but when I changed it to `p.firefox` it threw an exception.

The code was otherwise the same as yours.

```
(venv) playwright % ./timeout.py
HTTP timeout
(node:11282) UnhandledPromiseRejectionWarning: Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:154:25)
    at writeGeneric (internal/stream_base_commons.js:145:3)
    at Socket._writeGeneric (net.js:786:11)
    at Socket._write (net.js:798:8)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at Transport.send (/snapshot/playwright-cli/node_modules/playwright/lib/protocol/transport.js:38:25)
    at DispatcherConnection.onmessage (/snapshot/playwright-cli/lib/driver.js:49:61)
    at DispatcherConnection.sendMessageToClient (/snapshot/playwright-cli/node_modules/playwright/lib/dispatchers/dispatcher.js:129:14)
(node:11282) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11282) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:11282) UnhandledPromiseRejectionWarning: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
```

**Comment by pavelfeldman** [comment]
It prints `HTTP timeout` to me...

**Comment by kbreit** [comment]
I'm going to close this for now as I've been able to work around it and we can't reproduce it. If I run into it again, I'll reopen though. Thank you!

**Comment by perymerdeka** [comment]
where Timeout Error class? I want to handle using the backoff module but I can't find it

**Comment by perymerdeka** [comment]
i found it here: https://playwright.dev/python/docs/api/class-timeouterror
