### ISSUE TITLE
Protocol error (Page.setScreenSizeOverride): The page has been closed.

### ISSUE THREAD

**Issue by srudyanto** [microsoft/playwright-python#327]
I've got this error message when trying to running on my notebook. FYI this script is working fine on the AWS server.

Traceback (most recent call last):
  File "tiktokapi.py", line 4, in <module>
    api = TikTokApi()
  File "/home/lubuntu/.local/lib/python3.7/site-packages/TikTokApi/tiktok.py", line 49, in __init__
    self.browser = browser(**kwargs)
  File "/home/lubuntu/.local/lib/python3.7/site-packages/TikTokApi/browser.py", line 85, in __init__
    page = self.create_page(set_useragent=True)
  File "/home/lubuntu/.local/lib/python3.7/site-packages/TikTokApi/browser.py", line 119, in create_page
    page = context.newPage()
  File "/home/lubuntu/.local/lib/python3.7/site-packages/playwright/sync_api.py", line 5660, in newPage
    return mapping.from_impl(self._sync(self._impl_obj.newPage()))
  File "/home/lubuntu/.local/lib/python3.7/site-packages/playwright/sync_base.py", line 107, in _sync
    return future.result()
  File "/home/lubuntu/.local/lib/python3.7/site-packages/playwright/browser_context.py", line 118, in newPage
    return from_channel(await self._channel.send("newPage"))
  File "/home/lubuntu/.local/lib/python3.7/site-packages/playwright/connection.py", line 39, in send
    result = await callback.future
playwright.helper.Error: Protocol error (Page.setScreenSizeOverride): The page has been closed.
Exception ignored in: <greenlet.greenlet object at 0x7fd103de0290>

my configuration :
- I5 with NVIDIA VGA
- Ubuntu 18.04

how to solve this problem. thanks

**Comment by pavelfeldman** [comment]
Please set the `DEBUG=pw:browser*` environment variable, it should give us a clue on why browser exited.

**Comment by marcelogrsp** [comment]
> DEBUG=pw:browser*

Why was this closed? I am getting the same error, what is the solution please?
