### ISSUE TITLE
Inspect fails to retrieve module inside frozen app

### ISSUE THREAD

**Issue by tumregels** [microsoft/playwright-python#342]
# Description of the issue

when freezing playwright with [pyinstaller](https://github.com/pyinstaller/pyinstaller) the assertion in [`get_file_dirname`](https://github.com/microsoft/playwright-python/blob/master/playwright/path_utils.py#L19-L24) fails

```
  File "main.py", line 6, in <module>
    with sync_playwright() as p:
  File "playwright/__init__.py", line 34, in sync_playwright
  File "playwright/main.py", line 81, in __init__
  File "playwright/main.py", line 76, in run_driver
  File "asyncio/base_events.py", line 587, in run_until_complete
  File "playwright/main.py", line 44, in run_driver_async
  File "playwright/main.py", line 36, in compute_driver_executable
  File "playwright/path_utils.py", line 23, in get_file_dirname
AssertionError
```

The reason is that the inspect module fails to find the module on the following lines inside [`get_file_dirname`](https://github.com/microsoft/playwright-python/blob/master/playwright/path_utils.py#L19-L24)

```python
frame = inspect.stack()[1]
module = inspect.getmodule(frame[0])
```

# Context information (for bug reports)

* version of python: 3.7.9
* version of pyinstaller: 4.1
* version of playwright-python: Version 0.162.1
* platform: GNU/Linux (Ubuntu 18.04 LTS)

# Reproducing the bug

install packages

    $ pip install playwright pyinstaller

install the browsers inside playwright

    $ PLAYWRIGHT_BROWSERS_PATH=0 python -m playwright install

create `main.py`

```python
# main.py
import sys
from pathlib import Path
from playwright import sync_playwright

with sync_playwright() as p:
    for browser_type in [p.chromium]:
        browser = browser_type.launch(
            headless=False,
            executablePath=Path(sys.modules['playwright'].__file__).parent / 'driver' / '.local-browsers' / 'chromium-827102' / 'chrome-linux' / 'chrome')
        page = browser.newPage()
        page.goto('http://whatsmyuseragent.org/')
        page.screenshot(path=f'example-{browser_type.name}.png')
        browser.close()
```

freeze into single binary file with pyinstaller

    $ pyinstaller -F main.py

execute the binary file

```
$ ./dist/main 
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    with sync_playwright() as p:
  File "playwright/__init__.py", line 34, in sync_playwright
  File "playwright/main.py", line 81, in __init__
  File "playwright/main.py", line 76, in run_driver
  File "asyncio/base_events.py", line 587, in run_until_complete
  File "playwright/main.py", line 44, in run_driver_async
  File "playwright/main.py", line 36, in compute_driver_executable
  File "playwright/path_utils.py", line 23, in get_file_dirname
AssertionError
```

**Comment by niemtin6789** [comment]
i use it for window . but it is still error ""chromium" browser was not found" ( i add executablePath like you). please hepl me.

thanks you so much

**Comment by niemtin6789** [comment]
how can i download chromium-827102 file? . many thanks

**Comment by pavelfeldman** [comment]
You probably missed 

```sh
PLAYWRIGHT_BROWSERS_PATH=0 python -m playwright install
```

from above. Following the report steps now works. There was an issue, but it has since been fixed.

**Comment by niemtin6789** [comment]
i use window. i use command "-m playwright install". but when i run file it still error "[15660] Failed to execute script mainwindow"
thanks

**Comment by mbalslow** [comment]
Hopefully this can help anyone struggling to compile a Playwright script with Pyinstaller.

Here is how I have managed to make a template for compiling a Playwright script with Pyinstaller **on Windows**.

A basic main.py:
```
from sys import modules
from os import listdir, path
from pathlib import Path
from typing import Union
from playwright import sync_api


def get_executable_path() -> Union[str, None]:
    parent_folder = Path(modules['playwright'].__file__).parent / 'driver' / 'package' / '.local-browsers'

    if not path.exists(parent_folder):
        return None

    child_folders = [name for name in listdir(parent_folder) if path.isdir(parent_folder / name) and name.strip().lower().startswith('chromium')]

    if len(child_folders) != 1:
        return None

    chromium_folder = child_folders[0]

    return parent_folder / chromium_folder / 'chrome-win' / 'chrome.exe'


with sync_api.sync_playwright() as p:
    executable_path = get_executable_path()

    if executable_path:
        browser = p.chromium.launch(
            headless=False,
            executable_path=executable_path
        )
        page = browser.new_page()
        page.goto("http://playwright.dev")
        print(page.title())
        browser.close()
```

A compile.bat to automate the install and Pyinstaller process:
```
CALL py -m venv venv
CALL venv\scripts\activate
CALL pip install playwright pyinstaller
CALL SET PLAYWRIGHT_BROWSERS_PATH=0
CALL playwright install chromium
CALL pyinstaller -y -F main.py --add-data "venv/lib/site-packages/playwright/driver;playwright/driver"
```

Cheers.

**Comment by ThomasTrovon** [comment]
**I PROPOSE ANOTHER SOLUTION**

I use Windows 10. I tried [pavelfeldman](https://github.com/pavelfeldman) solution...

![image](https://user-images.githubusercontent.com/10778234/153954899-33e31710-8fcc-4b04-8848-c046207adc8d.png)

Did not work! I don't think I understand the correct way to do this in Windows.

I tried the [mbalslow](https://github.com/mbalslow) solution and it worked! However, the basic file, which was 8.52 MB, ended up being 137 MB, which, of course, I was not satisfied with.

I have a lot of professional applications (that I make to sell) that I use selenium. And they are on average 14 MB in size. Because, the way that I make, my application does not load the binaries. She installs the binaries on the client's computer, and uses them. That's why I get such a lean application, using the following method:

![image](https://user-images.githubusercontent.com/10778234/153955931-6bbae813-9724-45c8-9b47-4b0fa15d00f1.png)

That's when I thought, "What if, like with selenium, I didn't need to load the binaries into my executable? What if I could just install them on first run on my client's computer, and then use it in cache like me do with selenium?"

So I started looking for a way to install the binaries through playwright, in a folder on my client, and use that in my application as a cache. But I didn't find such a solution (Maybe there is, and I've just been unable to find it).

And then came another idea: "I currently only develop applications for Windows. Practically every Windows nowadays has: either a Microsoft Edge, or a Google Chrome, or a Firefox. What if I just take the directory of those browsers, and use them?"

So, I developed a way to get, from the windows registry, one of the directories of the browsers binaries, installed on the computer, and then, tell playwright to use it (not done in firefox yet, but it is possible to do):

![image](https://user-images.githubusercontent.com/10778234/153957707-a93687bb-036d-4ba8-bffd-5f32910dfc30.png)

This is an amateur solution made by me, to try to get around the problem. Maybe later it will be possible to do in a more optimized way, this idea of taking the binaries that already exist in the system, and just using them. Don't take into account the form made, but the idea behind it.

So, putting in focus, the heart the idea is: Use the binaries already existing in the system, just pointing to them!

**CONCLUSION:** 
When I run this code through PyCharm it works perfectly!
When I compile with Pyinstaller, and run it, I get the following error in my log.log file (because I catch the error, and Write it in a file)

![image](https://user-images.githubusercontent.com/10778234/153958760-eccf7ecd-5aa5-4df3-be51-d93cd3f6f0a4.png)

I can't understand why this works in PyCharm, and not with PyInstaller, since the directory, as you can see in the log.log, is correct! Why doesn't it work in PyInstaller, if I'm pointing correctly to the binary directory?

I believe it is a great idea/solution to be officially applied to the tool: to give the option to use the binaries that already exist on the computer.
I just haven't been able to execute it perfectly yet. Does anyone have any ideas? Did you see my mistake?

Sources Files: 
[source.zip](https://github.com/microsoft/playwright-python/files/8064453/source.zip)

Thanks for your patience and attention...

**Comment by mxschmitt** [comment]
You don't need to determine the browser paths yourself, we do this already for you and it's called channels: https://playwright.dev/python/docs/browsers#google-chrome--microsoft-edge

Also the command is not working because environment prefixing works only in Linux. In your case you need the PowerShell or batch approach. See here for a how to guide: https://playwright.dev/python/docs/intro#pyinstaller

Last but not least regarding the size, it's can't be less than 30-40mb, because the Playwright driver is that big, which can't be left out. For further issues please file a new issue.
