### ISSUE TITLE
Freeze in a loop if Timeout exceeded.

### ISSUE THREAD

**Issue by hubba-bubba-776** [microsoft/playwright-python#430]
Hi, thank you for nice port to python!

I have a problem though. In endless loop I go to website and scrape some info with proxies (that sometimes have unstable connection).

Basically my code is something like this:

```python
from playwright import sync_playwright
from playwright.helper import TimeoutError


def init(p: SyncPlaywrightContextManager, proxy: Proxy, device_name:str):
    device = p.devices[device_name]
    kwargs = {}
    args = ["--disable-dev-shm-usage", '--disable-setuid-sandbox', '--no-sandbox']
    config = dict(
        **device,
        locale='en-US',
        geolocation={'longitude': float(proxy.lon) + random.randint(1,99999)/1000000,
                               'latitude': float(proxy.lat) + random.randint(1,99999)/1000000},
        permissions=['geolocation'])

    kwargs["proxy"] = {
            "server": f"{prefix}://{proxy.ip}:{proxy.port}",
            "username": proxy.username,
            "password": proxy.password}
    args += [f"--proxy-server={kwargs['proxy']['server']}"]
    logger.info(f"Browser kwargs = {kwargs} ")
    config['httpCredentials'] = {"username": kwargs['proxy']['username'],
                                 "password": kwargs['proxy']['password']}
    
    browser = p.chromium.launch(headless=False,
                                slowMo=np.random.randint(30,100),
                                args=args,                                
                                timeout=10000)

    context = browser.newContext(**config)
    return browser, context


class Task(object):
    def return_error(self, error_text:str) -> (None):
        if self.page is not None:
            self.page.close()
            self.context.close()
            self.browser.close()

    def __call__(self) -> (bool):
        try:    
            with sync_playwright() as p:
                    self.browser, self.context = init(p=p,
                                                 proxy=proxy,
                                                 device_name=device_name)
                    self.page = self.context.newPage()

                    with self.page.expect_navigation():
                        self.page.goto("http://example.com")

                    if self.page.querySelector("//div[contains(text(), 'Blabla')]") is not None: 
                        # LOC A
                        self.return_error("Blabla")
                        return False

                    self.page.close()
                    self.context.close()
                    self.browser.close()

            return True

        except TimeoutError as e:
            # LOC B
            self.return_error(error_text="Playwright timeout error")
            return False

        except Exception as e:
            self.return_error(error_text="Playwright error")
            return False


if __name__ == "__main__":
    while True:
        t = Task()
        t()
``` 

So if `return_error` called in "LOC A" - the main loop continues after "browser gracefully close end":
```
2021-01-15T08:40:21.899Z pw:browser <launched> pid=88         
2021-01-15T08:40:22.255Z pw:browser [err] [88:98:0115/084022.254367:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory 
2021-01-15T08:40:22.328Z pw:browser [err] [88:111:0115/084022.328139:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp
" and on UNIX "unix")                                                                                                                                                                                       
2021-01-15T08:40:22.328Z pw:browser [err] [88:111:0115/084022.328872:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp
" and on UNIX "unix")                                                                                                                                                                                       
2021-01-15T08:40:22.412Z pw:browser [err] [88:123:0115/084022.412533:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
2021-01-15T08:40:22.414Z pw:browser [err] [88:123:0115/084022.414404:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
2021-01-15T08:40:22.415Z pw:browser [err] [88:123:0115/084022.415644:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
2021-01-15T08:40:22.417Z pw:browser [err] [88:123:0115/084022.417774:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
2021-01-15T08:40:22.418Z pw:browser [err] [88:123:0115/084022.418657:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
2021-01-15 08:40:22.423 | INFO     | utils.pw:init:67 - PW config = {}                                                                                                                                                                        
2021-01-15T08:40:22.479Z pw:browser [err] [88:111:0115/084022.479050:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp
" and on UNIX "unix")                                                                                                                                                                                       
2021-01-15T08:40:22.480Z pw:browser [err] [88:111:0115/084022.479899:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp
" and on UNIX "unix")                                                                                                                                                                                       
2021-01-15T08:40:22.753Z pw:browser [err] libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)                                                                                
2021-01-15T08:40:22.933Z pw:api navigating to "https://example.com", waiting until "load"                                                                                       
2021-01-15T08:40:24.045Z pw:api   navigated to "https://example.com"                                                                                                            
2021-01-15T08:40:30.478Z pw:api   "domcontentloaded" event fired                                                                                                                                            
2021-01-15T08:40:32.082Z pw:api   "networkidle" event fired                                                                                                                                                 
2021-01-15T08:40:32.241Z pw:api   navigated to "https://example.com"                                   
2021-01-15T08:40:32.775Z pw:api   navigated to "https://example.com"                                                                                                                       
2021-01-15T08:40:33.935Z pw:api   "load" event fired                                                                                                                                                        

.........


2021-01-15T08:42:25.303Z pw:browser <gracefully close start>                                                                                                                                                
2021-01-15T08:42:25.458Z pw:browser [err] [0115/084225.457706:ERROR:nacl_helper_linux.cc(307)] NaCl helper process running without a sandbox!                                                               
2021-01-15T08:42:25.458Z pw:browser [err] Most likely you need to configure your SUID sandbox correctly                                                                                                     
2021-01-15T08:42:25.463Z pw:browser <process did exit: exitCode=0, signal=null>                                                                                                                             
2021-01-15T08:42:25.537Z pw:browser <gracefully close end> 
```

But if `return_error` called in "LOC B" - the loop hangs forever:
```
2021-01-15T08:42:38.830Z pw:browser <launched> pid=248
2021-01-15T08:42:39.128Z pw:browser [err] [248:258:0115/084239.127248:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or director
y
2021-01-15T08:42:39.199Z pw:browser [err] [248:271:0115/084239.198823:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "t$
p" and on UNIX "unix")
2021-01-15T08:42:39.199Z pw:browser [err] [248:271:0115/084239.199811:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tc
p" and on UNIX "unix")
2021-01-15T08:42:39.329Z pw:browser [err] [248:283:0115/084239.329074:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or director
y
2021-01-15T08:42:39.331Z pw:browser [err] [248:283:0115/084239.331541:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or director
y
2021-01-15T08:42:39.332Z pw:browser [err] [248:283:0115/084239.332674:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or director
y
2021-01-15T08:42:39.338Z pw:browser [err] [248:283:0115/084239.338114:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or director
y
2021-01-15T08:42:39.339Z pw:browser [err] [248:283:0115/084239.339701:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or director
y
2021-01-15 08:42:39.346 | INFO     | utils.pw:init:67 - PW config = {}
2021-01-15T08:42:39.411Z pw:browser [err] [248:271:0115/084239.411186:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tc
p" and on UNIX "unix")
2021-01-15T08:42:39.413Z pw:browser [err] [248:271:0115/084239.412958:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tc
p" and on UNIX "unix")
2021-01-15T08:42:39.714Z pw:browser [err] libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
2021-01-15T08:42:39.882Z pw:api navigating to "https://example.com", waiting until "load"
2021-01-15T08:42:45.804Z pw:api   navigated to "https://example.com"
2021-01-15T08:43:05.060Z pw:api   "domcontentloaded" event fired
2021-01-15T08:43:09.884Z pw:browser <gracefully close start>
2021-01-15 08:43:09.922 | INFO     | core.base:__call__:185 Timeouterror Timeout 24076ms exceeded. Traceback (most recent call last):
  File "/app/core/base.py", line 165, in __call__
    self.page.goto(self.start_url)
  File "/usr/local/lib/python3.8/dist-packages/playwright/sync_api.py", line 4197, in goto
    self._sync(
  File "/usr/local/lib/python3.8/dist-packages/playwright/sync_base.py", line 107, in _sync
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/playwright/page.py", line 451, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "/usr/local/lib/python3.8/dist-packages/playwright/frame.py", line 116, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/usr/local/lib/python3.8/dist-packages/playwright/connection.py", line 39, in send
    result = await callback.future
playwright.helper.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "https://www.example.com", waiting until "load"
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/core/base.py", line 165, in __call__
    self.page.goto(self.start_url)
  File "/usr/local/lib/python3.8/dist-packages/playwright/sync_base.py", line 85, in __exit__
    self._event.value
  File "/usr/local/lib/python3.8/dist-packages/playwright/sync_base.py", line 73, in value
    raise self._exception
  File "/usr/local/lib/python3.8/dist-packages/playwright/sync_base.py", line 59, in done_callback
    self._value = mapping.from_maybe_impl(self._future.result())
  File "/usr/local/lib/python3.8/dist-packages/playwright/page.py", line 473, in waitForNavigation
    return await self._main_frame.waitForNavigation(**locals_to_params(locals()))
  File "/usr/local/lib/python3.8/dist-packages/playwright/frame.py", line 171, in waitForNavigation
    await self.waitForLoadState(state=waitUntil, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/playwright/frame.py", line 188, in waitForLoadState
    await wait_helper.wait_for_event(
  File "/usr/local/lib/python3.8/dist-packages/playwright/wait_helper.py", line 60, in wait_for_event
    return await self.wait_for_future(future)
  File "/usr/local/lib/python3.8/dist-packages/playwright/wait_helper.py", line 73, in wait_for_future 
    raise failure.result()
playwright.helper.TimeoutError: Timeout 24076ms exceeded.

2021-01-15 08:43:09.925 | ERROR    | common.utils:send_error:13 - Playwright timeout error
2021-01-15T08:43:10.070Z pw:browser [err] [0115/084310.066045:ERROR:nacl_helper_linux.cc(307)] NaCl helper process running without a sandbox!
2021-01-15T08:43:10.071Z pw:browser [err] Most likely you need to configure your SUID sandbox correctly
2021-01-15T08:43:10.072Z pw:browser <process did exit: exitCode=0, signal=null>
2021-01-15T08:43:10.184Z pw:browser <gracefully close end>
```

However the browser logs seems the same.

My env is Docker with playwright==0.162.2
```Dockerfile
FROM python:3.7
ENV PYTHONUNBUFFERED 1
ENV C_FORCE_ROOT true

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install gettext libgettextpo-dev vim postgresql-client -y

COPY requirements.txt /.
RUN pip3 install -U pip setuptools
RUN pip3 install -r /requirements.txt
```

docker-compose:
```
    build: './my_folder'
    container_name: my_container
    restart: always
    volumes:
      - my_folder ....
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
    mem_limit: 2.5gb
    memswap_limit: 2.5gb
    shm_size: '2.5gb'
    working_dir: /app
    env_file:
      - .env
    environment:
      - "DEBUG=pw:api,pw:browser*"
      - "DISPLAY=:0"
```

**I guess I'm doing something wrong, that causes the loop freeze?**

As a side question: **why there is error in `Most likely you need to configure your SUID sandbox correctly`, though I have `--disable-setuid-sandbox', '--no-sandbox'` args. I guess it's not crucial?**

**Comment by hubba-bubba-776** [comment]
Seem like if put try.. except inside ` with sync_playwright() as p:` is is working fine:

```python 
      with sync_playwright() as p:
             try:
                    self.browser, self.context = init(p=p,
                                                 proxy=proxy,
                                                 device_name=device_name)
                    self.page = self.context.newPage()

                    with self.page.expect_navigation():
                        self.page.goto("http://example.com")

                    if self.page.querySelector("//div[contains(text(), 'Blabla')]") is not None: 
                        # LOC A
                        self.return_error("Blabla")
                        return False

                    self.page.close()
                    self.context.close()
                    self.browser.close()
          except TimeoutError as e:
              # LOC B
              self.return_error(error_text="Playwright timeout error")
              return False

          except Exception as e:
              self.return_error(error_text="Playwright error")
              return False
              return True


```
