### ISSUE TITLE
Proxy-Authorization header not working in Chromium

### ISSUE THREAD

**Issue by elacuesta** [microsoft/playwright-python#443]
Hello there, thanks for this great project.

I'm having trouble making requests though a proxy. Consider the following snippet:

```python
import asyncio
from playwright import async_playwright

async def main():
    async with async_playwright() as p:
        browser = await p.chromium.launch(
            proxy={
                "server": "PROXY_URL",
                "username": "PROXY_APIKEY",
                "password": "",
            },
        )
        context = await browser.newContext(ignoreHTTPSErrors=True)
        page = await context.newPage()
        await page.goto("https://httpbin.org/ip")
        print(await page.content())
        await page.screenshot(path="ip_address.png")
        await browser.close()

if __name__ == "__main__":
    asyncio.run(main())
```

If I run it, I get:
```
$ DEBUG=pw:api python proxy.py 
  pw:api navigating to "https://httpbin.org/ip", waiting until "load" +0ms
  pw:api   navigated to "https://httpbin.org/ip" +1s
  pw:api   "load" event fired +7ms
  pw:api   "domcontentloaded" event fired +8ms
<html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">Internal Server Error</pre></body></html>
```

I can confirm the proxy URL and credentials are correct with cURL (the resulting IP address is not my own, as expected):
```
$ curl --insecure --proxy $PROXY_URL --proxy-user $PROXY_APIKEY: https://httpbin.org/ip
{
  "origin": "xxx.xxx.xxx.xxx"
}
```

Could this be caused by the fact that the proxy server expects an empty password and Playwright sends some default value? For the record, I'm using Python 3.8.2 and Playwright 0.171.1 on GNU/Linux.

Looking forward to your answers, thanks again for the hard work.

**Comment by pavelfeldman** [comment]
I ported a bunch of tests that use auth and also tested the empty password, it all worked. See https://github.com/microsoft/playwright-python/compare/master...pavelfeldman:proxy12?expand=1 

I wonder if there is anything specific to your use case. Also you could try setting dummy proxy on the browser level and setting real proxy on the context level.

(Note that we are in the process of migration to snake case, so the tests will look different from your code)

**Comment by elacuesta** [comment]
Hi, thanks for looking into this.

The proxy provider has instructed me to [manually set the `Proxy-Authorization` header](https://support.scrapinghub.com/support/solutions/articles/22000220800-using-crawlera-with-puppeteer) (the article is about Puppeteer, I suppose the concepts should still apply).
Unfortunately, I'm still having issues, even with a local proxy (`mitmproxy --proxyauth "user:pass"`):

```python
import asyncio
from base64 import b64encode
from playwright import async_playwright

async def main():
    async with async_playwright() as p:
        browser = await p.chromium.launch(
            proxy={"server": "localhost:8080"},
            # args=[
            #     "--proxy-server=localhost:8080",
            # ],
        )
        context = await browser.newContext(ignoreHTTPSErrors=True)
        page = await context.newPage()
        await page.setExtraHTTPHeaders({
            "Proxy-Authorization": "Basic " + b64encode(b"user:pass").decode("utf8"),
        })
        await page.goto("https://httpbin.org/ip")
        print(await page.content())
        await browser.close()

if __name__ == "__main__":
    asyncio.run(main())
```
```
$ DEBUG=pw:api python proxy.py 
  pw:api navigating to "https://httpbin.org/ip", waiting until "load" +0ms
Traceback (most recent call last):
  File "proxy.py", line 23, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "proxy.py", line 18, in main
    await page.goto("https://httpbin.org/ip")
  File "/.../lib/python3.8/site-packages/playwright/async_api.py", line 4269, in goto
    await self._impl_obj.goto(
  File "/.../lib/python3.8/site-packages/playwright/_page.py", line 452, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "/.../lib/python3.8/site-packages/playwright/_frame.py", line 114, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/.../lib/python3.8/site-packages/playwright/_connection.py", line 36, in send
    return await self.inner_send(method, params, False)
  File "/.../lib/python3.8/site-packages/playwright/_connection.py", line 47, in inner_send
    result = await callback.future
playwright._types.Error: net::ERR_INVALID_ARGUMENT at https://httpbin.org/ip
=========================== logs ===========================
navigating to "https://httpbin.org/ip", waiting until "load"
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
```

What seems strange to me is that I'm also having the same issue with plain Playwright:

```js
const { chromium } = require('playwright');

(async () => {
    const browser = await chromium.launch({
        proxy: {
            server: 'localhost:8080',
            // username: 'user',
            // password: 'pass',
        }
    });
    const context = await browser.newContext({ignoreHTTPSErrors: true})
    const page = await context.newPage();
    await page.setExtraHTTPHeaders({
        'Proxy-Authorization': 'Basic ' + Buffer.from('user:pass').toString('base64'),
    });
    try {
        await page.goto('https://httpbin.org/ip');
        console.log(await page.content());
    } catch(err) {
        console.log(err);
    }
    await browser.close();
})();
```
```
$ node proxy.js 
page.goto: net::ERR_INVALID_ARGUMENT at https://httpbin.org/ip
=========================== logs ===========================
navigating to "https://httpbin.org/ip", waiting until "load"
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
    at Connection.sendMessageToServer (/.../node_modules/playwright/lib/client/connection.js:69:15)
    at Proxy.<anonymous> (/.../node_modules/playwright/lib/client/channelOwner.js:44:61)
    at /.../node_modules/playwright/lib/client/frame.js:80:71
    at Frame._wrapApiCall (/.../node_modules/playwright/lib/client/channelOwner.js:72:34)
    at Frame.goto (/.../node_modules/playwright/lib/client/frame.js:78:21)
    at /.../node_modules/playwright/lib/client/page.js:267:60
    at Page._attributeToPage (/.../node_modules/playwright/lib/client/page.js:202:20)
    at Page.goto (/.../node_modules/playwright/lib/client/page.js:267:21)
    at /.../proxy.js:17:20
```

Is there a chance this might be an upstream issue that should be solved in https://github.com/microsoft/playwright instead?

**Comment by pavelfeldman** [comment]
> the article is about Puppeteer, I suppose the concepts should still apply

Not really, Playwright has dedicated support for proxies and Puppeteer was using combination of command line flags and headers override. All you need is the `proxy` parameter.

Following worked for me with plain `mitmweb`. Note that I'm using `pip install playwright==1.8.0a1` with the snake apis.
```py
import asyncio
from playwright.async_api import async_playwright

async def main():
    async with async_playwright() as p:
        browser = await p.chromium.launch(
            proxy={"server": "localhost:8080"},
        )
        context = await browser.new_context(ignore_https_errors=True)
        page = await context.new_page()
        await page.goto("https:/example.com")
        print(await page.content())
        await browser.close()

if __name__ == "__main__":
    asyncio.run(main())
```

**Comment by elacuesta** [comment]
Indeed, `mitmproxy/mitmweb` works for me as well without auth, the problem is using `--proxyauth "user:pass"` and calling `set_extra_http_headers` to pass `Proxy-Authorization`.

Intercepting the request to add the header doesn't work either:
```python
import asyncio
from base64 import b64encode
from playwright.async_api import async_playwright

def add_proxy_auth_header(route, request):
    headers = request.headers
    headers["Proxy-Authorization"] = "Basic " + b64encode(b"user:pass").decode("utf8")
    asyncio.create_task(route.continue_(headers=headers))

async def main():
    async with async_playwright() as p:
        browser = await p.chromium.launch(proxy={"server": "localhost:8080"})
        context = await browser.new_context(ignore_https_errors=True)
        page = await context.new_page()
        await page.route("**", add_proxy_auth_header)
        await page.goto("https://httpbin.org/ip")
        print(await page.content())
        await browser.close()
```

**Comment by elacuesta** [comment]
For the record, using `setExtraHTTPHeaders/set_extra_http_headers` to add `Proxy-Authorization` works with Firefox.

**Comment by pavelfeldman** [comment]
Following worked for me for all browsers if I havigate to HTTP and failed only on WebKit if I navigate to HTTPS.

```sh
./mitmweb --proxyauth user:
```

```py
browser = await p.chromium.launch(
    proxy={"server": "localhost:8080", "username": "user", "password": ""},
)
```

I was testing this on Linux, is this consistent with your experience?

**Comment by elacuesta** [comment]
Hey, I appreciate you're taking the time to look into this.

That works for me with `mitmproxy`, but it does not work with [`Crawlera`](https://www.scrapinghub.com/crawlera/), so I suspect there might be a difference in the way authentication is handled (in both ends). In any case, am I correct to believe setting `Proxy-Authorization` via `set_extra_http_headers` should also work, regardless of the browser? Consider the following, which works with Firefox but fails with Chromium:

```
$ ./mitmproxy --proxyauth user:
```
```python
async def main():
    async with async_playwright() as p:
        for browser_type in [p.firefox, p.chromium]:
            print("*" * 100)
            browser = await browser_type.launch(
                proxy={"server": "localhost:8080"},
            )
            context = await browser.new_context(ignore_https_errors=True)
            page = await context.new_page()
            await page.set_extra_http_headers({
                "Proxy-Authorization": "Basic " + b64encode(b"user:").decode("utf8"),
            })
            await page.goto("https://httpbin.org/ip")
            print(await page.content())
            await browser.close()
```
```
****************************************************************************************************
<html><head><link rel="stylesheet" href="resource://content-accessible/plaintext.css"></head><body><pre>{
  "origin": "xxx.xxx.xxx.xxx"
}
</pre></body></html>
****************************************************************************************************
Traceback (most recent call last):
  File "proxy.py", line 22, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "proxy.py", line 17, in main
    await page.goto("https://httpbin.org/ip")
  File "/.../lib/python3.8/site-packages/playwright/async_api/_generated.py", line 6553, in goto
    raise e
  File "/.../lib/python3.8/site-packages/playwright/async_api/_generated.py", line 6545, in goto
    await self._impl_obj.goto(
  File "/.../lib/python3.8/site-packages/playwright/_impl/_page.py", line 470, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "/.../lib/python3.8/site-packages/playwright/_impl/_frame.py", line 115, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/.../lib/python3.8/site-packages/playwright/_impl/_connection.py", line 36, in send
    return await self.inner_send(method, params, False)
  File "/.../lib/python3.8/site-packages/playwright/_impl/_connection.py", line 47, in inner_send
    result = await callback.future
playwright._impl._api_types.Error: net::ERR_INVALID_ARGUMENT at https://httpbin.org/ip
=========================== logs ===========================
navigating to "https://httpbin.org/ip", waiting until "load"
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
```

It's worth noting that I'm seeing the same behaviour with the JS version, i.e. the following works, but fails if I replace `playwright.firefox` with `playwright.chromium`. I'm thinking it might be better to close this issue and open one in https://github.com/microsoft/playwright.
```js
const playwright = require('playwright');

(async () => {
    const browser = await playwright.firefox.launch({
        proxy: {
            server: 'localhost:8080',
        }
    });
    const context = await browser.newContext({ignoreHTTPSErrors: true})
    const page = await context.newPage();
    await page.setExtraHTTPHeaders({
        'Proxy-Authorization': 'Basic ' + Buffer.from('user:').toString('base64'),
    });
    try {
        await page.goto('https://httpbin.org/ip');
        console.log(await page.content());
    } catch(err) {
        console.log(err);
    }
    await browser.close();
})();
```

**Comment by pavelfeldman** [comment]
> In any case, am I correct to believe setting Proxy-Authorization via set_extra_http_headers should also work, regardless of the browser?

No, networks stacks work differently across the browsers, so as you can see this approach does not work in Chromium.

**Comment by elacuesta** [comment]
Hi again, sorry for taking so long. I guess this is browser-dependent and out of the scope of Playwright, then?

**Comment by pavelfeldman** [comment]
> I guess this is browser-dependent and out of the scope of Playwright, then?

We support both headers injection and dedicated proxy auth, I'm not sure what we are missing actually.
