### ISSUE TITLE
browser_context.add_cookies(cookies) issues

### ISSUE THREAD

**Issue by selfisekai** [microsoft/playwright-python#459]
https://playwright.dev/python/docs/api/class-browsercontext#browser_contextadd_cookiescookies

this happens if `cookie['expires']` is set, but it's value is `None` (works if `'expires' not in cookie`):
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/laura/haruhi-dl/haruhi_dl/__main__.py", line 19, in <module>
    haruhi_dl.main()
  File "/home/laura/haruhi-dl/haruhi_dl/__init__.py", line 474, in main
    _real_main(argv)
  File "/home/laura/haruhi-dl/haruhi_dl/__init__.py", line 464, in _real_main
    retcode = hdl.download(all_urls)
  File "/home/laura/haruhi-dl/haruhi_dl/HaruhiDL.py", line 2019, in download
    res = self.extract_info(
  File "/home/laura/haruhi-dl/haruhi_dl/HaruhiDL.py", line 798, in extract_info
    ie_result = ie.extract(url)
  File "/home/laura/haruhi-dl/haruhi_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/laura/haruhi-dl/haruhi_dl/extractor/pornhub.py", line 193, in _real_extract
    webpage = dl_webpage('pc')
  File "/home/laura/haruhi-dl/haruhi_dl/extractor/pornhub.py", line 189, in dl_webpage
    return self._download_webpage(
  File "/home/laura/haruhi-dl/haruhi_dl/extractor/common.py", line 798, in _download_webpage
    res = self._download_webpage_handle(
  File "/home/laura/haruhi-dl/haruhi_dl/extractor/pornhub.py", line 48, in _download_webpage_handle
    pwh.open_page(url, display_id, html=webpage)
  File "/home/laura/haruhi-dl/haruhi_dl/playwright.py", line 103, in open_page
    browser_context.add_cookies(self._get_cookies_for_browser())
  File "/home/laura/.local/lib/python3.9/site-packages/playwright/sync_api/_generated.py", line 8934, in add_cookies
    raise e
  File "/home/laura/.local/lib/python3.9/site-packages/playwright/sync_api/_generated.py", line 8928, in add_cookies
    self._sync(self._impl_obj.add_cookies(cookies=cookies))
  File "/home/laura/.local/lib/python3.9/site-packages/playwright/_impl/_sync_base.py", line 90, in _sync
    return future.result()
  File "/home/laura/.local/lib/python3.9/site-packages/playwright/_impl/_browser_context.py", line 129, in add_cookies
    await self._channel.send("addCookies", dict(cookies=cookies))
  File "/home/laura/.local/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 36, in send
    return await self.inner_send(method, params, False)
  File "/home/laura/.local/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 47, in inner_send
    result = await callback.future
playwright._impl._api_types.Error: cookies[6].expires: expected number, got object
```

this happens when the cookie value is an empty string (`''`; affects cookies created by some real production web apps, including teams.microsoft.com, paypal.com, web.archive.org, edition.cnn.com and wikia.com):
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/laura/haruhi-dl/haruhi_dl/__main__.py", line 19, in <module>
    haruhi_dl.main()
  File "/home/laura/haruhi-dl/haruhi_dl/__init__.py", line 475, in main
    _real_main(argv)
  File "/home/laura/haruhi-dl/haruhi_dl/__init__.py", line 465, in _real_main
    retcode = hdl.download(all_urls)
  File "/home/laura/haruhi-dl/haruhi_dl/HaruhiDL.py", line 2018, in download
    res = self.extract_info(
  File "/home/laura/haruhi-dl/haruhi_dl/HaruhiDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/home/laura/haruhi-dl/haruhi_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/laura/haruhi-dl/haruhi_dl/extractor/tvn24.py", line 69, in _real_extract
    return self._handle_nextjs_frontend(url, display_id)
  File "/home/laura/haruhi-dl/haruhi_dl/extractor/tvn24.py", line 159, in _handle_nextjs_frontend
    page = pwh.open_page(url, display_id)
  File "/home/laura/haruhi-dl/haruhi_dl/playwright.py", line 108, in open_page
    browser_context.add_cookies(self._get_cookies_for_browser())
  File "/home/laura/.local/lib/python3.9/site-packages/playwright/sync_api/_generated.py", line 8934, in add_cookies
    raise e
  File "/home/laura/.local/lib/python3.9/site-packages/playwright/sync_api/_generated.py", line 8928, in add_cookies
    self._sync(self._impl_obj.add_cookies(cookies=cookies))
  File "/home/laura/.local/lib/python3.9/site-packages/playwright/_impl/_sync_base.py", line 90, in _sync
    return future.result()
  File "/home/laura/.local/lib/python3.9/site-packages/playwright/_impl/_browser_context.py", line 129, in add_cookies
    await self._channel.send("addCookies", dict(cookies=cookies))
  File "/home/laura/.local/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 36, in send
    return await self.inner_send(method, params, False)
  File "/home/laura/.local/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 47, in inner_send
    result = await callback.future
playwright._impl._api_types.Error: Cookie should have a value
```

**Comment by pavelfeldman** [comment]
Does this happen on WebKit only or any other browser as well?

**Comment by selfisekai** [comment]
@pavelfeldman both logs were for firefox, didn't check others

**Comment by vffuunnyy** [comment]
@pavelfeldman still has the same issue

```
Traceback (most recent call last):
  File "get_cookies.py", line 126, in parse_profile
  File "playwright\async_api\_generated.py", line 12295, in cookies
  File "playwright\_impl\_browser_context.py", line 300, in cookies
  File "playwright\_impl\_connection.py", line 59, in send
  File "playwright\_impl\_connection.py", line 509, in wrap_api_call
  File "playwright\_impl\_connection.py", line 97, in inner_send
playwright._impl._errors.Error: cookies[76].expires: expected number, got object
```

in `cookies = await context.cookies()`

playwright version `1.42.0`
python `3.12.0`

**Comment by mxschmitt** [comment]
@vffuunnyy please file a new issue with a reproduction, thanks!
