### ISSUE TITLE
[BUG] Protocol error (Network.setCacheDisabled): Target closed.Error

### ISSUE THREAD

**Issue by caramdache** [microsoft/playwright-python#461]
Just ran into this issue where playwright crashed on closing the browser:

```bash
(node:11318) UnhandledPromiseRejectionWarning: Protocol error (Network.setCacheDisabled): Target closed.Error
    at /var/www/django/python3.9/lib/python3.9/site-packages/playwright/driver/package/lib/server/chromium/crConnection.js:135:63
    at new Promise (<anonymous>)
    at CRSession.send (/var/www/django/python3.9/lib/python3.9/site-packages/playwright/driver/package/lib/server/chromium/crConnection.js:134:16)
    at CRNetworkManager._updateProtocolRequestInterception (/var/www/django/python3.9/lib/python3.9/site-packages/playwright/driver/package/lib/server/chromium/crNetworkManager.js:86:30)
    at CRNetworkManager.setRequestInterception (/var/www/django/python3.9/lib/python3.9/site-packages/playwright/driver/package/lib/server/chromium/crNetworkManager.js:77:20)
    at FrameSession._updateRequestInterception (/var/www/django/python3.9/lib/python3.9/site-packages/playwright/driver/package/lib/server/chromium/crPage.js:755:36)
    at /var/www/django/python3.9/lib/python3.9/site-packages/playwright/driver/package/lib/server/chromium/crPage.js:129:56
    at /var/www/django/python3.9/lib/python3.9/site-packages/playwright/driver/package/lib/server/chromium/crPage.js:71:76
    at Array.map (<anonymous>)
    at CRPage._forAllFrameSessions (/var/www/django/python3.9/lib/python3.9/site-packages/playwright/driver/package/lib/server/chromium/crPage.js:71:63)
```
This was triggered by the following code:
```python
def stop(self):
    print('Closing...')
    cookies = self.context.cookies()
    with open(self.COOKIES_PATH, 'w') as file:
        file.write(json.dumps(cookies))
    self.context.close()

```
This happened once, could not reproduce, probably a race condition.

**Comment by pavelfeldman** [comment]
Could you share more of your script? Could it be that you are setting a route in some event handler concurrently with closing the context?

**Comment by caramdache** [comment]
Sure. Here's some more code:

```python
from playwright.sync_api import sync_playwright

class W
    def start(self, playwright):
        self.context = playwright.chromium.launch_persistent_context(
            headless=True,
            accept_downloads=True,
            user_data_dir=f'./user_data',
        )

        if os.path.isfile(self.COOKIES_PATH):
            with open(self.COOKIES_PATH) as file:
                cookies = json.loads(file.read())
            self.context.add_cookies(cookies)

        self.page = self.context.pages[0]

        def handle(route, request):
            if request.resource_type in ['document', 'script', 'xhr']:
                route.continue_()
            else:
                route.abort()

        self.context.route('**/*', handle)

    def goto(self, url, selector):
        self.page.goto(url)
        self.page.wait_for_selector(selector)

    def stop(self):
        cookies = self.context.cookies()
        with open(self.COOKIES_PATH, 'w') as file:
            file.write(json.dumps(cookies))

        self.context.close()

def main(argv):
    with sync_playwright() as playwright:
        w= W()
        w.start()
        w.goto(<some url>)
        walker.stop()

```

**Comment by dgozman** [comment]
I think that https://github.com/microsoft/playwright/pull/5246 fixes this issue. Let me tentatively close it. Please reopen if v1.9 won't fix it.
