### ISSUE TITLE
[BUG ] Unable to take screenshot because "page is still navigating"

### ISSUE THREAD

**Issue by caramdache** [microsoft/playwright-python#463]
I have an issue where `page.goto()` returns when before the page has is fully loaded.

However, if I take a screenshot right after `page.goto()` returns, chromium says that page is still navigating.

Am I missing something obvious?

```python
  pw:api => browser_type.launch_persistent_context started
  pw:api <= browser_type.launch_persistent_context succeded
  pw:api => browser_context.add_cookies started
  pw:api <= browser_context.add_cookies succeded
  pw:api => browser_context.route started
  pw:api <= browser_context.route succeded
>>> OPENING <someurl> <<<
  pw:api => page.goto started
  pw:api navigating to "<someurl>", waiting until "load" +0ms
  pw:api => route.continue_ started
  pw:api <= route.continue_ succeded
  pw:api   navigated to "<someurl>" +65ms
  pw:api   "domcontentloaded" event fired +4ms
  pw:api   "load" event fired +0ms
  pw:api <= page.goto succeded
>>> PAGE.URL: <someurl> <<<
  pw:api => page.screenshot started
  pw:api <= page.screenshot failed
Traceback (most recent call last):
  File "/var/www/django/playwright/x.py", line 25, in goto
    self.page.screenshot(path="screenshot.png", full_page=True)
  File "/var/www/django/python3.9/lib/python3.9/site-packages/playwright/sync_api/_generated.py", line 7250, in screenshot
    raise e
  File "/var/www/django/python3.9/lib/python3.9/site-packages/playwright/sync_api/_generated.py", line 7234, in screenshot
    self._sync(
  File "/var/www/django/python3.9/lib/python3.9/site-packages/playwright/_impl/_sync_base.py", line 90, in _sync
    return future.result()
  File "/var/www/django/python3.9/lib/python3.9/site-packages/playwright/_impl/_page.py", line 573, in screenshot
    encoded_binary = await self._channel.send("screenshot", params)
  File "/var/www/django/python3.9/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 36, in send
    return await self.inner_send(method, params, False)
  File "/var/www/django/python3.9/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 47, in inner_send
    result = await callback.future
playwright._impl._api_types.Error: Cannot take a screenshot while page is navigating
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.

```

**Comment by caramdache** [comment]
The trace above was on CentOS7. The exact same code runs without any issue on Win10.

```python
  pw:api => browser_type.launch_persistent_context started
  pw:api <= browser_type.launch_persistent_context succeded
  pw:api => browser_context.add_cookies started
  pw:api <= browser_context.add_cookies succeded
  pw:api => browser_context.route started
  pw:api <= browser_context.route succeded
>>> OPENING <someurl> <<<
  pw:api => page.goto started
  pw:api navigating to <someurl>, waiting until "load" +0ms
  pw:api => route.continue_ started
  pw:api <= route.continue_ succeded
  pw:api   navigated to <timeouturl +2s
  pw:api => route.abort started
  pw:api => route.abort started
  pw:api => route.continue_ started
  pw:api => route.continue_ started
  pw:api => route.continue_ started
  pw:api => route.continue_ started
  pw:api => route.continue_ started
  pw:api => route.continue_ started
  pw:api => route.continue_ started
  pw:api => route.continue_ started
  pw:api => route.continue_ started
  pw:api => route.abort started
  pw:api <= route.abort succeded
  pw:api <= route.abort succeded
  pw:api <= route.continue_ succeded
  pw:api <= route.continue_ succeded
  pw:api <= route.continue_ succeded
  pw:api <= route.continue_ succeded
  pw:api <= route.continue_ succeded
  pw:api <= route.continue_ succeded
  pw:api <= route.continue_ succeded
  pw:api <= route.continue_ succeded
  pw:api <= route.continue_ succeded
  pw:api <= route.abort succeded
  pw:api => route.continue_ started
  pw:api => route.continue_ started
  pw:api => route.continue_ started
  pw:api => route.continue_ started
  pw:api <= route.continue_ succeded
  pw:api <= route.continue_ succeded
  pw:api <= route.continue_ succeded
  pw:api <= route.continue_ succeded
  pw:api => route.abort started
  pw:api <= route.abort succeded
  pw:api => route.abort started
  pw:api => route.abort started
  pw:api => route.abort started
  pw:api => route.abort started
  pw:api <= route.abort succeded
  pw:api <= route.abort succeded
  pw:api <= route.abort succeded
  pw:api <= route.abort succeded
  pw:api   "load" event fired +3s
  pw:api <= page.goto succeded
  pw:api   "domcontentloaded" event fired +1ms
  pw:api => page.screenshot started
  pw:api <= page.screenshot succeded
```

**Comment by dgozman** [comment]
@caramdache Perhaps the page is still navigating? Maybe it does a client-side redirect after a timeout?  Unfortunately, we cannot proceed without reproducing this first. Could you share a page url at least?

**Comment by caramdache** [comment]
@dgozman It's an internal server that you don't have access to unfortunately. Are there any debug means at my disposal, finer grain than `DEBUG=pw:api`?

Interestingly, the issue on CentOS seems to go away as soon as I run `pip -m playwright install` (which runs instantly and does seem to do anything). But why?

**Comment by dgozman** [comment]
> @dgozman It's an internal server that you don't have access to unfortunately. Are there any debug means at my disposal, finer grain than `DEBUG=pw:api`?

Try running with `DEBUG=pw:protocol` and attaching the logs. Note that logs will have all the urls and cookies, so make sure you are comfortable sharing that.

> Interestingly, the issue on CentOS seems to go away as soon as I run `pip -m playwright install` (which runs instantly and does seem to do anything). But why?

That's weird, and I have no idea why that helps.

**Comment by kumaraditya303** [comment]
@caramdache Curious to know if you could provide the browser dependencies you installed on the Centos Machine?

**Comment by pavelfeldman** [comment]
We need more details in order to address this issue. Could you please file a new one with the additional info (protocol log) requested above?
