### ISSUE TITLE
[BUG] chromium hang when download file from jupyter notebook tree page

### ISSUE THREAD

**Issue by zhuoqiang** [microsoft/playwright-python#465]
- Python: `3.8`
- Playwright: `1.8.0a1`
- OS: MacOS Catalina

the following scripts shows that chromium hang when download file from jupyter notebook tree page:

suppose there is a jupyter notebook server running with `some-file.zip` in the its working directory

```python
import playwright.sync_api

with playwright.sync_api.sync_playwright() as playwright:
    browser = playwright.chromium.launch()
    context = browser.new_context(accept_downloads=True)
    page = context.new_page()

    page.goto("http://localhost:8888/tree")
    name = "some-file.zip"
    page.check("//div[contains(@class, 'list_item') and contains(.//span, '{}')]//input[@type='checkbox']".format(name))
    page.wait_for_load_state("networkidle")
    with page.expect_download() as download_info:
        page.click("button.download-button")
        download = download_info.value

    print("download suggested filename: {}".format(download.suggested_filename))
    print("download path:{}".format(download.path()))
    download.save_as(download.suggested_filename)
```

the hang happens when calling `download.path()`, I have to manually stop it with CTRL-C

here's the output:

```
2021-01-28T11:59:29.064Z pw:api navigating to "http://localhost:8888/tree", waiting until "load"
2021-01-28T11:59:29.090Z pw:api   navigated to "http://localhost:8888/tree"
2021-01-28T11:59:29.179Z pw:api   "load" event fired
2021-01-28T11:59:29.180Z pw:api waiting for selector "//div[contains(@class, 'list_item') and contains(.//span, 'some-file.zip')]//input[@type='checkbox']"
2021-01-28T11:59:29.182Z pw:api   "domcontentloaded" event fired
2021-01-28T11:59:29.317Z pw:api   selector resolved to visible <input type="checkbox" title="点击这里进行重命名或删除等操作"/>
2021-01-28T11:59:29.324Z pw:api attempting click action
2021-01-28T11:59:29.325Z pw:api   waiting for element to be visible, enabled and not moving
2021-01-28T11:59:29.345Z pw:api   element is visible, enabled and does not move
2021-01-28T11:59:29.345Z pw:api   scrolling into view if needed
2021-01-28T11:59:29.346Z pw:api   done scrolling
2021-01-28T11:59:29.348Z pw:api   checking that element receives pointer events at (98.48,702.14)
2021-01-28T11:59:29.350Z pw:api   element does receive pointer events
2021-01-28T11:59:29.351Z pw:api   performing click action
2021-01-28T11:59:29.365Z pw:api   click action done
2021-01-28T11:59:29.366Z pw:api   waiting for scheduled navigations to finish
2021-01-28T11:59:29.383Z pw:api   navigations have finished
2021-01-28T11:59:29.814Z pw:api   "networkidle" event fired
2021-01-28T11:59:29.818Z pw:api waiting for selector "button.download-button"
2021-01-28T11:59:29.823Z pw:api   selector resolved to visible <button title="下载" aria-label="下载" aria-describedby="too…>下载</button>
2021-01-28T11:59:29.826Z pw:api attempting click action
2021-01-28T11:59:29.826Z pw:api   waiting for element to be visible, enabled and not moving
2021-01-28T11:59:29.845Z pw:api   element is visible, enabled and does not move
2021-01-28T11:59:29.845Z pw:api   scrolling into view if needed
2021-01-28T11:59:29.845Z pw:api   done scrolling
2021-01-28T11:59:29.846Z pw:api   checking that element receives pointer events at (218.87,112)
2021-01-28T11:59:29.849Z pw:api   element does receive pointer events
2021-01-28T11:59:29.849Z pw:api   performing click action
2021-01-28T11:59:29.964Z pw:api   click action done
2021-01-28T11:59:29.964Z pw:api   waiting for scheduled navigations to finish
2021-01-28T11:59:29.966Z pw:api   navigations have finished
2021-01-28T11:59:29.970Z pw:api   "domcontentloaded" event fired
2021-01-28T11:59:29.970Z pw:api   "load" event fired
  pw:api => browser_type.launch started
  pw:api <= browser_type.launch succeded
  pw:api => browser.new_context started
  pw:api <= browser.new_context succeded
  pw:api => browser_context.new_page started
  pw:api <= browser_context.new_page succeded
  pw:api => page.goto started
  pw:api <= page.goto succeded
  pw:api => page.check started
  pw:api <= page.check succeded
  pw:api => page.wait_for_load_state started
  pw:api <= page.wait_for_load_state succeded
  pw:api => page.click started
  pw:api <= page.click succeded
  pw:api => download.path started
download suggested filename: some-file.zip
Traceback (most recent call last):
  File "bug.py", line 16, in <module>
    print("download path:{}".format(download.path()))
  File "python3.8/site-packages/playwright/sync_api/_generated.py", line 5356, in path
    result = mapping.from_maybe_impl(self._sync(self._impl_obj.path()))
  File "python3.8/site-packages/playwright/_impl/_sync_base.py", line 88, in _sync
    self._dispatcher_fiber.switch()
  File "python3.8/site-packages/playwright/sync_api/_context_manager.py", line 48, in greenlet_main
    loop.run_until_complete(self._connection.run_as_sync())
  File "python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "python3.8/asyncio/base_events.py", line 1823, in _run_once
    event_list = self._selector.select(timeout)
  File "python3.8/selectors.py", line 558, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt
```

using firefox is OK with the following expected output:

```
2021-01-28T12:00:10.834Z pw:api   navigated to "about:blank"
2021-01-28T12:00:10.949Z pw:api   navigated to "about:blank"
2021-01-28T12:00:10.953Z pw:api navigating to "http://localhost:8888/tree", waiting until "load"
2021-01-28T12:00:11.104Z pw:api   navigated to "http://localhost:8888/tree"
2021-01-28T12:00:11.215Z pw:api   "domcontentloaded" event fired
2021-01-28T12:00:11.215Z pw:api   "load" event fired
2021-01-28T12:00:11.216Z pw:api waiting for selector "//div[contains(@class, 'list_item') and contains(.//span, 'some-file.zip')]//input[@type='checkbox']"
2021-01-28T12:00:11.378Z pw:api   selector resolved to visible <input type="checkbox" title="Click here to rename, del…/>
2021-01-28T12:00:11.386Z pw:api attempting click action
2021-01-28T12:00:11.386Z pw:api   waiting for element to be visible, enabled and not moving
2021-01-28T12:00:11.429Z pw:api   element is visible, enabled and does not move
2021-01-28T12:00:11.429Z pw:api   scrolling into view if needed
2021-01-28T12:00:11.430Z pw:api   done scrolling
2021-01-28T12:00:11.431Z pw:api   checking that element receives pointer events at (98.48,683.36)
2021-01-28T12:00:11.433Z pw:api   element does receive pointer events
2021-01-28T12:00:11.434Z pw:api   performing click action
2021-01-28T12:00:11.442Z pw:api   click action done
2021-01-28T12:00:11.442Z pw:api   waiting for scheduled navigations to finish
2021-01-28T12:00:11.443Z pw:api   navigations have finished
2021-01-28T12:00:11.835Z pw:api   "networkidle" event fired
2021-01-28T12:00:11.846Z pw:api waiting for selector "button.download-button"
2021-01-28T12:00:11.853Z pw:api   selector resolved to visible <button title="下载" aria-label="下载" aria-describedby="too…>下载</button>
2021-01-28T12:00:11.856Z pw:api attempting click action
2021-01-28T12:00:11.856Z pw:api   waiting for element to be visible, enabled and not moving
2021-01-28T12:00:11.885Z pw:api   element is visible, enabled and does not move
2021-01-28T12:00:11.885Z pw:api   scrolling into view if needed
2021-01-28T12:00:11.886Z pw:api   done scrolling
2021-01-28T12:00:11.887Z pw:api   checking that element receives pointer events at (218.85,112.56)
2021-01-28T12:00:11.889Z pw:api   element does receive pointer events
2021-01-28T12:00:11.889Z pw:api   performing click action
2021-01-28T12:00:11.921Z pw:api   click action done
2021-01-28T12:00:11.921Z pw:api   waiting for scheduled navigations to finish
2021-01-28T12:00:11.921Z pw:api   navigations have finished
2021-01-28T12:00:11.922Z pw:api   navigated to "about:blank"
2021-01-28T12:00:11.939Z pw:api   navigated to "http://localhost:8888/files/some-file.zip?download=1"
2021-01-28T12:00:11.939Z pw:api   "load" event fired
  pw:api => browser_type.launch started
  pw:api <= browser_type.launch succeded
  pw:api => browser.new_context started
  pw:api <= browser.new_context succeded
  pw:api => browser_context.new_page started
  pw:api <= browser_context.new_page succeded
  pw:api => page.goto started
  pw:api <= page.goto succeded
  pw:api => page.check started
  pw:api <= page.check succeded
  pw:api => page.wait_for_load_state started
  pw:api <= page.wait_for_load_state succeded
  pw:api => page.click started
  pw:api <= page.click succeded
  pw:api => download.path started
  pw:api <= download.path succeded
  pw:api => download.save_as started
  pw:api <= download.save_as succeded
download suggested filename: some-file.zip
download path:/var/folders/6j/5s8qxgxd7hx_zq6wnxljr5d40000gn/T/playwright_downloads-c7yyS1/6df094f5-39af-c246-bdf9-02ccdd202354

```

webkit works as expected as well:

```
  pw:api => browser_type.launch started
  pw:api <= browser_type.launch succeded
  pw:api => browser.new_context started
  pw:api <= browser.new_context succeded
  pw:api => browser_context.new_page started
  pw:api <= browser_context.new_page succeded
  pw:api => page.goto started
  pw:api navigating to "http://localhost:8888/tree", waiting until "load" +0ms
  pw:api   navigated to "http://localhost:8888/tree" +76ms
  pw:api   "domcontentloaded" event fired +84ms
  pw:api   "load" event fired +1ms
  pw:api <= page.goto succeded
  pw:api => page.check started
  pw:api waiting for selector "//div[contains(@class, 'list_item') and contains(.//span, 'some-file.zip')]//input[@type='checkbox']" +2ms
  pw:api   selector resolved to visible <input type="checkbox" title="点击这里进行重命名或删除等操作"/> +293ms
  pw:api attempting click action +3ms
  pw:api   waiting for element to be visible, enabled and not moving +0ms
  pw:api   element is visible, enabled and does not move +27ms
  pw:api   scrolling into view if needed +0ms
  pw:api   done scrolling +1ms
  pw:api   checking that element receives pointer events at (98,703) +2ms
  pw:api   element does receive pointer events +1ms
  pw:api   performing click action +0ms
  pw:api   click action done +33ms
  pw:api   waiting for scheduled navigations to finish +0ms
  pw:api   navigations have finished +0ms
  pw:api <= page.check succeded
  pw:api => page.wait_for_load_state started
  pw:api   "networkidle" event fired +429ms
  pw:api <= page.wait_for_load_state succeded
  pw:api => page.click started
  pw:api waiting for selector "button.download-button" +2ms
  pw:api   selector resolved to visible <button title="下载" aria-label="下载" aria-describedby="too…>下载</button> +7ms
  pw:api attempting click action +2ms
  pw:api   waiting for element to be visible, enabled and not moving +0ms
  pw:api   element is visible, enabled and does not move +22ms
  pw:api   scrolling into view if needed +0ms
  pw:api   done scrolling +1ms
  pw:api   checking that element receives pointer events at (218.82,112.64) +2ms
  pw:api   element does receive pointer events +1ms
  pw:api   performing click action +0ms
  pw:api   "domcontentloaded" event fired +149ms
  pw:api   "load" event fired +0ms
  pw:api   click action done +4ms
  pw:api   waiting for scheduled navigations to finish +1ms
  pw:api   navigations have finished +0ms
  pw:api <= page.click succeded
download suggested filename: some-file.zip
  pw:api => download.path started
  pw:api <= download.path succeded
download path:/var/folders/6j/5s8qxgxd7hx_zq6wnxljr5d40000gn/T/playwright_downloads-qnoFRv/1c86dd66-671d-4dbd-994a-d7e3c2ec5c81
  pw:api => download.save_as started
  pw:api <= download.save_as succeded
```

**Comment by pavelfeldman** [comment]
Is there anything I can try running locally to reproduce this?

**Comment by zhuoqiang** [comment]
> Is there anything I can try running locally to reproduce this?

you could startup a jupyter notebook locally to reproduce it

**Comment by pavelfeldman** [comment]
Is this still an issue? Having a reproduction on a smaller context would help us addressing it a lot.

**Comment by pavelfeldman** [comment]
Closing non-actionable bugs as a part of the triage. We need more information to address your issue. Please file a new one with the questions above answered and we'll be able to help.
