### ISSUE TITLE
[BUG] could not use sync api inside jupyter notebook

### ISSUE THREAD

**Issue by zhuoqiang** [microsoft/playwright-python#480]
* Python: 3.8
* Playwright: 1.8.0a1
* OS: MacOS Catalina

the following code failed to run in jupyter notebook envrionment

```python
import playwright.sync_api
with playwright.sync_api.sync_playwright() as api:
    pass
```

it gives error

```
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
<ipython-input-19-af4d5d3f125f> in <module>
      1 import playwright.sync_api
----> 2 with playwright.sync_api.sync_playwright() as api:
      3     pass

python3.8/site-packages/playwright/sync_api/_context_manager.py in __enter__(self)
     65         self._connection.call_on_object_with_known_name("Playwright", callback_wrapper)
     66 
---> 67         dispatcher_fiber.switch()
     68         playwright = self._playwright
     69         playwright.stop = self.__exit__  # type: ignore

python3.8/site-packages/playwright/sync_api/_context_manager.py in greenlet_main()
     41 
     42             if loop.is_running():
---> 43                 raise Error(
     44                     """It looks like you are using Playwright Sync API inside the asyncio loop.
     45 Please use the Async API instead."""

Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
```

**Comment by pavelfeldman** [comment]
Jupyter notebook uses asyncio event look, so you should use async api.

**Comment by pavelfeldman** [comment]
Closing as a dupe for #462

**Comment by rloibman** [comment]
How can I use async API? What's the code?

**Comment by fabiofumarola** [comment]
```
async with async_playwright() as p:
    browser = await p.chromium.launch()
    page = await browser.new_page()
    await page.goto(your url])
```

**Comment by asheshstha** [comment]
@fabiofumarola 

Using async_playwright creates `NotImplementedError`

``` python
from playwright.async_api import async_playwright

async with async_playwright() as p:
    browser = await p.chromium.launch()
    page = await browser.new_page()
```

```
Task exception was never retrieved
future: <Task finished name='Task-8' coro=<Connection.run() done, defined at C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py:240> exception=NotImplementedError()>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 247, in run
    await self._transport.connect()
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_transport.py", line 132, in connect
    raise exc
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_transport.py", line 120, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 1675, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 498, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
```

**Comment by demelo-solutions** [comment]
I haven't tried running this on Jupyter, but I get the error with Python if I don't install some extra dependencies for Playwright.
If you run the command:
`playwright install-deps`
This probably would fix this error for Jupyter, since it fixes for me without Jupyter.

**Comment by earonesty** [comment]
i;m not using async at alll, but if you put code inside a generator, sync_playwright also bails (for no reason)

**Comment by kevcampb** [comment]
Adding a comment here for the benefit of any new users coming to this. Playwright works perfectly fine in jupyter using the async API

Screenshot here showing basic usage:

<img width="887" height="726" alt="Image" src="https://github.com/user-attachments/assets/723a0820-7c45-4b4f-9387-f3ff5b90266d" />

In this example, the mcr.microsoft.com/playwright:v1.55.0-noble is running in a different container running on port 3010, but I'm sure you can use local playwright as well.
