### ISSUE TITLE
1.8.0a1 - running from cron results in driver not being located?

### ISSUE THREAD

**Issue by Mattwmaster58** [microsoft/playwright-python#489]
Hi, with 0.171.0 I could run from a cron job. Now, whenever I try, this happens:

```py
/home/<username>/.local/lib/python3.8/site-packages/playwright/driver/playwright.sh: 2: dirname: not found
/home/<username>/.local/lib/python3.8/site-packages/playwright/driver/playwright.sh: 3: /home/<username>/node: not found
Traceback (most recent call last):
  File "/home/<username>/scriptpath/cli.py", line 18, in cli
    with sync_playwright() as p:
  File "/home/<username>/.local/lib/python3.8/site-packages/playwright/sync_api/_context_manager.py", line 68, in __enter__
    playwright = self._playwright
AttributeError: 'PlaywrightContextManager' object has no attribute '_playwright'
```

My current mitigation for this is to simply hardcode the script path but that's obviously far from ideal.

**Comment by Mattwmaster58** [comment]
Some more information: I recently set up the same script on my arch box which has `cronie==1.5.5-1`. No issues there. Only on the GCloud VM with Ubuntu 20.10 and `cron==3.0pl1-136ubuntu1`

**Comment by pavelfeldman** [comment]
Is this still happening? Could you share your script?

**Comment by Mattwmaster58** [comment]
the environment this was occurring in no longer exists, and I can't seem to repro in a similar setup

**Comment by 2dareis2do** [comment]
I have similar issue 'object has no attribute '_playwright'

I am running 1.30.x due to running on centos 7.

I believe there is issue in playwright/driver/playwright.sh

Line 2 

`SCRIPT_PATH="$(cd "$(dirname "$0")" ; pwd -P)"`

 Usually get error when running vis cron on certain web user.

e.g. 

```
failed. Exit Code: 1(General error) Working directory: /var/www/vhosts/myhost/httpdocs/web Output: ================ Error Output: ================ /usr/local/lib/python3.9/site-packages/playwright/driver/playwright.sh: line 2: dirname: command not found /usr/local/lib/python3.9/site-packages/playwright/driver/playwright.sh: line 6: /var/www/vhosts/myhost/httpdocs/web/node: No such file or directory Traceback (most recent call last): File "/var/www/vhosts/myhost/httpdocs/web/../python/google_playwright/ArticleScraping.py", line 50, in <module> newurl = accept_cookies_and_redirect_and_get_url(url) File "/var/www/vhosts/myhost/httpdocs/web/../python/google_playwright/ArticleScraping.py", line 21, in accept_cookies_and_redirect_and_get_url with sync_playwright() as p: File "/usr/local/lib/python3.9/site-packages/playwright/sync_api/_context_manager.py", line 90, in __enter__ playwright = self._playwright AttributeError: 'PlaywrightContextManager' object has no attribute '_playwright' Task was destroyed but it is pending! task: <Task pending name='Task-3' coro=<Connection.run.<locals>.init() running at /usr/local/lib/python3.9/site-packages/playwright/_impl/_connection.py:245> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f8ceafcaee0>()]> cb=[ProtocolCallback.__init__.<locals>.cb() at /usr/local/lib/python3.9/site-packages/playwright/_impl/_connection.py:168]> Future exception was never retrieved future: <Future finished exception=BrokenPipeError(32, 'Broken pipe')> Traceback (most recent call last): File "/usr/local/lib/python3.9/asyncio/unix_events.py", line 665, in write n = os.write(self._fileno, data) BrokenPipeError: [Errno 32] Broken pipe
```

from what I understand `$(dirname "$0")` is unreliable. See https://stackoverflow.com/questions/5256823/pwd-command-with-shell-script and http://mywiki.wooledge.org/BashFAQ/028


Updating to 

`SCRIPT_PATH="$(dirname -- $(readlink -fn -- "$0"))"`

to see if that is more reliable.

This has been bugging me for a while!
