### ISSUE TITLE
Pyinstaller

### ISSUE THREAD

**Issue by nubonics** [microsoft/playwright-python#524]
## Intro
I'm attempting to export a basic playwright program to an exectuable, whether this be linux or windows.
I have tried everything I can find online on how to accomplish this, however, I have not succeeded. I don't have alot of experience with pyinstaller, however, I don't think that the issue is with pyinstaller

## Reproducible steps
```
playwright version: 1.9.0
python version: 3.7.9
pyinstaller version: 4.2
pyinstaller-hooks-contrib version: 2020.11
```

A basic playwright program:
```python
# example.py
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
        browser = browser_type.launch(headless=False)
        page = browser.new_page()
        page.goto('http://whatsmyuseragent.org/')
        browser.close()
```

A simple example of pyinstaller
```
pyinstaller -w -F example.py
```

The traceback
```traceback
Traceback (most recent call last):
  File "playwright_exe_test_1.py", line 3, in <module>
  File "playwright/sync_api/_context_manager.py", line 67, in __enter__
  File "playwright/sync_api/_context_manager.py", line 48, in greenlet_main
  File "asyncio/base_events.py", line 587, in run_until_complete
  File "playwright/_impl/_connection.py", line 161, in run_as_sync
  File "playwright/_impl/_connection.py", line 166, in run
  File "playwright/_impl/_transport.py", line 67, in run
  File "asyncio/subprocess.py", line 217, in create_subprocess_exec
  File "asyncio/base_events.py", line 1544, in subprocess_exec
  File "asyncio/unix_events.py", line 190, in _make_subprocess_transport
  File "asyncio/base_subprocess.py", line 37, in __init__
  File "asyncio/unix_events.py", line 775, in _start
  File "subprocess.py", line 800, in __init__
  File "subprocess.py", line 1551, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/user/1000/_MEIGT6nHA/playwright/driver/playwright.sh': '/tmp/user/1000/_MEIGT6nHA/playwright/driver/playwright.sh'
```

**Comment by nubonics** [comment]
Solved

**Comment by analogaio** [comment]
How did you solve this? @nubonics
