### ISSUE TITLE
how to set ‘proxy-authorization' in headers?

### ISSUE THREAD

**Issue by jryzj** [microsoft/playwright-python#535]
I tried to set 'proxy-authorization' in header, by the two methods with python,
* 1
```python
headers = {"proxy-authorization":"xxxxx"}
p= sync_playwright()
browser =p.start().chromium.launch(headless=False)
b1 = browser.new_context(extra_http_headers=headers)
page = b1.new_page()
page.goto('http://localhost:3000')  #code crashed here
print(page.title())
b1.close()
```
* 2
```python
headers = {"proxy-authorization":"xxxxx"}
p= sync_playwright()
browser =p.start().chromium.launch(headless=False)
b1 = browser.new_context()
page = b1.new_page()
page.set_extra_http_headers(headers = headers)
page.goto('http://localhost:3000')    #code crashed here
print(page.title())
b1.close()
```

and then get error as below,
```ptyhon
Traceback (most recent call last):
  File "xun_playwright.py", line 39, in <module>
    page.goto('http://localhost:3000')
  File "D:\Program Files\Anaconda3\lib\site-packages\playwright\sync_api\_generated.py", line 5776, in goto
    url=url, timeout=timeout, waitUntil=wait_until, referer=referer
  File "D:\Program Files\Anaconda3\lib\site-packages\playwright\_impl\_sync_base.py", line 103, in _sync
    return task.result()
  File "D:\Program Files\Anaconda3\lib\site-packages\playwright\_impl\_page.py", line 461, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "D:\Program Files\Anaconda3\lib\site-packages\playwright\_impl\_frame.py", line 114, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "D:\Program Files\Anaconda3\lib\site-packages\playwright\_impl\_connection.py", line 36, in send
    return await self.inner_send(method, params, False)
  File "D:\Program Files\Anaconda3\lib\site-packages\playwright\_impl\_connection.py", line 47, in inner_send
    result = await callback.future
playwright._impl._api_types.Error: net::ERR_INVALID_ARGUMENT at http://localhost:3000
=========================== logs ===========================
navigating to "http://localhost:3000", waiting until "load"
============================================================
Note: use DEBUG=pw:api environment variable to capture Playwright logs.
`

Then I tried change the key name, and  at  last,  I found if key started with “proxy-", the error would happen.

Finaly, I change browser from **chromium** to **webkit**, then the code worked.

So have any idea for why?
Thanks!

**Comment by pavelfeldman** [comment]
You seem to be using proxy, why not tell Playwright to authenticate you?:

```py
browser = chromium.launch(proxy={
  "server": "http://myproxy.com:3128",
  "user": "usr",
  "password": "pwd"
})
```

**Comment by jryzj** [comment]
> You seem to be using proxy, why not tell Playwright to authenticate you?:
> 
> ```python
> browser = chromium.launch(proxy={
>   "server": "http://myproxy.com:3128",
>   "user": "usr",
>   "password": "pwd"
> })
> ```

thanks.
the scenerio is using proxy-authorization to send token, so what I meet.
