### ISSUE TITLE
can't open the chromium.

### ISSUE THREAD

**Issue by zhiming429438709** [microsoft/playwright-python#549]
I did with the tutorials

1. `pip install playwright`
2. `python -m install chromium`  it will download the chromium
3. `python -m playwright codegen --target python -o 'my.py' -b chromium https://www.baidu.com`

I execute the  C:\Users\A20060\AppData\Local\ms-playwright\chromium-854489\chrome-win\chrome.exe. nothing happend

but I can open the chromium in this path  `C:\Users\A20060\AppData\Local\Chromium\Application`

I install this chromium use the msi not the zip package.

How can I solve the chromium
```cmd
(ford_playwright1) D:\work\ford_playwright>python -m playwright codegen --target python -o 'my.py' -b chromium https://www.baidu.com
����: û���ҵ���� "15844"��
(node:5516) UnhandledPromiseRejectionWarning: browserType.launch: Protocol error (Browser.getVersion): Browser closed.
==================== Browser output: ====================
<launching> C:\Users\A20060\AppData\Local\ms-playwright\chromium-854489\chrome-win\chrome.exe --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-b
ackgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=Tr
anslateUI,BlinkGenPropertyTrees,ImprovedCookieControls,SameSiteByDefaultCookies,LazyFrameLoading --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgro
unding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --user-data-dir=C:\Users\A20060\AppData\Local\Temp\playwright_chromiumdev_profil
e-W4Ot2A --remote-debugging-pipe --no-sandbox --no-startup-window
<launched> pid=15844
[err] [0306/143808.329:ERROR:icu_util.cc(256)] Failed to initialize ICU with data file: U_INVALID_FORMAT_ERROR
[err] [0306/143808.330:FATAL:icu_util.cc(311)] Check failed: result.
[err] Backtrace:
[err]   IsSandboxedProcess [0x00007FFEB5CB9392+700450]
[err]   IsSandboxedProcess [0x00007FFEB5C3CBE2+190578]
[err]   IsSandboxedProcess [0x00007FFEB5C4BA38+251592]
[err]   IsSandboxedProcess [0x00007FFEB5C4C9C0+255568]
[err]   IsSandboxedProcess [0x00007FFEB5DFF92A+2037178]
[err]   CrashForExceptionInNonABICompliantCodeRange [0x00007FFEB5BD1268+8079592]
[err]   CrashForExceptionInNonABICompliantCodeRange [0x00007FFEB5BD09CE+8077390]
[err]   CrashForExceptionInNonABICompliantCodeRange [0x00007FFEB5BD0B3C+8077756]
[err]   ChromeMain [0x00007FFEB331123F+415]
[err]   Ordinal0 [0x00007FF757F32612+9746]
[err]   Ordinal0 [0x00007FF757F31A31+6705]
[err]   GetHandleVerifier [0x00007FF75807D4D2+914210]
[err]   BaseThreadInitThunk [0x00007FFF1D2F7BD4+20]
[err]   RtlUserThreadStart [0x00007FFF1DDACED1+33]
[err]
=========================== logs ===========================
<launching> C:\Users\A20060\AppData\Local\ms-playwright\chromium-854489\chrome-win\chrome.exe --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-b
ackgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=Tr
anslateUI,BlinkGenPropertyTrees,ImprovedCookieControls,SameSiteByDefaultCookies,LazyFrameLoading --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgro
unding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --user-data-dir=C:\Users\A20060\AppData\Local\Temp\playwright_chromiumdev_profil
e-W4Ot2A --remote-debugging-pipe --no-sandbox --no-startup-window
<launched> pid=15844
[err] [0306/143808.329:ERROR:icu_util.cc(256)] Failed to initialize ICU with data file: U_INVALID_FORMAT_ERROR
[err] [0306/143808.330:FATAL:icu_util.cc(311)] Check failed: result.
[err] Backtrace:
[err]   IsSandboxedProcess [0x00007FFEB5CB9392+700450]
[err]   IsSandboxedProcess [0x00007FFEB5C3CBE2+190578]
[err]   IsSandboxedProcess [0x00007FFEB5C4BA38+251592]
[err]   IsSandboxedProcess [0x00007FFEB5C4C9C0+255568]
[err]   IsSandboxedProcess [0x00007FFEB5DFF92A+2037178]
[err]   CrashForExceptionInNonABICompliantCodeRange [0x00007FFEB5BD1268+8079592]
[err]   CrashForExceptionInNonABICompliantCodeRange [0x00007FFEB5BD09CE+8077390]
[err]   CrashForExceptionInNonABICompliantCodeRange [0x00007FFEB5BD0B3C+8077756]
[err]   ChromeMain [0x00007FFEB331123F+415]
[err]   Ordinal0 [0x00007FF757F32612+9746]
[err]   Ordinal0 [0x00007FF757F31A31+6705]
[err]   GetHandleVerifier [0x00007FF75807D4D2+914210]
[err]   BaseThreadInitThunk [0x00007FFF1D2F7BD4+20]
[err]   RtlUserThreadStart [0x00007FFF1DDACED1+33]
[err]
============================================================
Note: use DEBUG=pw:api environment variable to capture Playwright logs.Error
    at Object.captureStackTrace (D:\ENVS\Envs\ford_playwright1\Lib\site-packages\playwright\driver\package\lib\utils\stackTrace.js:48:19)
    at Connection.sendMessageToServer (D:\ENVS\Envs\ford_playwright1\Lib\site-packages\playwright\driver\package\lib\client\connection.js:69:48)
    at Proxy.<anonymous> (D:\ENVS\Envs\ford_playwright1\Lib\site-packages\playwright\driver\package\lib\client\channelOwner.js:64:61)
    at D:\ENVS\Envs\ford_playwright1\Lib\site-packages\playwright\driver\package\lib\client\browserType.js:64:67
    at BrowserType._wrapApiCall (D:\ENVS\Envs\ford_playwright1\Lib\site-packages\playwright\driver\package\lib\client\channelOwner.js:77:34)
    at BrowserType.launch (D:\ENVS\Envs\ford_playwright1\Lib\site-packages\playwright\driver\package\lib\client\browserType.js:55:21)
    at launchContext (D:\ENVS\Envs\ford_playwright1\Lib\site-packages\playwright\driver\package\lib\cli\cli.js:200:39)
    at codegen (D:\ENVS\Envs\ford_playwright1\Lib\site-packages\playwright\driver\package\lib\cli\cli.js:299:62)
    at Command.<anonymous> (D:\ENVS\Envs\ford_playwright1\Lib\site-packages\playwright\driver\package\lib\cli\cli.js:101:5)
    at Command.listener [as _actionHandler] (D:\ENVS\Envs\ford_playwright1\Lib\site-packages\playwright\driver\package\node_modules\commander\index.js:426:31)
(node:5516) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To
 terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:5516) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mxschmitt** [comment]
Which version of Windows are you using?

**Comment by pavelfeldman** [comment]
We need more info to address your issue. Please feel free to open a new one with the additional details requested above.
