### ISSUE TITLE
What will CentOS do in this situation？

### ISSUE THREAD

**Issue by Shimon-Cheung** [microsoft/playwright-python#555]
Traceback (most recent call last):
  File "demo.py", line 32, in <module>
    work.run()
  File "demo.py", line 18, in run
    browser = p.webkit.launch(headless=True, slow_mo=1000)
  File "/root/miniconda3/lib/python3.8/site-packages/playwright/sync_api/_generated.py", line 8915, in launch
    self._sync(
  File "/root/miniconda3/lib/python3.8/site-packages/playwright/_impl/_sync_base.py", line 103, in _sync
    return task.result()
  File "/root/miniconda3/lib/python3.8/site-packages/playwright/_impl/_browser_type.py", line 74, in launch
    raise e
  File "/root/miniconda3/lib/python3.8/site-packages/playwright/_impl/_browser_type.py", line 70, in launch
    return from_channel(await self._channel.send("launch", params))
  File "/root/miniconda3/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 36, in send
    return await self.inner_send(method, params, False)
  File "/root/miniconda3/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 47, in inner_send
    result = await callback.future
playwright._impl._api_types.Error: Host system is missing dependencies!

  Install missing packages with:
      sudo apt-get install gstreamer1.0-libav

  Missing libraries we didn't find packages for:
      libvpx.so.6
      libwoff2dec.so.1.0.2
      libgcrypt.so.20
      libjpeg.so.8
      libpng16.so.16
      libwebpdemux.so.2
      libwebp.so.6
      libicui18n.so.66
      libicuuc.so.66

**Comment by SansLang** [comment]
https://github.com/microsoft/playwright/issues/5506

**Comment by marcelogrsp** [comment]
Check my answer [here](https://github.com/microsoft/playwright/issues/5506#issuecomment-822876115)

**Comment by kumaraditya303** [comment]
https://github.com/microsoft/playwright/issues/6219 :+1: the issue if you want playwright on centos @Shimon-Cheung
