### ISSUE TITLE
 Async call browser.close() to trigger I/O operation on closed pipe

### ISSUE THREAD

**Issue by Magicskys** [microsoft/playwright-python#590]
**Context:**
- Playwright Version: playwright-1.9.2
- Operating System: Windows
- Python version: 3.8.5
- Browser: All
- Extra: Windows 21332.1010

**Code Snippet**
```python
async def main():
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=False)
        user_context = await browser.new_context()
        page = await user_context.new_page()
        await page.goto('http://192.168.3.112:8080')
        await asyncio.sleep(2)
        await browser.close()


if __name__ == '__main__':
    asyncio.run(main())
```

**Describe the bug**
When I call browser.close() it triggers an exception
```
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x00000246909AF0D0>
Traceback (most recent call last):
  File "G:\ProgramData\Anaconda3\envs\work38\lib\asyncio\base_subprocess.py", line 126, in __del__
    self.close()
  File "G:\ProgramData\Anaconda3\envs\work38\lib\asyncio\base_subprocess.py", line 104, in close
    proto.pipe.close()
  File "G:\ProgramData\Anaconda3\envs\work38\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "G:\ProgramData\Anaconda3\envs\work38\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "G:\ProgramData\Anaconda3\envs\work38\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000246909C9820>
Traceback (most recent call last):
  File "G:\ProgramData\Anaconda3\envs\work38\lib\asyncio\proactor_events.py", line 115, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
  File "G:\ProgramData\Anaconda3\envs\work38\lib\asyncio\proactor_events.py", line 79, in __repr__
    info.append(f'fd={self._sock.fileno()}')
  File "G:\ProgramData\Anaconda3\envs\work38\lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
```

**Comment by kumaraditya303** [comment]
Try running the script with env var `DEBUG=pw:api` and paste the output here

**Comment by Magicskys** [comment]
After setting environment variables DEBUG=pw:api, the following error is prompted
```
2021-03-23T02:00:34.723Z pw:api navigating to "http://192.168.3.112:8080", waiting until "load"
2021-03-23T02:00:34.769Z pw:api   navigated to "http://192.168.3.112:8080/"
2021-03-23T02:00:36.892Z pw:api   "domcontentloaded" event fired
2021-03-23T02:00:37.006Z pw:api   "load" event fired
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x000001CF2FC0F160>
Traceback (most recent call last):
  File "G:\ProgramData\Anaconda3\envs\work38\lib\asyncio\base_subprocess.py", line 126, in __del__
    self.close()
  File "G:\ProgramData\Anaconda3\envs\work38\lib\asyncio\base_subprocess.py", line 104, in close
    proto.pipe.close()
  File "G:\ProgramData\Anaconda3\envs\work38\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "G:\ProgramData\Anaconda3\envs\work38\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "G:\ProgramData\Anaconda3\envs\work38\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001CF2FC268B0>
Traceback (most recent call last):
  File "G:\ProgramData\Anaconda3\envs\work38\lib\asyncio\proactor_events.py", line 115, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
  File "G:\ProgramData\Anaconda3\envs\work38\lib\asyncio\proactor_events.py", line 79, in __repr__
    info.append(f'fd={self._sock.fileno()}')
  File "G:\ProgramData\Anaconda3\envs\work38\lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe

```

**Comment by Magicskys** [comment]
> Try running the script with env var `DEBUG=pw:api` and paste the output here

After setting environment variables DEBUG=pw:api, the following error is prompted
```
2021-03-23T02:00:34.723Z pw:api navigating to "http://192.168.3.112:8080", waiting until "load"
2021-03-23T02:00:34.769Z pw:api   navigated to "http://192.168.3.112:8080/"
2021-03-23T02:00:36.892Z pw:api   "domcontentloaded" event fired
2021-03-23T02:00:37.006Z pw:api   "load" event fired
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x000001CF2FC0F160>
Traceback (most recent call last):
  File "G:\ProgramData\Anaconda3\envs\work38\lib\asyncio\base_subprocess.py", line 126, in __del__
    self.close()
  File "G:\ProgramData\Anaconda3\envs\work38\lib\asyncio\base_subprocess.py", line 104, in close
    proto.pipe.close()
  File "G:\ProgramData\Anaconda3\envs\work38\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "G:\ProgramData\Anaconda3\envs\work38\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "G:\ProgramData\Anaconda3\envs\work38\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001CF2FC268B0>
Traceback (most recent call last):
  File "G:\ProgramData\Anaconda3\envs\work38\lib\asyncio\proactor_events.py", line 115, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
  File "G:\ProgramData\Anaconda3\envs\work38\lib\asyncio\proactor_events.py", line 79, in __repr__
    info.append(f'fd={self._sock.fileno()}')
  File "G:\ProgramData\Anaconda3\envs\work38\lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
````

**Comment by pavelfeldman** [comment]
I believe this was fixed in https://github.com/microsoft/playwright-python/pull/593. Could you try updating Playwright to 1.10 and checking it there?

**Comment by pavelfeldman** [comment]
Assuming it was fixed, closing!
