### ISSUE TITLE
failed to install from latest master branch

### ISSUE THREAD

**Issue by x0day** [microsoft/playwright-python#668]
steps:

```
pip install git+https://github.com/microsoft/playwright-python
```

or

```
pip install auditwheel
git clone https://github.com/microsoft/playwright-python
cd playwright-python
python setup.py bdist_wheel
```

```bash
removing build/bdist.macosx-10.9-x86_64/wheel
Traceback (most recent call last):
  File "setup.py", line 133, in <module>
    setup(
  File "/Users/x/.miniconda3/envs/py38/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/Users/x/.miniconda3/envs/py38/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/x/.miniconda3/envs/py38/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/x/.miniconda3/envs/py38/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 120, in run
    with InWheel(
TypeError: __init__() got an unexpected keyword argument 'ret_self'
```

**Comment by x0day** [comment]
auditwheel 4.0.0 released 2days ago, and changed `InWheel` api, so it's a bug.

**Comment by kumaraditya303** [comment]
I am on a PR it would be fixed.
