### ISSUE TITLE
Proxy with authentication doesn't work [Doc bug]

### ISSUE THREAD

**Issue by fawazahmed0** [microsoft/playwright-python#716]
Please see [this comment](https://github.com/microsoft/playwright-python/issues/716#issuecomment-847096149)

**Details:**
Python 3.9.2
Playwright 1.11.2
Windows 10

**Code To reproduce:**
```python
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.firefox.launch(proxy={
  "server": "http://172.22.35.253:8888",
  "user": "admin",
  "password": "1234"
})
    page = browser.new_page()
    page.goto("http://icanhazip.com")
    print(page.text_content("body").strip())
    browser.close()
```

**Output:**
```
  pw:api   navigated to "about:blank" +0ms
  pw:api   navigated to "about:blank" +168ms
  pw:api navigating to "http://icanhazip.com", waiting until "load" +11ms
Traceback (most recent call last):
  File "C:\Users\nawaz\Desktop\scrape\basic.py", line 10, in <module>
    page.goto("http://icanhazip.com")
  File "C:\Users\nawaz\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\sync_api\_generated.py", line 5954, in goto
    self._sync(
  File "C:\Users\nawaz\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\_impl\_sync_base.py", line 103, in _sync
    return task.result()
  File "C:\Users\nawaz\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\_impl\_page.py", line 470, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Users\nawaz\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\_impl\_frame.py", line 117, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Users\nawaz\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\_impl\_connection.py", line 36, in send
    return await self.inner_send(method, params, False)
  File "C:\Users\nawaz\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\_impl\_connection.py", line 54, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: NS_ERROR_PROXY_CONNECTION_REFUSED
=========================== logs ===========================
navigating to "http://icanhazip.com", waiting until "load"
============================================================
Note: use DEBUG=pw:api environment variable to capture Playwright logs.
```

**Other Things**
My local proxy is working fine, I have tested it
```
$ curl -x http://admin:1234@172.22.35.253:8888 http://icanhazip.com
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    13  100    13    0     0    276      0 --:--:-- --:--:-- --:--:--   276



```

Also, you can setup a local proxy with authentication by following [this](https://stackoverflow.com/a/67671720/2437224)

Thanks

**Comment by fawazahmed0** [comment]
Oh, man ,I wasted so much time on this, the issue is with the [documentation](https://playwright.dev/python/docs/network?_highlight=prox#http-proxy)

The `user` should be `username`

**Comment by mxschmitt** [comment]
Sorry for the inconvenience and that you run into this issue, I created a [PR](https://github.com/microsoft/playwright/pull/6716) to fix it for future users.

**Comment by srkeyan** [comment]
Same problem, same wasted much time

**Comment by mxschmitt** [comment]
I created another PR to backport it: https://github.com/microsoft/playwright.dev/pull/227 :/
