### ISSUE TITLE
[BUG]dirver/playwright.sh not support path with space

### ISSUE THREAD

**Issue by juseedom** [microsoft/playwright-python#766]
**Context:**

- Playwright Version: 1.12.1 (playwright driver v1.12.0-1623185968000)
- Operating System: Mac Catalina
- Python Version: 3.9

```
 % /Users/xxxx/Documents/CODES/yyyy/dist 5/zzzz.app/Contents/MacOS/zzzz 
/Users/xxxx/Documents/CODES/yyyy/dist 5/zzzz.app/Contents/Resources/lib/python3.9/playwright/driver/playwright.sh: line 3: /Users/xxxx/Documents/CODES/yyyy/dist: No such file or directory
Traceback (most recent call last):
  File "zzzz.pyc", line 107, in __init__
  File "/Users/xxxx/Documents/CODES/yyyy/dist 5/zzzz.app/Contents/Resources/lib/python3.9/playwright/sync_api/_context_manager.py", line 75, in start
  File "/Users/xxxx/Documents/CODES/yyyy/dist 5/zzzz.app/Contents/Resources/lib/python3.9/playwright/sync_api/_context_manager.py", line 70, in __enter__
AttributeError: 'PlaywrightContextManager' object has no attribute '_playwright'
```

**Code Snippet**

```python
...  
playwright = sync_playwright().start()
browser = playwright.webkit.launch(headless=True, executable_path=_path)
context = browser.new_context(ignore_https_errors=True)

```

**Describe the bug**

normally when playwright installed, the path of dirver/playwirght will be under virtual environment path without any spaces inside. however, after package with py2app, there might be space in absolute path depends on the file location of *.app
**After adding double quotation marks, the issue resolved**

**Potential Fix**
```shell
# original playwright.sh
#!/bin/sh
SCRIPT_PATH="$(cd "$(dirname "$0")" ; pwd -P)"
$SCRIPT_PATH/node $SCRIPT_PATH/package/lib/cli/cli.js "$@". #<-- add double quotation here

# suggested playwright.sh
#!/bin/sh
SCRIPT_PATH="$(cd "$(dirname "$0")" ; pwd -P)"
"$SCRIPT_PATH/node" "$SCRIPT_PATH/package/lib/cli/cli.js" "$@"
```

**Comment by mxschmitt** [comment]
Thank you for your great investigation, I created a patch with the fix in https://github.com/microsoft/playwright/pull/7240.
