### ISSUE TITLE
[BUG] Firefox fails to start on linux: XPCOMGlueLoad  error -> /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.30' not found (required by .../firefox/libnspr4.so)

### ISSUE THREAD

**Issue by sell1fawn** [microsoft/playwright-python#779]
With the following snippet:

```python
with sync_playwright() as p:
    browser = p.firefox.launch()
    page = browser.new_page()
    page.goto('http://whatsmyuseragent.org/')
    page.screenshot(path=f'example-{i}.png')
    browser.close()
```

on a freshly installed debian buster we get:

```
Traceback (most recent call last):
  File "/home/user/PycharmProjects/my_project/tmp.py", line 17, in <module>
    browser = p.firefox.launch()
  File "/home/user/PycharmProjects/my_project/venv/lib/python3.9/site-packages/playwright/sync_api/_generated.py", line 9430, in launch
    self._sync(
  File "/home/user/PycharmProjects/my_project/venv/lib/python3.9/site-packages/playwright/_impl/_sync_base.py", line 103, in _sync
    return task.result()
  File "/home/user/PycharmProjects/my_project/venv/lib/python3.9/site-packages/playwright/_impl/_browser_type.py", line 90, in launch
    raise e
  File "/home/user/PycharmProjects/my_project/venv/lib/python3.9/site-packages/playwright/_impl/_browser_type.py", line 86, in launch
    return from_channel(await self._channel.send("launch", params))
  File "/home/user/PycharmProjects/my_project/venv/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 36, in send
    return await self.inner_send(method, params, False)
  File "/home/user/PycharmProjects/my_project/venv/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 54, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Protocol error (Browser.enable): Browser closed.
==================== Browser output: ====================
<launching> /home/user/.cache/ms-playwright/firefox-1271/firefox/firefox -no-remote -headless -profile /tmp/playwright_firefoxdev_profile-n6pvvQ -juggler-pipe -silent
<launched> pid=12432
[pid=12432][err] XPCOMGlueLoad error for file /home/user/.cache/ms-playwright/firefox-1271/firefox/libnspr4.so:
[pid=12432][err] /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.30' not found (required by /home/user/.cache/ms-playwright/firefox-1271/firefox/libnspr4.so)
[pid=12432][err] Couldn't load XPCOM.
[pid=12432] <process did exit: exitCode=255, signal=null>
[pid=12432] starting temporary directories cleanup
=========================== logs ===========================
<launching> /home/user/.cache/ms-playwright/firefox-1271/firefox/firefox -no-remote -headless -profile /tmp/playwright_firefoxdev_profile-n6pvvQ -juggler-pipe -silent
<launched> pid=12432
[pid=12432][err] XPCOMGlueLoad error for file /home/user/.cache/ms-playwright/firefox-1271/firefox/libnspr4.so:
[pid=12432][err] /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.30' not found (required by /home/user/.cache/ms-playwright/firefox-1271/firefox/libnspr4.so)
[pid=12432][err] Couldn't load XPCOM.
[pid=12432] <process did exit: exitCode=255, signal=null>
[pid=12432] starting temporary directories cleanup
============================================================
Note: use DEBUG=pw:api environment variable to capture Playwright logs.
python-BaseException

Process finished with exit code 1
```
I have already verified that "glibc" which seems to be called libc6 on debian is installed.
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libc6 is already the newest version (2.28-10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

> On comparing the version numbers _2.28-10_, installed on the local machine, and _2.30_ which is mentioned in the traceback, could it be a possibility, that playwright is asking for a newer version of this library?

And if that would be the case not even debian backports would have 2.30 available yet - see https://sources.debian.org/src/glibc/

**Comment by mxschmitt** [comment]
Only Ubuntu 18.04/20.04 are officially supported see [here](https://playwright.dev/docs/intro#system-requirements). With Debian, you might run into issues with operating system dependencies - like in your case. I would recommend to use Ubuntu 20.04 instead, and then the CLI command to install the dependencies `playwright install-deps` which we have will work out of the box. See here: https://playwright.dev/docs/cli#install-system-dependencies

**Comment by sell1fawn** [comment]
I have setup an ubuntu 20.04 and can confirm it works perfectly. I got distracted by the big green icons inside this one : ).
![image](https://user-images.githubusercontent.com/86576508/123663203-78b69f80-d836-11eb-9372-d4334fca1600.png)
