### ISSUE TITLE
How to use chrome extensions on Playwright in python, such as ad blocking, etc.

### ISSUE THREAD

**Issue by djkcyl** [microsoft/playwright-python#782]
The webpage I need to operate has too many advertisements, which affect the screenshots. I need to use some ad blocking extensions to block ads

**Comment by mxschmitt** [comment]
You can load extensions like that (is soon also in the docs):

```py
from playwright.async_api import sync_playwright
path_to_extension = "./my-extension"
user_data_dir = "/tmp/test-user-data-dir"
def run(playwright):
    context = playwright.chromium.launch_persistent_context(
        user_data_dir,
        headless=False,
        args=[
            f"--disable-extensions-except={path_to_extension}",
            f"--load-extension={path_to_extension}",
        ],
    )
    background_page = context.background_pages[0]
    # Test the background page as you would any other page.
    context.close()
with sync_playwright() as playwright:
    run(playwright)
```

In your case, you can use e.g. [U Block Origin, download it from GitHub](https://github.com/gorhill/uBlock) and add it when launching Chromium.

**Comment by djkcyl** [comment]
```
Failed to launch: Error: spawn /root/bot/plugins/ABot/saya/ChineseDict/chrome/data EACCES\n=========================== logs ===========================\n<launching> /root/bot/plugins/ABot/saya/ChineseDict/chrome/data --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI,BlinkGenPropertyTrees,ImprovedCookieControls,SameSiteByDefaultCookies,LazyFrameLoading,GlobalMediaControls --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --user-data-dir=/tmp/playwright_chromiumdev_profile-HXyCZf --remote-debugging-pipe --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --disable-extensions-except=/root/bot/plugins/ABot/saya/ChineseDict/chrome/extension --load-extension=/root/bot/plugins/ABot/saya/ChineseDict/chrome/extension --no-startup-window\n[_pid=N/A] starting temporary directories cleanup\n[_pid=N/A] finished temporary directories cleanup\n============================================================\nNote: use DEBUG=pw:api environment variable to capture Playwright logs.'
Traceback (most recent call last):
  File "/root/bot/plugins/ABot/saya/ChineseDict/__init__.py", line 53, in fun_dict
    image_b64 = await get_hans_screenshot(url)
  File "/root/bot/plugins/ABot/saya/ChineseDict/page_screenshot.py", line 27, in get_hans_screenshot
    browser = await get_browser()
  File "/root/bot/plugins/ABot/saya/ChineseDict/page_screenshot.py", line 23, in get_browser
    return _browser or await init(**kwargs)
  File "/root/bot/plugins/ABot/saya/ChineseDict/page_screenshot.py", line 18, in init
    _browser = await browser.chromium.launch(executable_path=USER_DIR, args=args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/abot-r4AbEI-h-py3.8/lib/python3.8/site-packages/playwright/async_api/_generated.py", line 9485, in launch
    await self._async(
  File "/root/.cache/pypoetry/virtualenvs/abot-r4AbEI-h-py3.8/lib/python3.8/site-packages/playwright/_impl/_browser_type.py", line 90, in launch
    raise e
  File "/root/.cache/pypoetry/virtualenvs/abot-r4AbEI-h-py3.8/lib/python3.8/site-packages/playwright/_impl/_browser_type.py", line 86, in launch
    return from_channel(await self._channel.send("launch", params))
  File "/root/.cache/pypoetry/virtualenvs/abot-r4AbEI-h-py3.8/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 36, in send
    return await self.inner_send(method, params, False)
  File "/root/.cache/pypoetry/virtualenvs/abot-r4AbEI-h-py3.8/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 54, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Failed to launch: Error: spawn /root/bot/plugins/ABot/saya/ChineseDict/chrome/data EACCES
=========================== logs ===========================
<launching> /root/bot/plugins/ABot/saya/ChineseDict/chrome/data --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI,BlinkGenPropertyTrees,ImprovedCookieControls,SameSiteByDefaultCookies,LazyFrameLoading,GlobalMediaControls --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --user-data-dir=/tmp/playwright_chromiumdev_profile-HXyCZf --remote-debugging-pipe --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --disable-extensions-except=/root/bot/plugins/ABot/saya/ChineseDict/chrome/extension --load-extension=/root/bot/plugins/ABot/saya/ChineseDict/chrome/extension --no-startup-window
[pid=N/A] starting temporary directories cleanup
[pid=N/A] finished temporary directories cleanup
============================================================
Note: use DEBUG=pw:api environment variable to capture Playwright logs.
```

```
import base64

from typing import Optional
from playwright.async_api import Browser, async_playwright


CHROME_DATA = '/root/bot/plugins/ABot/saya/ChineseDict/chrome'
USER_DIR = f'{CHROME_DATA}/data'

_browser: Optional[Browser] = None
pathToPac = ''

async def init(**kwargs) -> Browser:
    args = [f"--disable-extensions-except={CHROME_DATA}/extension",
            f"--load-extension={CHROME_DATA}/extension"]
    
    global _browser
    browser = await async_playwright().start()
    _browser = await browser.chromium.launch(executable_path=USER_DIR, args=args, **kwargs)
    return _browser


async def get_browser(**kwargs) -> Browser:
    return _browser or await init(**kwargs)


async def get_hans_screenshot(url):
    browser = await get_browser()
    page = None
    try:
        page = await browser.new_page()
        await page.goto(url, wait_until='load', timeout=10000)
        await page.set_viewport_size({"width": 1500, "height": 6880})
        card = await page.query_selector(".shiyi_content")
        # await page.evaluate()
        assert card is not None
        image = await card.screenshot(type='jpeg', quality=90)
        await page.close()
        return base64.b64encode(image).decode()
    except Exception:
        if page:
            await page.close()
        raise
```

**Comment by mxschmitt** [comment]
Closing since the following works for me:

```
# Download this and extract it:
# https://github.com/gorhill/uBlock/releases/download/1.36.2/uBlock0_1.36.2.chromium.zip

from playwright.sync_api import sync_playwright

path_to_extension = "./uBlock0.chromium"
user_data_dir = "/tmp/test-user-data-dir"

def run(playwright):
    context = playwright.chromium.launch_persistent_context(
        user_data_dir,
        headless=False,
        args=[
            f"--disable-extensions-except={path_to_extension}",
            f"--load-extension={path_to_extension}",
        ],
    )
    page = context.new_page()
    page.wait_for_timeout(1000) # wait until uBlock Origin is initialised
    page.goto("https://blockads.fivefilters.org/")
    # Test the background page as you would any other page.
    context.close()
with sync_playwright() as playwright:
    run(playwright)
```

Google Chrome data dirs and Playwright dirs are not compatible, thats why you are getting this error.

**Comment by clin-ro** [comment]
is it possible that the issue comes from running the browser headless? 😅
