### ISSUE TITLE
No module named 'filelock' exit status 1

### ISSUE THREAD

**Issue by H077y** [microsoft/playwright-python#787]
When attempting to install the package via repl.it, it returns an error:

```
--> python3 -m poetry add playwright
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/poetry/__main__.py", line 5, in <module>
    from .console import main
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/poetry/console/application.py", line 7, in <module>
    from .commands.about import AboutCommand
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/poetry/console/commands/__init__.py", line 4, in <module>
    from .check import CheckCommand
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/poetry/console/commands/check.py", line 2, in <module>
    from poetry.factory import Factory
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/poetry/factory.py", line 18, in <module>
    from .repositories.pypi_repository import PyPiRepository
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/poetry/repositories/pypi_repository.py", line 33, in <module>
    from ..inspection.info import PackageInfo
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/poetry/inspection/info.py", line 25, in <module>
    from poetry.utils.env import EnvCommandError
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/poetry/utils/env.py", line 23, in <module>
    import virtualenv
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/virtualenv/__init__.py", line 3, in <module>
    from .run import cli_run, session_via_cli
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/virtualenv/run/__init__.py", line 7, in <module>
    from ..app_data import make_app_data
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/virtualenv/app_data/__init__.py", line 12, in <module>
    from .read_only import ReadOnlyAppData
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/virtualenv/app_data/read_only.py", line 3, in <module>
    from virtualenv.util.lock import NoOpFileLock
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/virtualenv/util/lock.py", line 10, in <module>
    from filelock import FileLock, Timeout
ModuleNotFoundError: No module named 'filelock'
exit status 1
```

I'm not sure what's causing this as I simply pressed `Add`. Not sure if it's an issue with repl.it or with the extension

**Comment by mxschmitt** [comment]
I tried it via running in the shell:

```bash
pip install playwright
python -m playwright install
```

which works for me. I was then able to launch a Chromium browser.

**Comment by mxschmitt** [comment]
Closed since it seems stale.
