### ISSUE TITLE
[Bug]: pyinstaller/pyarmor pack error

### ISSUE THREAD

**Issue by niewiemczego** [microsoft/playwright-python#810]
### Playwright version

1.12.0

### Operating system

Windows

### What browsers are you seeing the problem on?

Firefox

### What happened? / Describe the bug

after using pyarmor pack command to make .py to .exe I got weird error

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "<frozen lightningcli_reworked>", line 1303, in asensio_generator_loop
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "<frozen lightningcli_reworked>", line 179, in main_generator
  File "playwright\async_api\_context_manager.py", line 47, in __aenter__
  File "playwright\_impl\_transport.py", line 108, in run
  File "asyncio\subprocess.py", line 236, in create_subprocess_exec
  File "asyncio\base_events.py", line 1630, in subprocess_exec
  File "asyncio\windows_events.py", line 389, in _make_subprocess_transport
  File "asyncio\base_subprocess.py", line 36, in __init__
  File "asyncio\windows_events.py", line 885, in _start
  File "asyncio\windows_utils.py", line 153, in __init__
  File "subprocess.py", line 858, in __init__
  File "subprocess.py", line 1311, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by mxschmitt** [comment]
Pyinstaller is not officially supported, folding into #513.
