### ISSUE TITLE
[Bug]: File download is not working in Webkit with Web Assembly

### ISSUE THREAD

**Issue by apple-blossom** [microsoft/playwright-python#821]
### Playwright version

Version 1.13.0-1626733671000.

### Operating system

Linux

### What browsers are you seeing the problem on?

WebKit

### Other information

Python 3.8
Ubuntu 20.04.2 LTS
.NET 5
Radzen.Blazor 3.5.2

### What happened? / Describe the bug

Our website is created with .Net Blazor and uses Web Assembly and file downloading is not working in Webkit, but works in other browsers. Downloading fails on timeout:
```
Traceback (most recent call last):
  File "test-pw.py", line 39, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "test-pw.py", line 33, in main
    await page.click("#profileLink")
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_async_base.py", line 54, in __aexit__
    await self._event.value
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_async_base.py", line 35, in value
    return mapping.from_maybe_impl(await self._future)
playwright._impl._api_types.TimeoutError: Timeout while waiting for event "download"
```

Manually downloading works fine in Safari. 

### Code snippet to reproduce your bug

```shell
mport asyncio
import time
from playwright.async_api import async_playwright

async def page_scr(pag):
    await pag.screenshot()

async def bro_close(bro):
    await bro.close()

async def main():
    async with async_playwright() as p:
        browser = await p.webkit.launch(downloads_path="./downloads")
        context = await browser.new_context(accept_downloads=True)
        page = await context.new_page()
        await page.goto(url)
        await page.fill(".visible-lg #signInFormUsername", "...")
        await page.fill(".visible-lg #signInFormPassword", "...")
        await page.click("//*[contains(@class, 'visible-lg')]//input[@name='signInSubmitButton']")
        await page.goto(url)
        time.sleep(10)
        await page_scr(page)
        await page.wait_for_selector("//button/span[text()='Details']")
        await page.click('//a[contains(text(),"TEST00444 231-PA-010")]')
        await page.wait_for_selector("#profileLink")
        async with page.expect_download() as download_info:
            await page.click("#profileLink")
        download = await download_info.value
        path = await download.path()
        time.sleep(20)
        await bro_close(browser)
asyncio.run(main())
```

**Comment by mxschmitt** [comment]
Would it be possible to share logs with us via the `DEBUG=pw:api` environment variable? Also the URL would be useful, so we can test it ourselves.

**Comment by apple-blossom** [comment]
Here is a detailed log where you can also find a url if it helps, but you can only access the home page as we can't give user  credentials:
`# DEBUG=pw:api python3 test-pw.py
  pw:api navigating to "https://dbtenderapp.de/login", waiting until "load" +0ms
  pw:api   navigated to "...eu-central-1.amazoncognito.com/login..." +1s
  pw:api   "domcontentloaded" event fired +837ms
  pw:api   "load" event fired +0ms
  pw:api waiting for selector ".visible-lg #signInFormUsername" +6ms
  pw:api   selector resolved to visible <input type="text" required="" name="username" autocapi…/> +60ms
  pw:api elementHandle.fill("...username...") +3ms
  pw:api   waiting for element to be visible, enabled and editable +0ms
  pw:api   element is visible, enabled and editable +15ms
  pw:api waiting for selector ".visible-lg #signInFormPassword" +11ms
  pw:api   selector resolved to visible <input required="" name="password" type="password" plac…/> +8ms
  pw:api elementHandle.fill("...password...") +4ms
  pw:api   waiting for element to be visible, enabled and editable +0ms
  pw:api   element is visible, enabled and editable +10ms
  pw:api waiting for selector "//*[contains(@class, 'visible-lg')]//input[@name='signInSubmitButton']" +9ms
  pw:api   selector resolved to visible <input type="Submit" value="Sign in" aria-label="submit…/> +9ms
  pw:api attempting click action +5ms
  pw:api   waiting for element to be visible, enabled and stable +0ms
  pw:api   element is visible, enabled and stable +34ms
  pw:api   scrolling into view if needed +0ms
  pw:api   done scrolling +3ms
  pw:api   checking that element receives pointer events at (640,303) +3ms
  pw:api   element does receive pointer events +3ms
  pw:api   performing click action +1ms
  pw:api   click action done +56ms
  pw:api   waiting for scheduled navigations to finish +1ms
  pw:api   navigations have finished +688ms
  pw:api navigating to "https://dbtenderapp.de/tenders", waiting until "load" +3ms
  pw:api   navigated to "https://dbtenderapp.de/tenders" +210ms
  pw:api   "domcontentloaded" event fired +503ms
  pw:api   "load" event fired +380ms
  pw:api   "networkidle" event fired +2s
  pw:api   navigated to "https://dbtenderapp.de/tenders" +2s
  pw:api   "domcontentloaded" event fired +359ms
  pw:api   "load" event fired +1ms
  pw:api   "networkidle" event fired +719ms
  pw:api waiting for selector "//button/span[text()='Details']" to be visible +5s
  pw:api   selector resolved to 3 elements. Proceeding with the first one. +24ms
  pw:api   selector resolved to visible <span class="rz-button-text">Details</span> +1ms
  pw:api waiting for selector "//a[contains(text(),"TEST00444 231-PA-010")]" +9ms
  pw:api   selector resolved to visible <a href="tenders/3fa85f64-5717-4562-b3fc-2c963f66bb…>TEST00444 231-PA-010</a> +7ms
  pw:api attempting click action +3ms
  pw:api   waiting for element to be visible, enabled and stable +0ms
  pw:api   element is visible, enabled and stable +37ms
  pw:api   scrolling into view if needed +0ms
  pw:api   done scrolling +1ms
  pw:api   checking that element receives pointer events at (115.87,346.12) +4ms
  pw:api   element does receive pointer events +4ms
  pw:api   performing click action +0ms
  pw:api   navigated to "https://dbtenderapp.de/tenders/3fa85f64-5717-4562-b3fc-2c963f66bba7" +50ms
  pw:api   click action done +225ms
  pw:api   waiting for scheduled navigations to finish +0ms
  pw:api   navigations have finished +0ms
  pw:api waiting for selector "#profileLink" to be visible +3ms
  pw:api   selector resolved to 3 elements. Proceeding with the first one. +112ms
  pw:api   selector resolved to visible <a download="" target="_blank" id="profileLink" cla…>…</a> +15ms
  pw:api waiting for selector "#profileLink" +66ms
  pw:api   selector resolved to 3 elements. Proceeding with the first one. +7ms
  pw:api   selector resolved to visible <a download="" target="_blank" id="profileLink" cla…>…</a> +3ms
  pw:api attempting click action +4ms
  pw:api   waiting for element to be visible, enabled and stable +1ms
  pw:api   element is visible, enabled and stable +45ms
  pw:api   scrolling into view if needed +0ms
  pw:api   done scrolling +1ms
  pw:api   checking that element receives pointer events at (1018.4,345.75) +4ms
  pw:api   element does receive pointer events +3ms
  pw:api   performing click action +0ms
  pw:api   click action done +28ms
  pw:api   waiting for scheduled navigations to finish +0ms
  pw:api   navigations have finished +0ms
  pw:api   "domcontentloaded" event fired +16ms
  pw:api   "load" event fired +0ms
  pw:api   "networkidle" event fired +1s
Traceback (most recent call last):
  File "test-pw.py", line 38, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "test-pw.py", line 33, in main
    await page.click("#profileLink")
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_async_base.py", line 54, in __aexit__
    await self._event.value
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_async_base.py", line 35, in value
    return mapping.from_maybe_impl(await self._future)
playwright._impl._api_types.TimeoutError: Timeout while waiting for event "download"`

**Comment by mxschmitt** [comment]
Unfortunately the logs don't say much about the issue, since its probably on browser level. Would it be possible that you create a small reproducible for us in form of a GitHub repo with .NET Blazor? Otherwise its hard for us to repro and support, thanks!

(Web Assembly should work everywhere except on WebKit+Win)

**Comment by mxschmitt** [comment]
Closing since there was no activity on this issue. Please reopen / create a new issue if you still encounter unexpected behaviour.
