### ISSUE TITLE
[Question]: Incompatible with Enigma Virtual Box 

### ISSUE THREAD

**Issue by dennis8989** [microsoft/playwright-python#825]
### Your question

I use pyinstaller -F to make a exe file, but it works very slowly.
So, I decided to use pyinstaller -D to build a folder,
then packing the folder by Enigma Virtual Box.
but when execute the exe file, it shows the error as below

File "playwright\sync_api\_context_manager.py", line 70, in __enter__
AttributeError: 'PlaywrightContextManager' object has no attribute '_playwright'
[30224] Failed to execute script 'ADV_GetDriver' due to unhandled exception!
--- Logging error ---
--- Logging error ---
Exception ignored in: <bound method BaseEventLoop.call_exception_handler of <ProactorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "asyncio\base_events.py", line 1771, in call_exception_handler
  File "logging\__init__.py", line 1463, in error
  File "logging\__init__.py", line 1577, in _log
  File "logging\__init__.py", line 1587, in handle
  File "logging\__init__.py", line 1657, in callHandlers
  File "logging\__init__.py", line 948, in handle
  File "logging\__init__.py", line 1087, in emit
  File "logging\__init__.py", line 1001, in handleError
  File "traceback.py", line 103, in print_exception
  File "traceback.py", line 508, in __init__
  File "traceback.py", line 366, in extract
  File "traceback.py", line 288, in line
  File "linecache.py", line 30, in getline
  File "linecache.py", line 46, in getlines
  File "linecache.py", line 101, in updatecache
  File "PyInstaller\loader\pyimod03_importers.py", line 342, in get_source
NameError: name 'open' is not defined

**Comment by mxschmitt** [comment]
Please provide more bug details, the best would be a minimum reproducible in form of a git repo, also I would recommend to wait for the next release, where we have added support for Pyinstaller.

**Comment by mxschmitt** [comment]
Closing since there was no activity on this issue. Please reopen / create a new issue with a reproducible if you still encounter unexpected behaviour.
