### ISSUE TITLE
[Question]: After using Pyinstaller to package the program as an EXE file, the runtime error reported that the offender was wrong

### ISSUE THREAD

**Issue by tufbel** [microsoft/playwright-python#829]
### Your question

After using Pyinstall to package the program as an EXE file, the runtime error reported that the offender was wrong.
```
Traceback (most recent call last):
  File "main.py", line 73, in <module>
  File "typer\main.py", line 214, in __call__
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "typer\main.py", line 497, in wrapper
  File "main.py", line 64, in run_shift_excel
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "main.py", line 31, in shift_excel
  File "playwright\async_api\_context_manager.py", line 47, in __aenter__
  File "playwright\_impl\_transport.py", line 108, in run
  File "asyncio\subprocess.py", line 236, in create_subprocess_exec
  File "asyncio\base_events.py", line 1630, in subprocess_exec
  File "asyncio\windows_events.py", line 389, in _make_subprocess_transport
  File "asyncio\base_subprocess.py", line 36, in __init__
  File "asyncio\windows_events.py", line 885, in _start
  File "asyncio\windows_utils.py", line 153, in __init__
  File "subprocess.py", line 858, in __init__
  File "subprocess.py", line 1311, in _execute_child
FileNotFoundError: [WinError 2] 
```

**Comment by mxschmitt** [comment]
Pyinstaller support is not yet available, please wait until 1.13.1 was released.

**Comment by tufbel** [comment]
> Pyinstaller support is not yet available, please wait until 1.13.1 was released.

ty

**Comment by tufbel** [comment]
Can I specify the location of my ChromeDriver as I do with seleium?

**Comment by mxschmitt** [comment]
Playwright does not use ChromeDriver. It uses normal Chromium which gets installed via playwright install. See here for the docs for Pyinstaller which you should be able to use when you install it via Git.

https://playwright.dev/python/docs/next/intro#pyinstaller

```
pip install git+https://github.com/microsoft/playwright-python
PLAYWRIGHT_BROWSERS_PATH=0 playwright install chromium
pyinstaller -F test.py
./dist/test
```

**Comment by tufbel** [comment]
> Playwright does not use ChromeDriver. It uses normal Chromium which gets installed via playwright install. See here for the docs for Pyinstaller which you should be able to use when you install it via Git.
> 
> https://playwright.dev/python/docs/next/intro#pyinstaller
> 
> ```
> pip install git+https://github.com/microsoft/playwright-python
> PLAYWRIGHT_BROWSERS_PATH=0 playwright install chromium
> pyinstaller -F test.py
> ./dist/test
> ```

ty
