### ISSUE TITLE
[Question]: After i pyinstaller my .py, it went wrong!AttributeError: 'PlaywrightContextManager' object has no attribute '_playwright'

### ISSUE THREAD

**Issue by scouthe** [microsoft/playwright-python#874]
### Your question

Traceback (most recent call last):
  File "microsoft.py", line 281, in <module>
  File "microsoft.py", line 223, in duihuan
  File "site-packages\playwright\sync_api\_context_manager.py", line 70, in __enter__
AttributeError: 'PlaywrightContextManager' object has no attribute '_playwright'
[31880] Failed to execute script microsoft
Future exception was never retrieved
future: <Future finished exception=FileNotFoundError(2, '系统找不到指定的文件。', None, 2, None)>
Traceback (most recent call last):
  File "site-packages\playwright\_impl\_transport.py", line 114, in run
  File "asyncio\subprocess.py", line 236, in create_subprocess_exec
  File "asyncio\base_events.py", line 1630, in subprocess_exec
  File "asyncio\windows_events.py", line 385, in _make_subprocess_transport
  File "asyncio\base_subprocess.py", line 36, in __init__
  File "asyncio\windows_events.py", line 881, in _start
  File "asyncio\windows_utils.py", line 153, in __init__
  File "subprocess.py", line 854, in __init__
  File "subprocess.py", line 1307, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by mxschmitt** [comment]
How did you create your executable? Did you follow this guide? https://playwright.dev/python/docs/intro#pyinstaller

**Comment by scouthe** [comment]
yes, i try that ways ,but it still doesn't work, the same error

**Comment by mxschmitt** [comment]
Do you have a reproducible in form of a GitHub repository? So we can try to reproduce it.

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale or did not get enough upvotes in the past. Please create a new issue with a detailed reproducible or feature request if you still face issues.
