### ISSUE TITLE
[Bug]: page.get_attribute hanging if selector does not return results

### ISSUE THREAD

**Issue by pawelmhm** [microsoft/playwright-python#922]
### Playwright version

1.15.0

### Operating system

Linux

### What browsers are you seeing the problem on?

Chromium

### Other information

Python 3.9.1

### What happened? / Describe the bug

[page.get_attribute method](https://playwright.dev/python/docs/api/class-page#page-get-attribute) accepts optional timeout argument, when set to zero method should disable timeout, setting strict=False should also not require call to resolve to single element. I pass both strict=False and timeout=0, but method is just hanging, not returning anything.

My expectation: it should return None. 

### Code snippet to reproduce your bug

```python
# example.py
import asyncio
from playwright.async_api import async_playwright

async def main():
    url = "https://quotes.toscrape.com/"
    async with async_playwright() as p:
        browser_type = p.chromium
        browser = await browser_type.launch()
        page = await browser.new_page()
        await page.goto(url)

        # selector present, should print value and prints it
        value = await page.get_attribute("h1 a", "href",
                                         timeout=0, strict=False)
        print(value)

        # selector H10 not present, should print None, instead it hangs
        value = await page.get_attribute("h10 a", "href",
                                         timeout=0, strict=False)
        print(value)
        await page.screenshot(path=f'example-{browser_type.name}.png',
                              full_page=True)
        await browser.close()

asyncio.run(main())
```

### Relevant log output

In output you can see "/" is prnted, so get_attribute gets attribute if its there, but then script hangs, no result is returned, neither None nor string.

```shell
╰─>$ python example.py
/
^C^CTraceback (most recent call last):
  File "/home/pawel/.pyenv/versions/3.9.1/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/pawel/.pyenv/versions/3.9.1/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/home/pawel/.pyenv/versions/3.9.1/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/home/pawel/.pyenv/versions/3.9.1/lib/python3.9/asyncio/base_events.py", line 1854, in _run_once
    event_list = self._selector.select(timeout)
  File "/home/pawel/.pyenv/versions/3.9.1/lib/python3.9/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pawel/xxx/example.py", line 25, in <module>
    asyncio.run(main())
  File "/home/pawel/.pyenv/versions/3.9.1/lib/python3.9/asyncio/runners.py", line 47, in run
    _cancel_all_tasks(loop)
  File "/home/pawel/.pyenv/versions/3.9.1/lib/python3.9/asyncio/runners.py", line 63, in _cancel_all_tasks
    loop.run_until_complete(
  File "/home/pawel/.pyenv/versions/3.9.1/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/home/pawel/.pyenv/versions/3.9.1/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/home/pawel/.pyenv/versions/3.9.1/lib/python3.9/asyncio/base_events.py", line 1854, in _run_once
    event_list = self._selector.select(timeout)
  File "/home/pawel/.pyenv/versions/3.9.1/lib/python3.9/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
```

**Comment by mxschmitt** [comment]
This is expected. `Page.get_attribute` will wait until the element is there and only resolves when an actual element (or more if !strict) was found.

Disabling timeout via `timeout = 0` means it will wait forever. You can use get_attribute with a low timeout and then it'll throw that the element could not be found. What is your actual use-case?
