### ISSUE TITLE
[Bug]: RuntimeError: no running event loop with multiprocessing

### ISSUE THREAD

**Issue by hrynkodev** [microsoft/playwright-python#937]
### Playwright version

1.12.1

### Operating system

Linux

### Other information

Python 3.8
Ubuntu/Xubuntu 20.04

### What happened? / Describe the bug

I'm using https://github.com/davidteather/TikTok-Api that contains playwright's `sync_api` inside of it, and I've tried to use multiprocessing with that lib to improve the performance, but each time running that I'm getting following error:
`RuntimeError: no running event loop`. 
Are there any workarounds or should I do something on my own and use `async_playwright`?

### Code snippet to reproduce your bug

```shell
import random

from playwright.sync_api import sync_playwright
from multiprocessing import Pool

playwright = sync_playwright().start()


def create_context():
    browser = playwright.webkit.launch()

    iphone = playwright.devices["iPhone 11 Pro"]
    iphone["viewport"] = {
        "width": random.randint(320, 1920),
        "height": random.randint(320, 1920),
    }
    iphone["device_scale_factor"] = random.randint(1, 3)
    iphone["is_mobile"] = random.randint(1, 2) == 1
    iphone["has_touch"] = random.randint(1, 2) == 1

    iphone['bypass_csp'] = True

    context = browser.new_context(**iphone)

    return context


with Pool(3) as p:
    result = p.map(func=create_context, iterable=range(3))
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/user/PyCharmProjects/TtApiTest/helpers/mp_test.py", line 10, in create_context
    browser = playwright.webkit.launch()
  File "/home/user/PyCharmProjects/TtApiTest/venv/lib/python3.8/site-packages/playwright/sync_api/_generated.py", line 9430, in launch
    self._sync(
  File "/home/user/PyCharmProjects/TtApiTest/venv/lib/python3.8/site-packages/playwright/_impl/_sync_base.py", line 103, in _sync
    return task.result()
  File "/home/user/PyCharmProjects/TtApiTest/venv/lib/python3.8/site-packages/playwright/_impl/_browser_type.py", line 90, in launch
    raise e
  File "/home/user/PyCharmProjects/TtApiTest/venv/lib/python3.8/site-packages/playwright/_impl/_browser_type.py", line 86, in launch
    return from_channel(await self._channel.send("launch", params))
  File "/home/user/PyCharmProjects/TtApiTest/venv/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 36, in send
    return await self.inner_send(method, params, False)
  File "/home/user/PyCharmProjects/TtApiTest/venv/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 48, in inner_send
    done, pending = await asyncio.wait(
  File "/usr/lib/python3.8/asyncio/tasks.py", line 418, in wait
    loop = events.get_running_loop()
RuntimeError: no running event loop
```

**Comment by mxschmitt** [comment]
The Python `multiprocessing` module has implemented concurrency by spawning it via additional sub-processes. This means, no sharing of non-basic objects e.g. BrowserContexts is possible (playwright object).

In the following example I adjusted your example, that Playwright gets launched in each process, it navigates to the specific URL and returns its value back to the main process. Keep in mind, that the value needs to be a primitive type, in this specific case it's a `str`.

```py
import random

from playwright.sync_api import sync_playwright
from multiprocessing import Pool



def create_context(something):
    playwright = sync_playwright().start()
    browser = playwright.webkit.launch()

    iphone = playwright.devices["iPhone 11 Pro"]
    iphone["viewport"] = {
        "width": random.randint(320, 1920),
        "height": random.randint(320, 1920),
    }
    iphone["device_scale_factor"] = random.randint(1, 3)
    iphone["is_mobile"] = random.randint(1, 2) == 1
    iphone["has_touch"] = random.randint(1, 2) == 1

    iphone['bypass_csp'] = True

    context = browser.new_context(**iphone)
    
    page = context.new_page()
    page.goto("https://playwright.dev")
    
    content = page.content()
    
    browser.close()
    playwright.stop()

    return content

if __name__ == '__main__':
    with Pool(3) as p:
        result = p.map(func=create_context, iterable=range(3))
    breakpoint()
```

Does this work for your use-case? The best performance and concurrency you can get when using the async API, including async.gather etc.

**Comment by mxschmitt** [comment]
Closing since its answered.
