### ISSUE TITLE
[Bug]: Inexplicable closure in multithreads after adding route

### ISSUE THREAD

**Issue by Konano** [microsoft/playwright-python#956]
### Playwright version

1.15.2-1633455481000

### Operating system

Linux

### What browsers are you seeing the problem on?

Chromium

### What happened? / Describe the bug

When I add a route about block_aggressively, the program runs for a while and then quits with an error. Then when I remove the route or reduce max_workers, it works. 

It can also works when no route and the max_workers is 32. This confuses me.

Will adding routing cause playwright to be unstable? 

### Code snippet to reproduce your bug

```shell
from playwright.sync_api import sync_playwright
from playwright._impl._api_types import Error as PwError
from pathlib import Path
import random
import threadpool
import threading
from playwright.sync_api import sync_playwright
from concurrent.futures import ThreadPoolExecutor, ProcessPoolExecutor

class CrawlerError(Exception):
    """ Crawler Error """

excluded_resource_types = ['image', 'media', 'font']

def block_aggressively(route):
    if (route.request.resource_type in excluded_resource_types):
        route.abort()
    else:
        route.continue_()

class Tls(threading.local):
    def __init__(self) -> None:
        self.playwright = sync_playwright().start()
        print("Create playwright instance in Thread", threading.current_thread().name)

class Worker:
    tls = Tls()

    def run(self):
        print("Launched worker in ", threading.current_thread().name)
        browser = self.tls.playwright.chromium.launch()
        context = browser.new_context()
        page = browser.new_page()
        page.route('**/*', block_aggressively)
        page.goto("http://baidu.com/")
        page.close()
        context.close()
        browser.close()
        print("Stopped worker in ", threading.current_thread().name)

if __name__ == "__main__":
    with ThreadPoolExecutor(max_workers=8) as executor:
        for _ in range(32):
            worker = Worker()
            executor.submit(worker.run)
```

### Relevant log output

```shell
Create playwright instance in Thread MainThread
Launched worker in  ThreadPoolExecutor-0_0
Launched worker in  ThreadPoolExecutor-0_1
Launched worker in  ThreadPoolExecutor-0_2
Launched worker in  ThreadPoolExecutor-0_3
Launched worker in  ThreadPoolExecutor-0_4
Launched worker in  ThreadPoolExecutor-0_5
Launched worker in  ThreadPoolExecutor-0_6
Launched worker in  ThreadPoolExecutor-0_7
Create playwright instance in Thread ThreadPoolExecutor-0_0
Create playwright instance in Thread ThreadPoolExecutor-0_2
Create playwright instance in Thread ThreadPoolExecutor-0_1
Create playwright instance in Thread ThreadPoolExecutor-0_4
Create playwright instance in Thread ThreadPoolExecutor-0_3
Create playwright instance in Thread ThreadPoolExecutor-0_7
Create playwright instance in Thread ThreadPoolExecutor-0_6
Create playwright instance in Thread ThreadPoolExecutor-0_5
Launched worker in  ThreadPoolExecutor-0_2
Launched worker in  ThreadPoolExecutor-0_0
Launched worker in  ThreadPoolExecutor-0_3
Launched worker in  ThreadPoolExecutor-0_7
Launched worker in  ThreadPoolExecutor-0_5
Launched worker in  ThreadPoolExecutor-0_7
Launched worker in  ThreadPoolExecutor-0_5
Stopped worker in  ThreadPoolExecutor-0_4
Launched worker in  ThreadPoolExecutor-0_4
Stopped worker in  ThreadPoolExecutor-0_1
Launched worker in  ThreadPoolExecutor-0_1
Exception in callback SyncBase._sync.<locals>.callback(<Task finishe...been closed')>) at /home/nano/.local/lib/python3.8/site-packages/playwright/_impl/_sync_base.py:104
handle: <Handle SyncBase._sync.<locals>.callback(<Task finishe...been closed')>) at /home/nano/.local/lib/python3.8/site-packages/playwright/_impl/_sync_base.py:104>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/nano/.local/lib/python3.8/site-packages/playwright/_impl/_sync_base.py", line 105, in callback
    g_self.switch()
  File "/home/nano/.local/lib/python3.8/site-packages/playwright/_impl/_page.py", line 186, in <lambda>
    lambda params: self._on_route(
  File "/home/nano/.local/lib/python3.8/site-packages/playwright/_impl/_page.py", line 217, in _on_route
    result = handler_entry.handle(route, request)
  File "/home/nano/.local/lib/python3.8/site-packages/playwright/_impl/_helper.py", line 221, in handle
    return cast(
  File "/home/nano/.local/lib/python3.8/site-packages/playwright/_impl/_impl_to_api_mapping.py", line 89, in wrapper_func
    return handler(
  File "crawler.py", line 25, in block_aggressively
    route.continue_()
  File "/home/nano/.local/lib/python3.8/site-packages/playwright/sync_api/_generated.py", line 739, in continue_
    self._sync(
  File "/home/nano/.local/lib/python3.8/site-packages/playwright/_impl/_sync_base.py", line 111, in _sync
    return task.result()
  File "/home/nano/.local/lib/python3.8/site-packages/playwright/_impl/_network.py", line 239, in continue_
    await self._channel.send("continue", cast(Any, overrides))
  File "/home/nano/.local/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/home/nano/.local/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 57, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target page, context or browser has been closed
Exception in callback SyncBase._sync.<locals>.callback(<Task finishe...been closed')>) at /home/nano/.local/lib/python3.8/site-packages/playwright/_impl/_sync_base.py:104
handle: <Handle SyncBase._sync.<locals>.callback(<Task finishe...been closed')>) at /home/nano/.local/lib/python3.8/site-packages/playwright/_impl/_sync_base.py:104>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/nano/.local/lib/python3.8/site-packages/playwright/_impl/_sync_base.py", line 105, in callback
    g_self.switch()
  File "/home/nano/.local/lib/python3.8/site-packages/playwright/_impl/_page.py", line 186, in <lambda>
    lambda params: self._on_route(
  File "/home/nano/.local/lib/python3.8/site-packages/playwright/_impl/_page.py", line 217, in _on_route
    result = handler_entry.handle(route, request)
  File "/home/nano/.local/lib/python3.8/site-packages/playwright/_impl/_helper.py", line 221, in handle
    return cast(
  File "/home/nano/.local/lib/python3.8/site-packages/playwright/_impl/_impl_to_api_mapping.py", line 89, in wrapper_func
    return handler(
  File "crawler.py", line 25, in block_aggressively
    route.continue_()
  File "/home/nano/.local/lib/python3.8/site-packages/playwright/sync_api/_generated.py", line 739, in continue_
    self._sync(
  File "/home/nano/.local/lib/python3.8/site-packages/playwright/_impl/_sync_base.py", line 111, in _sync
    return task.result()
  File "/home/nano/.local/lib/python3.8/site-packages/playwright/_impl/_network.py", line 239, in continue_
    await self._channel.send("continue", cast(Any, overrides))
  File "/home/nano/.local/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/home/nano/.local/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 57, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target page, context or browser has been closed
Stopped worker in  ThreadPoolExecutor-0_6
Launched worker in  ThreadPoolExecutor-0_6
Launched worker in  ThreadPoolExecutor-0_4
Stopped worker in  ThreadPoolExecutor-0_0
Launched worker in  ThreadPoolExecutor-0_0
Stopped worker in  ThreadPoolExecutor-0_2
Launched worker in  ThreadPoolExecutor-0_2
Stopped worker in  ThreadPoolExecutor-0_3
Launched worker in  ThreadPoolExecutor-0_3
Stopped worker in  ThreadPoolExecutor-0_7
Launched worker in  ThreadPoolExecutor-0_7
Launched worker in  ThreadPoolExecutor-0_0
Launched worker in  ThreadPoolExecutor-0_3
Stopped worker in  ThreadPoolExecutor-0_5
Launched worker in  ThreadPoolExecutor-0_5
```

**Comment by Konano** [comment]
`page.goto("http://baidu.com/", wait_until='networkidle')` can work
